playlist 노래 장르 파악하기

In [135]:
import pandas as pd
train_data= pd.read_csv(r'C:\Users\jmlee\Desktop\kakao_arena\csv_data\train.csv')
song_meta= pd.read_csv(r'C:\Users\jmlee\Desktop\kakao_arena\csv_data\song_meta.csv')
genre= pd.read_csv(r'C:\Users\jmlee\Desktop\kakao_arena\csv_data\genre.csv')
train_data

,Unnamed: 0,tags,id,plylst_title,songs,like_cnt,updt_date
0,0,['락'],61281,여행같은 음악,"[525514, 129701, 383374, 562083, 297861, 13954...",71,2013-12-19 18:36:19.000
1,1,"['추억', '회상']",10532,요즘 너 말야,"[432406, 675945, 497066, 120377, 389529, 24427...",1,2014-12-02 16:19:42.000
2,2,"['까페', '잔잔한']",76951,"편하게, 잔잔하게 들을 수 있는 곡.-","[83116, 276692, 166267, 186301, 354465, 256598...",17,2017-08-28 07:09:34.000
3,3,"['연말', '눈오는날', '캐럴', '분위기', '따듯한', '크리스마스캐럴', ...",147456,크리스마스 분위기에 흠뻑 취하고 싶을때,"[394031, 195524, 540149, 287984, 440773, 10033...",33,2019-12-05 15:15:18.000
4,4,['댄스'],27616,추억의 노래 ㅋ,"[159327, 553610, 5130, 645103, 294435, 100657,...",9,2011-10-25 13:54:56.000
...,...,...,...,...,...,...,...
115066,115066,"['록메탈', '밴드사운드', '록', '락메탈', '메탈', '락', 'extre...",120325,METAL E'SM #2,"[429629, 441511, 612106, 516359, 691768, 38714...",3,2020-04-17 04:31:11.000
115067,115067,['일렉'],106976,빠른 리스너를 위한 따끈따끈한 최신 인기 EDM 모음!,"[321330, 216057, 534472, 240306, 331098, 23288...",13,2015-12-24 17:23:19.000
115068,115068,"['담시', '가족', '눈물', '그리움', '주인공', '나의_이야기', '사랑...",11343,#1. 눈물이 앞을 가리는 나의_이야기,"[50512, 249024, 250608, 371171, 229942, 694943...",4,2019-08-16 20:59:22.000
115069,115069,"['잔잔한', '버스', '퇴근버스', 'Pop', '풍경', '퇴근길']",131982,퇴근 버스에서 편히 들으면서 하루를 마무리하기에 좋은 POP,"[533534, 608114, 343608, 417140, 609009, 30217...",4,2019-10-25 23:40:42.000
115070,115070,"['노래추천', '팝송추천', '팝송', '팝송모음']",100389,FAVORITE POPSONG!!!,"[26008, 456354, 324105, 89871, 135272, 143548,...",17,2020-04-18 20:35:06.000

In [136]:
song=train_data["songs"][0].replace("[","").replace("]","")
list_str = song.split(",")
list_str[:]

['525514',
 ' 129701',
 ' 383374',
 ' 562083',
 ' 297861',
 ' 139541',
 ' 351214',
 ' 650298',
 ' 531057',
 ' 205238',
 ' 706183',
 ' 127099',
 ' 660493',
 ' 461973',
 ' 121455',
 ' 72552',
 ' 223955',
 ' 324992',
 ' 50104']

In [147]:
int(list_str[0])

525514

In [214]:
length=len(list_str)
a=[]
for i in range(0,length-1):
    new_data=song_meta.loc[song_meta.id==int(list_str[i]),['id','song_gn_dtl_gnr_basket','song_name']] #플레이리스트별 장르  type=df

In [215]:
new_data

            id song_gn_dtl_gnr_basket  song_name
324992  324992             ['GN0901']  If We Try