# 0. import libraries

In [1]:
!pip3 install --user sklearn
!pip install -U scikit-learn scipy matplotlib
!pip install seaborn

Requirement already satisfied: sklearn in c:\users\308_2\appdata\roaming\python\python37\site-packages (0.0)
Requirement already satisfied: scikit-learn in c:\users\308_2\.conda\envs\minji\lib\site-packages (from sklearn) (0.23.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\308_2\.conda\envs\minji\lib\site-packages (from scikit-learn->sklearn) (2.1.0)
Requirement already satisfied: scipy>=0.19.1 in c:\users\308_2\.conda\envs\minji\lib\site-packages (from scikit-learn->sklearn) (1.5.1)
Requirement already satisfied: numpy>=1.13.3 in c:\users\308_2\.conda\envs\minji\lib\site-packages (from scikit-learn->sklearn) (1.19.0)
Requirement already satisfied: joblib>=0.11 in c:\users\308_2\.conda\envs\minji\lib\site-packages (from scikit-learn->sklearn) (0.16.0)
Requirement already up-to-date: scikit-learn in c:\users\308_2\.conda\envs\minji\lib\site-packages (0.23.1)
Requirement already up-to-date: scipy in c:\users\308_2\.conda\envs\minji\lib\site-packages (1.5.1)
Requirement already up-to-date: matplotlib in c:\users\308_2\.conda\envs\minji\lib\site-packages (3.3.0)
Requirement already satisfied, skipping upgrade: numpy>=1.13.3 in c:\users\308_2\.conda\envs\minji\lib\site-packages (from scikit-learn) (1.19.0)
Requirement already satisfied, skipping upgrade: threadpoolctl>=2.0.0 in c:\users\308_2\.conda\envs\minji\lib\site-packages (from scikit-learn) (2.1.0)
Requirement already satisfied, skipping upgrade: joblib>=0.11 in c:\users\308_2\.conda\envs\minji\lib\site-packages (from scikit-learn) (0.16.0)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.1 in c:\users\308_2\.conda\envs\minji\lib\site-packages (from matplotlib) (2.8.1)
Requirement already satisfied, skipping upgrade: cycler>=0.10 in c:\users\308_2\.conda\envs\minji\lib\site-packages (from matplotlib) (0.10.0)
Requirement already satisfied, skipping upgrade: kiwisolver>=1.0.1 in c:\users\308_2\.conda\envs\minji\lib\site-packages (from matplotlib) (1.2.0)
Requirement already satisfied, skipping upgrade: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\users\308_2\.conda\envs\minji\lib\site-packages (from matplotlib) (2.4.7)
Requirement already satisfied, skipping upgrade: pillow>=6.2.0 in c:\users\308_2\.conda\envs\minji\lib\site-packages (from matplotlib) (7.2.0)
Requirement already satisfied, skipping upgrade: six>=1.5 in c:\users\308_2\.conda\envs\minji\lib\site-packages (from python-dateutil>=2.1->matplotlib) (1.15.0)
Requirement already satisfied: seaborn in c:\users\308_2\.conda\envs\minji\lib\site-packages (0.10.1)
Requirement already satisfied: numpy>=1.13.3 in c:\users\308_2\.conda\envs\minji\lib\site-packages (from seaborn) (1.19.0)
Requirement already satisfied: matplotlib>=2.1.2 in c:\users\308_2\.conda\envs\minji\lib\site-packages (from seaborn) (3.3.0)
Requirement already satisfied: scipy>=1.0.1 in c:\users\308_2\.conda\envs\minji\lib\site-packages (from seaborn) (1.5.1)
Requirement already satisfied: pandas>=0.22.0 in c:\users\308_2\.conda\envs\minji\lib\site-packages (from seaborn) (1.0.5)
Requirement already satisfied: pillow>=6.2.0 in c:\users\308_2\.conda\envs\minji\lib\site-packages (from matplotlib>=2.1.2->seaborn) (7.2.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\308_2\.conda\envs\minji\lib\site-packages (from matplotlib>=2.1.2->seaborn) (1.2.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\308_2\.conda\envs\minji\lib\site-packages (from matplotlib>=2.1.2->seaborn) (2.8.1)
Requirement already satisfied: cycler>=0.10 in c:\users\308_2\.conda\envs\minji\lib\site-packages (from matplotlib>=2.1.2->seaborn) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\users\308_2\.conda\envs\minji\lib\site-packages (from matplotlib>=2.1.2->seaborn) (2.4.7)
Requirement already satisfied: pytz>=2017.2 in c:\users\308_2\.conda\envs\minji\lib\site-packages (from pandas>=0.22.0->seaborn) (2020.1)
Requirement already satisfied: six>=1.5 in c:\users\308_2\.conda\envs\minji\lib\site-packages (from python-dateutil>=2.1->matplotlib>=2.1.2->seaborn) (1.15.0)

In [1]:
# import libraries
import json
import re # regular expression
import gc # to collect memory
from datetime import datetime

import tensorflow as tf
import pandas as pd
import numpy as np

# for NLP
# from konlpy.tag import Kkma
# from konlpy.utils import pprint
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

import matplotlib.pyplot as plt
import seaborn as sns
# import missingno as msno

plt.style.use('seaborn')
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 50)

import matplotlib
matplotlib.rcParams['axes.unicode_minus'] = False
font_name = matplotlib.font_manager.FontProperties(fname = 'c:/Windows/Fonts/malgun.ttf').get_name()
matplotlib.rc('font', family = font_name)

C:\Users\user\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\user\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\user\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\user\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\user\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\user\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
C:\Users\user\Anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\user\Anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\user\Anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\user\Anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\user\Anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\user\Anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

---
# 1. data

In [3]:
# load json files
with open("./res/genre_gn_all.json", encoding = 'utf-8') as json_file: genre_gn_all = json.load(json_file)
with open("./res/song_meta.json", encoding = 'utf-8') as json_file: song_meta = json.load(json_file)
with open("./res/train.json", encoding = 'utf-8') as json_file: train = json.load(json_file)
with open("./res/val.json", encoding = 'utf-8') as json_file: valid = json.load(json_file)

# json to dataframe
genre_gn_all = pd.Series(genre_gn_all).to_frame('genre').reset_index().rename({'index' : 'gen_id'}, axis = 1)
song_meta = pd.DataFrame(song_meta)
train = pd.DataFrame(train)
valid = pd.DataFrame(valid)

In [4]:
#대분류장르코드
# 장르코드 뒷자리 두 자리가 00인 코드를 필터링
gnr_code = genre_gn_all[genre_gn_all['gen_id'].str[-2:] == '00']

In [5]:
#상세장르코드
# 장르코드 뒷자리 두 자리가 00이 아닌 코드를 필터링
dtl_gnr_code = genre_gn_all[genre_gn_all['gen_id'].str[-2:] != '00']
dtl_gnr_code.rename(columns = {'gen_id' : 'dtl_gen_id', 'genre' : 'dtl_genre'}, inplace = True)

C:\Users\user\Anaconda3\lib\site-packages\pandas\core\frame.py:4133: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [6]:
train

,tags,id,plylst_title,songs,like_cnt,updt_date
0,[락],61281,여행같은 음악,"[525514, 129701, 383374, 562083, 297861, 13954...",71,2013-12-19 18:36:19.000
1,"[추억, 회상]",10532,요즘 너 말야,"[432406, 675945, 497066, 120377, 389529, 24427...",1,2014-12-02 16:19:42.000
2,"[까페, 잔잔한]",76951,"편하게, 잔잔하게 들을 수 있는 곡.-","[83116, 276692, 166267, 186301, 354465, 256598...",17,2017-08-28 07:09:34.000
3,"[연말, 눈오는날, 캐럴, 분위기, 따듯한, 크리스마스캐럴, 겨울노래, 크리스마스,...",147456,크리스마스 분위기에 흠뻑 취하고 싶을때,"[394031, 195524, 540149, 287984, 440773, 10033...",33,2019-12-05 15:15:18.000
4,[댄스],27616,추억의 노래 ㅋ,"[159327, 553610, 5130, 645103, 294435, 100657,...",9,2011-10-25 13:54:56.000
...,...,...,...,...,...,...
115066,"[록메탈, 밴드사운드, 록, 락메탈, 메탈, 락, extreme]",120325,METAL E'SM #2,"[429629, 441511, 612106, 516359, 691768, 38714...",3,2020-04-17 04:31:11.000
115067,[일렉],106976,빠른 리스너를 위한 따끈따끈한 최신 인기 EDM 모음!,"[321330, 216057, 534472, 240306, 331098, 23288...",13,2015-12-24 17:23:19.000
115068,"[담시, 가족, 눈물, 그리움, 주인공, 나의_이야기, 사랑, 친구]",11343,#1. 눈물이 앞을 가리는 나의_이야기,"[50512, 249024, 250608, 371171, 229942, 694943...",4,2019-08-16 20:59:22.000
115069,"[잔잔한, 버스, 퇴근버스, Pop, 풍경, 퇴근길]",131982,퇴근 버스에서 편히 들으면서 하루를 마무리하기에 좋은 POP,"[533534, 608114, 343608, 417140, 609009, 30217...",4,2019-10-25 23:40:42.000
115070,"[노래추천, 팝송추천, 팝송, 팝송모음]",100389,FAVORITE POPSONG!!!,"[26008, 456354, 324105, 89871, 135272, 143548,...",17,2020-04-18 20:35:06.000

In [7]:
song_meta

,song_gn_dtl_gnr_basket,issue_date,album_name,album_id,artist_id_basket,song_name,song_gn_gnr_basket,artist_name_basket,id
0,[GN0901],20140512,불후의 명곡 - 7080 추억의 얄개시대 팝송베스트,2255639,[2727],Feelings,[GN0900],[Various Artists],0
1,"[GN1601, GN1606]",20080421,"Bach : Partitas Nos. 2, 3 & 4",376431,[29966],"Bach : Partita No. 4 In D Major, BWV 828 - II....",[GN1600],[Murray Perahia],1
2,[GN0901],20180518,Hit,4698747,[3361],Solsbury Hill (Remastered 2002),[GN0900],[Peter Gabriel],2
3,"[GN1102, GN1101]",20151016,Feeling Right (Everything Is Nice) (Feat. Popc...,2644882,[838543],Feeling Right (Everything Is Nice) (Feat. Popc...,[GN1100],[Matoma],3
4,"[GN1802, GN1801]",20110824,그남자 그여자,2008470,[560160],그남자 그여자,[GN1800],[Jude Law],4
...,...,...,...,...,...,...,...,...,...
707984,[GN2001],19991219,The Best Best Of The Black President,65254,[166499],Coffin For Head Of State,[GN2000],[Fela Kuti],707984
707985,[GN0901],19860000,True Colors,44141,[11837],Change Of Heart,[GN0900],[Cyndi Lauper],707985
707986,"[GN0105, GN0101]",20160120,행보 2015 윤종신 / 작사가 윤종신 Live Part.1,2662866,[437],스치듯 안녕,[GN0100],[윤종신],707986
707987,"[GN1807, GN1801]",20131217,명상의 시간을 위한 뉴에이지 음악,2221722,[729868],숲의 빛,[GN1800],[Nature Piano],707987
707988,"[GN0601, GN0604]",19980000,김경호 Live,34663,[895],Queen 명곡 멜로디,[GN0600],[김경호],707988

# 2. 대분류에서 장르명과 일치하는 단어가 있는 태그를 찾기
---

---
## 1) tag dataframe 제작

In [8]:
# 플레이리스트 아이디(id)와 매핑된 태그(tags) 추출
plylst_tag_map = train[['id', 'tags']]

# unnest tags
plylst_tag_map_unnest = np.dstack(
    (
        np.repeat(plylst_tag_map.id.values, list(map(len, plylst_tag_map.tags))), 
        np.concatenate(plylst_tag_map.tags.values)
    )
)

# unnested 데이터프레임 생성 : plylst_tag_map
plylst_tag_map = pd.DataFrame(data = plylst_tag_map_unnest[0], columns = plylst_tag_map.columns)
plylst_tag_map['id'] = plylst_tag_map['id'].astype(str)

# unnest 객체 제거
del plylst_tag_map_unnest

In [9]:
plylst_tag_map

            id  tags
0        61281     락
1        10532    추억
2        10532    회상
3        76951    까페
4        76951   잔잔한
...        ...   ...
476326  131982   퇴근길
476327  100389  노래추천
476328  100389  팝송추천
476329  100389    팝송
476330  100389  팝송모음

[476331 rows x 2 columns]

### 이건 그냥 플레이리스트 아이디와 맵핑된 코드였음.. 416331개가 아님

In [10]:
# 태그 별 매핑 빈도 수 저장 
tag_cnt = plylst_tag_map.groupby('tags').tags.count().reset_index(name = 'mapping_cnt')
tag_cnt['tags'] = tag_cnt['tags'].astype(str)
tag_cnt['mapping_cnt'] = tag_cnt['mapping_cnt'].astype(int)

In [11]:
tag_cnt.head(100)

              tags  mapping_cnt
0                             1
1               00            4
2              007            3
3           007시리즈            2
4              00s            3
5              00년            6
6             00년대           27
7           00년대노래            1
8          00년대발라드            2
9           00년도노래            1
10            00년생            1
11              01            5
12            0129            1
13            015B            5
14              02            4
15              03            4
16             03월            1
17              04            5
18            0416            1
19            0421            1
20           04_29            1
21              05            2
22            0515            6
23              06            2
24              07            2
25            0802            1
26             08월            1
27            0930            1
28             09월            1
29        0channel            1
30            0개국어            2
31              0살           58
32              0시            1
33               1           20
34              10            4
35             100            5
36          100000            1
37           1000곡            3
38       1000만관객동원            1
39         1000칼로리            1
40            100곡            8
41            100번            2
42            100선            1
43       100억짜리피쳐링            1
44            100위            2
45           100주년            1
46             101            3
47            10cm           22
48             10곡            5
49        10년간의_기록            2
50            10년대            6
51            10년전            5
52             10대           17
53       10대가10대에게            1
54           10대감성            1
55         10대들의우상            1
56  10대의영원할것같았던순수함            1
57             10만            2
58            10만개            2
59            10분전            1
60             10살            1
61            10센치            1
62             10월           26
63          10월29일            1
64          10월4주차            2
65         10월_1주차            1
66         10월_2주차            1
67         10월_3주차            1
68         10월_4주차            1
69        10월마지막힙합            1
70           10월음악            1
71           10월힙합            1
72             10주            1
73            10주년            3
74         10주년축하해            1
75             10초            2
76             10화            2
77              11            4
78          110bpm            1
79            1124            1
80             113            1
81             11곡            1
82             11시            1
83             11월           31
84          11월11일            1
85           11월1일            1
86          11월1주차            1
87          11월20일            1
88          11월3주차            1
89          11월4주차            1
90         11월_2주차            1
91         11월_3주차            1
92          11월_컴백            1
93          11월넷째주            1
94          11월둘째주            1
95             11일            1
96             11화            2
97              12            2
98            1218            1
99            1222            1

In [12]:
tag_cnt.tail(100)

             tags  mapping_cnt
29060          힙플            2
29061       힙플라디오            1
29062       힙플레이스            1
29063         힙플페            3
29064         힙하게            1
29065         힙하고            1
29066      힙하고싶은날            1
29067         힙하다            4
29068        힙하우스            2
29069          힙한          209
29070      힙한_사운드            2
29071      힙한_세련된            7
29072      힙한_알앤비            1
29073        힙한감성            2
29074         힙한곡            9
29075        힙한노래            8
29076        힙한느낌            1
29077      힙한매장음악            4
29078        힙한뮤직            1
29079        힙한음악           12
29080       힙한음악한            1
29081        힙한트랙            2
29082        힙한팝송            1
29083          힙함            7
29084        힙함주의            2
29085          힙합         6413
29086       힙합CCM            3
29087        힙합DJ           11
29088       힙합RnB            3
29089        힙합감성           54
29090      힙합같은일렉            1
29091        힙합갬성           32
29092        힙합곡들            1
29093        힙합공연            2
29094       힙합그루브            1
29095        힙합까지            1
29096        힙합노래            7
29097        힙합댄스            4
29098         힙합돌            2
29099        힙합듀오            3
29100    힙합드라이브음악            1
29101       힙합라운지            2
29102       힙합레전드            1
29103      힙합레전드곡            1
29104       힙합리스트           12
29105         힙합만            1
29106       힙합매니아            6
29107       힙합멜로디            1
29108        힙합명곡            6
29109        힙합명반            1
29110        힙합뮤직            3
29111       힙합발라드            1
29112        힙합밴드            1
29113       힙합보부상            1
29114        힙합비트            3
29115       힙합선구자            1
29116        힙합소울           10
29117       힙합스타일            1
29118       힙합알앤비           13
29119        힙합앨범            1
29120        힙합엔비            1
29121        힙합엘이          233
29122        힙합엠알            1
29123        힙합연습            1
29124        힙합영화            1
29125         힙합왕            1
29126         힙합은            1
29127   힙합을선곡하는남자            2
29128   힙합을좋아하는여자            1
29129        힙합음악            9
29130         힙합의            2
29131       힙합의온도            1
29132       힙합의품격            1
29133       힙합인생곡            1
29134        힙합인스            2
29135        힙합입문            1
29136        힙합재즈            2
29137        힙합전설            1
29138         힙합존            2
29139        힙합추억            1
29140        힙합추천           11
29141     힙합컴필레이션            1
29142        힙합클럽           73
29143        힙합키즈            1
29144        힙합탑백            2
29145        힙합터부            1
29146        힙합트랙            8
29147        힙합팝송            1
29148      힙합팬이창민            1
29149      힙합페스티벌            1
29150    힙합플레이리스트            5
29151      힙합플레이야            2
29152  힙합플레이야2018            1
29153        힙합홍수            1
29154        힙합힙합            1
29155          힙해            5
29156         힙힙힙            2
29157        힛뎀포크            1
29158         힛뎀폭            1
29159        힛뎀폭스            2

In [13]:
tag_cnt

         tags  mapping_cnt
0                        1
1          00            4
2         007            3
3      007시리즈            2
4         00s            3
...       ...          ...
29155      힙해            5
29156     힙힙힙            2
29157    힛뎀포크            1
29158     힛뎀폭            1
29159    힛뎀폭스            2

[29160 rows x 2 columns]

### 태그 자체는 29159개였다!
전체 태그 저장해놓은 df: tag_cnt

---

## 2) 대분류에서 장르 name dataframe 만들기
- 유의사항
  - 중복 있음
  - 랩/힙합과 같이 /로 나눠진 것 존재
  - pop의 경우 팝이라는 단어로 더 많이 쓰임
---
- 중복 제거 필요
- / 있는 경우 나눠서 넣음
- 알앤비, 소울, rock, metal, 팝, country, 등등 단어 추가 (일단 생각나는게 이정도라서...)

In [14]:
gnr_code

     gen_id       genre
0    GN0100         발라드
6    GN0200          댄스
12   GN0300        랩/힙합
18   GN0400    R&B/Soul
22   GN0500        인디음악
32   GN0600        록/메탈
39   GN0700        성인가요
50   GN0800      포크/블루스
56   GN0900         POP
65   GN1000        록/메탈
80   GN1100      일렉트로니카
90   GN1200        랩/힙합
100  GN1300    R&B/Soul
109  GN1400  포크/블루스/컨트리
117  GN1500         OST
128  GN1600         클래식
144  GN1700          재즈
155  GN1800        뉴에이지
163  GN1900       J-POP
176  GN2000        월드뮤직
187  GN2100         CCM
198  GN2200      어린이/태교
215  GN2300        종교음악
218  GN2400          국악
225  GN2500         아이돌
232  GN2600      일렉트로니카
237  GN2700         EDM
242  GN2800       뮤직테라피
249  GN2900         뮤지컬
253  GN3000       크리스마스

In [15]:
genre_list=gnr_code[['genre']]

In [16]:
genre_list

          genre
0           발라드
6            댄스
12         랩/힙합
18     R&B/Soul
22         인디음악
32         록/메탈
39         성인가요
50       포크/블루스
56          POP
65         록/메탈
80       일렉트로니카
90         랩/힙합
100    R&B/Soul
109  포크/블루스/컨트리
117         OST
128         클래식
144          재즈
155        뉴에이지
163       J-POP
176        월드뮤직
187         CCM
198      어린이/태교
215        종교음악
218          국악
225         아이돌
232      일렉트로니카
237         EDM
242       뮤직테라피
249         뮤지컬
253       크리스마스

In [17]:
var_split = genre_list['genre'].str.split('/')
var_split


#value_name = var_split.str[0]

#2,3번째 항목에서 NaN 제거
value_name1 = var_split.str[1]
value_name1=value_name1[~value_name1.isnull()]
value_name2 = var_split.str[2]
value_name2=value_name2[~value_name2.isnull()]

#장르 리스트에서 /없애고, /로 나눈 항목 중 첫번째 것만 넣음
genre_list['genre'] = genre_list['genre'].str.split('/').str[0]

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [18]:
#object를 dataframe로
value_name1=pd.DataFrame(value_name1)
value_name1

    genre
12     힙합
18   Soul
32     메탈
50    블루스
65     메탈
90     힙합
100  Soul
109   블루스
198    태교

In [19]:
value_name2=pd.DataFrame(value_name2)
value_name2

    genre
109   컨트리

In [20]:
genre_list=pd.concat([genre_list, value_name1,value_name2], ignore_index=True)
genre_list

     genre
0      발라드
1       댄스
2        랩
3      R&B
4     인디음악
5        록
6     성인가요
7       포크
8      POP
9        록
10  일렉트로니카
11       랩
12     R&B
13      포크
14     OST
15     클래식
16      재즈
17    뉴에이지
18   J-POP
19    월드뮤직
20     CCM
21     어린이
22    종교음악
23      국악
24     아이돌
25  일렉트로니카
26     EDM
27   뮤직테라피
28     뮤지컬
29   크리스마스
30      힙합
31    Soul
32      메탈
33     블루스
34      메탈
35      힙합
36    Soul
37     블루스
38      태교
39     컨트리

In [21]:
genre_list=genre_list.drop_duplicates() #중복 제거

#index reset하겠음(문자 단위 검색 목적이므로)
genre_list=genre_list.reset_index()
del genre_list['index']

genre_list

     genre
0      발라드
1       댄스
2        랩
3      R&B
4     인디음악
5        록
6     성인가요
7       포크
8      POP
9   일렉트로니카
10     OST
11     클래식
12      재즈
13    뉴에이지
14   J-POP
15    월드뮤직
16     CCM
17     어린이
18    종교음악
19      국악
20     아이돌
21     EDM
22   뮤직테라피
23     뮤지컬
24   크리스마스
25      힙합
26    Soul
27      메탈
28     블루스
29      태교
30     컨트리

In [22]:
#키워드 추가
#dance, 알앤비, rock, 인디, 성인, 팝, 일렉트로닉, 키즈, 종교, idol, 소울, 일본(12개)
genre_list=genre_list.append([{'genre':'dance'},{'genre':'알앤비'},{'genre':'rock'},{'genre':'인디'},{'genre':'성인'},
                           {'genre':'팝'},{'genre':'일렉트로닉'},{'genre':'키즈'},{'genre':'종교'},{'genre':'idol'},
                              {'genre':'소울'},{'genre':'일본'}]
                          ,ignore_index=True)
genre_list

     genre
0      발라드
1       댄스
2        랩
3      R&B
4     인디음악
5        록
6     성인가요
7       포크
8      POP
9   일렉트로니카
10     OST
11     클래식
12      재즈
13    뉴에이지
14   J-POP
15    월드뮤직
16     CCM
17     어린이
18    종교음악
19      국악
20     아이돌
21     EDM
22   뮤직테라피
23     뮤지컬
24   크리스마스
25      힙합
26    Soul
27      메탈
28     블루스
29      태교
30     컨트리
31   dance
32     알앤비
33    rock
34      인디
35      성인
36       팝
37   일렉트로닉
38      키즈
39      종교
40    idol
41      소울
42      일본

---

## 3) 장르와 연관된 태그
tag_cnt: 태그 모음  
genre_list: 장르 모음

- 문자열 검색시 contains는 일부 포함된것도 검색
- isin은 완벽하게 일치인듯?

In [23]:
#'발라드'
print(genre_list['genre'][0])
test=tag_cnt[tag_cnt['tags'].str.contains(genre_list['genre'][0])] 
test=test.reset_index()
del test['index']
test

발라드

          tags  mapping_cnt
0      00년대발라드            2
1    1980년대발라드            1
2    1990년대발라드            2
3    2000년대발라드            6
4      7080발라드            1
..         ...          ...
114      한국발라드            6
115     한국형발라드            1
116      혼성발라드            1
117       힙발라드            4
118      힙합발라드            1

[119 rows x 2 columns]

In [24]:
#'댄스'
print(genre_list['genre'][1])
test=tag_cnt[tag_cnt['tags'].str.contains(genre_list['genre'][1])] 
test=test.reset_index()
del test['index']
test

댄스

           tags  mapping_cnt
0      2010년대댄스            1
1       30대댄스가요            1
2        8090댄스            1
3       80년대댄스팝            1
4       90년대_댄스            1
..          ...          ...
135      하우스_댄스            1
136  헬스장에서듣는댄스곡            1
137      혼성댄스그룹            1
138        힐링댄스            1
139        힙합댄스            4

[140 rows x 2 columns]

### 전체 출력(반복문)

In [25]:
for i in range(0,43):
    print("index %d: " %i,end='')
    print(genre_list['genre'][i]+'\n')
    test=tag_cnt[tag_cnt['tags'].str.contains(genre_list['genre'][i])] 
    test=test.reset_index()
    del test['index']
    print(test)
    print("\n---------------------------------------------------------\n")

index 0: 발라드

          tags  mapping_cnt
0      00년대발라드            2
1    1980년대발라드            1
2    1990년대발라드            2
3    2000년대발라드            6
4      7080발라드            1
..         ...          ...
114      한국발라드            6
115     한국형발라드            1
116      혼성발라드            1
117       힙발라드            4
118      힙합발라드            1

[119 rows x 2 columns]

---------------------------------------------------------

index 1: 댄스

           tags  mapping_cnt
0      2010년대댄스            1
1       30대댄스가요            1
2        8090댄스            1
3       80년대댄스팝            1
4       90년대_댄스            1
..          ...          ...
135      하우스_댄스            1
136  헬스장에서듣는댄스곡            1
137      혼성댄스그룹            1
138        힐링댄스            1
139        힙합댄스            4

[140 rows x 2 columns]

---------------------------------------------------------

index 2: 랩

         tags  mapping_cnt
0        CCM랩            1
1         감성랩           14
2       감성적인랩            1
3       갱스터_랩            1
4        갱스터랩           13
5        고등랩퍼            1
6         고랩2            1
7       국내랩힙합           31
8       국외랩힙합            2
9        남자는랩            1
10  남자는랩여자는노래            1
11      때려박는랩            1
12      때려밖는랩            1
13          랩         3421
14       랩OST            1
15       랩_힙합            1
16         랩과            1
17        랩노래           25
18        랩라인            1
19       랩메이킹            1
20        랩메탈            8
21       랩몬스터            3
22       랩발라드           13
23        랩보컬            4
24    랩비트페스티벌            1
25        랩소디            1
26     랩소디인블루            1
27      랩소디투어            1
28         랩송            2
29        랩스킬            1
30        랩스타            1
31        랩어택            1
32        랩으로            1
33        랩음악            2
34         랩의            1
35   랩이들어간CCM            1
36        랩찬양            1
37        랩코어            9
38       랩콜라보            1
39         랩퍼           16
40       랩퍼들의            1
41        랩힙합           78
42    랩힙합_디스전            1
43      마우스트랩            1
44        멈블랩            5
45       멜로디랩            3
46       발라드랩            7
47    방탄소년단_랩            2
48   보컬댄스랩다완벽            1
49    보헤미안랩소디           22
50        빠른랩            2
51        빡센랩            1
52        사랑랩            2
53       속사포랩            2
54        슬픈랩            1
55         싱랩            6
56        싱어랩            1
57        싱잉랩           30
58        써던랩            1
59    언프리티랩스타            7
60      에릭클랩튼            3
61        여자랩            2
62        외국랩            2
63        이모랩            1
64       이모트랩            1
65        이별랩            1
66      잘들리는랩            1
67        재즈랩            4
68     최우수랩앨범            1
69     치즈인더트랩            2
70       컨셔스랩            4
71      클라우드랩            3
72      타이트한랩            1
73         트랩          128
74       트랩비트            4
75       트랩소울            1
76      트랩하우스            1
77         팝랩           23
78     페어런트트랩            1
79      하드코어랩            2
80        한국랩            2
81        핫랩퍼            1
82      해외랩힙합           52

---------------------------------------------------------

index 3: R&B

Empty DataFrame
Columns: [tags, mapping_cnt]
Index: []

---------------------------------------------------------

index 4: 인디음악

              tags  mapping_cnt
0         감성적인인디음악            3
1     개성있는_인디음악으로만            1
2           국내인디음악            1
3   내_플레이리스트속_인디음악            1
4         들어봤을인디음악            1
5        매력적인_인디음악            1
6         몽환적인인디음악            1
7       분위기있는_인디음악            2
8         색다른_인디음악            1
9             인디음악          582
10          인디음악같은            1
11          인디음악다수           16
12           인디음악들            2
13           인디음악을            1
14          인디음악추천           12
15     일상에묻어나는인디음악            1
16      주목해야할_인디음악            1
17       차트에없는인디음악            2
18          추천인디음악            1
19          해외인디음악            1

---------------------------------------------------------

index 5: 록

         tags  mapping_cnt
0    10년간의_기록            2
1     2000년대록            1
2    20주년명작록팝            1
3       60년대록            9
4     70년대독일록            1
..        ...          ...
181       한국록           17
182        해록            1
183       해외록           19
184       헤비록            1
185    혼자듣는_록            1

[186 rows x 2 columns]

---------------------------------------------------------

index 6: 성인가요

         tags  mapping_cnt
0        성인가요           85
1  성인가요Top100            1
2     성인가요스테디            1
3      슬픈성인가요            1

---------------------------------------------------------

index 7: 포크

         tags  mapping_cnt
0      21세기포크            1
1      70년대포크            1
2        국내포크            2
3        미국포크            1
4     사이키델릭포크            1
5      아이리시포크            1
6       애시드포크            2
7     이달의인디포크            5
8        인디포크           16
9        전통포크            8
10        킨포크            1
11         포크          345
12   포크top100            1
13       포크듀오            1
14      포크라노스            2
15     포크라이스트            2
16  포크라이스트어워즈            1
17        포크락            2
18      포크러브송            1
19      포크레전드            1
20        포크록           35
21     포크리바이벌            4
22     포크리이스트            1
23       포크명곡            2
24    포크블루스차트            1
25        포크송           10
26        포크쇼            1
27      포크스테디            1
28       포크음악           10
29       포크인기            1
30       포크추천            1
31       포크탑백            1
32        포크팝           15
33      프렌치포크            1
34   프로그레시브포크            1
35       프릭포크            1
36       피치포크            2
37       한국포크            6
38    해외포크스테디            1
39    해외포크핫트랙            1
40       힛뎀포크            1

---------------------------------------------------------

index 8: POP

          tags  mapping_cnt
0     90년대JPOP            1
1         CPOP            6
2     DREAMPOP            1
3      EDM_POP            1
4       HIPPOP            3
5         JPOP          575
6        JPOPj            1
7     JPOP리메이크            1
8       JPOP모음            9
9        JPOP을            1
10      JPOP추천            3
11       J_POP           23
12  KPOP_MUSIC            6
13   KPOP_STAR            1
14    KPOP탐구생활           27
15        POP6            1
16      POPCCM            2
17        POP_            9
18   POP_MUSIC           21
19   POP_Remix            1
20        POP송            1
21     POP전문DJ            3
22       POP차트            2
23      겨울JPOP            1
24     기분좋은POP            1
25      분위기POP            1
26       새벽POP            1
27      신나는POP            3
28       여성POP            1
29       영국POP            1
30       인디POP            1
31    일렉트로닉POP           10
32      잡POP사전           19
33       최신POP            3
34       최애POP            2
35     추억의JPOP            1
36     트로피컬POP            1
37       힐링POP            1

---------------------------------------------------------

index 9: 일렉트로니카

              tags  mapping_cnt
0         감성일렉트로니카            1
1    거닐며듣기좋은일렉트로니카            1
2     듣기부담없는일렉트로니카            1
3       듣기편한일렉트로니카            1
4     모두일렉트로니카의세계로            1
5   산책하며듣기좋은일렉트로니카            1
6         월간일렉트로니카            5
7           일렉트로니카          986
8          일렉트로니카팝           11
9         주간일렉트로니카           18
10        해외일렉트로니카           17

---------------------------------------------------------

index 10: OST

              tags  mapping_cnt
0        80년대영화OST            1
1          BOOSTER            1
2        DisneyOST            4
3         JokerOST            1
4        NOSTALGIA            4
5              OST         2323
6          OST_모음곡            3
7            OST강자            1
8             OST곡            7
9             OST도            1
10        OST로_귀이득            3
11           OST명곡           20
12           OST모음           48
13           OST발견            1
14           OST여왕            1
15           OST음악            1
16          OST중최고            1
17           OST추천            3
18           OST포함            2
19       가사있는영화OST            1
20          검블유OST            1
21         고백부부OST            1
22           국내OST            1
23       너도인간이니OST            1
24          느와르OST            1
25           댄스OST            1
26          도깨비OST           14
27         도깨비OST비            1
28         독립영화OST            1
29           독전OST            1
30       동백꽃필무렵OST            3
31         드라마_OST           20
32          디즈니OST           18
33         라라랜드OST            2
34         라이온킹OST            1
35          라푼젤OST            1
36        래퍼들의_OST            1
37            랩OST            1
38         명불허전OST            3
39           명작OST           20
40           명품OST            1
41          뮤지컬OST           12
42         뮤지컬_OST            1
43     미안하다사랑한다OST            1
44           밀회OST            1
45        바람의검심OST            1
46        바람이분다OST            2
47          발라드OST            2
48       벨벳골드마인OST            1
49         보디가드OST            1
50         봄드라마OST            1
51         비밀의숲OST            1
52          비스트OST            1
53            빅OST            1
54           사극OST           13
55         사의찬미OST            1
56   센과치이로의행방불명OST            1
57           수사OST            1
58     슬기로운감빵생활OST            4
59          아이돌OST            1
60        애니메이션OST           15
61          역대급OST            2
62         연애시대OST            1
63       열여덟의순간OST            1
64           영화OST          178
65         영화음악OST            1
66          올해의OST            1
67        위대한쇼맨OST            1
68         음악영화OST            2
69           인디OST            2
70           인생OST            1
71       일본만화영화OST            1
72         저글러스OST            2
73       지옥의묵시록OST            1
74        질투의화신OST            2
75         청춘시대OST            4
76          초콜릿OST            1
77          통기타OST            2
78         트래블러OST            4
79           팝송OST            1
80       품위있는그녀OST            1
81  하울의_움직이는_성_OST            1
82          하이틴OST            1
83         한국영화OST            4
84         해리포터OST            1
85         해외영화OST            2
86        호텔델루나OST            5
87          화유기OST            1
88     화이트크리스마스OST            2
89       황금빛내인생OST            1

---------------------------------------------------------

index 11: 클래식

               tags  mapping_cnt
0         1일1클래식1기쁨            1
1           1일_1클래식            1
2       1일_1클래식_1기쁨            1
3     2019년베스트인기클래식            1
4    2019년클래식내한아티스트            1
..              ...          ...
380         힐링되는클래식            1
381         힐링첼로클래식            1
382           힐링클래식            9
383        힘들때듣는클래식            1
384         힘을주는클래식            1

[385 rows x 2 columns]

---------------------------------------------------------

index 12: 재즈

            tags  mapping_cnt
0          CCM재즈            1
1         W재즈가된팝            1
2           가요재즈            1
3           가을재즈           11
4         감각적인재즈            1
..           ...          ...
231         현대재즈            3
232       황금재즈파티            1
233  휴식시간에듣는힐링재즈            1
234          흥재즈            1
235         힙합재즈            2

[236 rows x 2 columns]

---------------------------------------------------------

index 13: 뉴에이지

          tags  mapping_cnt
0       감성뉴에이지            1
1       겨울뉴에이지            1
2     귀르가즘뉴에이지            1
3      나른한뉴에이지            7
4         뉴에이지         3493
5        뉴에이지곡            6
6        뉴에이지로            1
7       뉴에이지모음            4
8      뉴에이지발라드            1
9      뉴에이지스테디            1
10     뉴에이지실내악            1
11     뉴에이지연주곡            1
12      뉴에이지음악            8
13     뉴에이지자장가            2
14      뉴에이지최애            1
15     뉴에이지클래식            1
16      뉴에이지탑백            1
17     뉴에이지피아노           49
18  뉴에이지피아노연주곡            3
19      뉴에이지힐링           10
20   드라마뉴에이지음악            1
21   마음에좋은뉴에이지            1
22       밤뉴에이지            1
23    부드러운뉴에이지            6
24      아침뉴에이지            1
25    템포빠른뉴에이지            1
26    피아노_뉴에이지            1
27     피아노뉴에이지            2

---------------------------------------------------------

index 14: J-POP

Empty DataFrame
Columns: [tags, mapping_cnt]
Index: []

---------------------------------------------------------

index 15: 월드뮤직

           tags  mapping_cnt
0          월드뮤직          243
1      월드뮤직아일랜드            1
2  한국뮤지션이만든월드뮤직            1

---------------------------------------------------------

index 16: CCM

               tags  mapping_cnt
0      2014_CCM_총정리            1
1      2016_CCM_총정리            1
2               CCM          618
3           CCMROCK            1
4        CCM같지않은CCM            3
5             CCM결산            3
6             CCM까지            1
7              CCM랩            1
8             CCM맞아            1
9            CCM시상식            2
10            CCM연주            1
11            CCM재즈            1
12           CCM전문가            7
13            CCM추천           15
14            CCM탑백            1
15           POPCCM            2
16         Top50CCM            1
17            가수CCM            1
18            가을CCM            4
19            감성CCM            4
20        공부할때듣는CCM            3
21           국내외CCM            1
22          눈물나는CCM            1
23      등교길에_듣는_CCM            1
24           따뜻한CCM            2
25         랩이들어간CCM            1
26         마음울리는CCM            1
27  멜론_좋아요4000이상CCM            1
28     모르면후회할_해외CCM            2
29        묵상할때듣는CCM            3
30            벚꽃CCM            2
31             봄CCM            3
32       봄에들으면좋은CCM            2
33          비트있는CCM            1
34           빌보드CCM            1
35           상큼한CCM            2
36         스테디셀러CCM            1
37       아침을_여는_CCM            1
38          어쿠스틱CCM            3
39          여자보컬CCM            1
40           연예인CCM            1
41            영어CCM            5
42            외국CCM            2
43       워십할때_좋은CCM            1
44          이스라엘CCM            1
45            인디CCM            1
46        잔잔한연주곡CCM            2
47            재즈CCM            1
48       지칠때_듣는_CCM            1
49        책읽을때듣는CCM            2
50           축복송CCM            1
51      출근길에_듣는_CCM            2
52        카페에서듣는CCM            1
53        큐티할떄듣는CCM            2
54          트랜디한CCM            1
55           트렌디CCM            1
56         파워DJ_CCM           57
57             팝CCM            2
58           팝같은CCM            1
59            해외CCM           52
60            힙합CCM            3

---------------------------------------------------------

index 17: 어린이

        tags  mapping_cnt
0        어린이           60
1   어린이carol            3
2       어린이날            7
3      어린이만화            1
4      어린이음악            4
5       어린이집           78
6   어린이집낮잠노래            4
7    어린이집자장가            2
8      어린이찬양            1
9      어린이캐럴            2
10     어린이캐롤            4
11    어린이클래식           15

---------------------------------------------------------

index 18: 종교음악

           tags  mapping_cnt
0          종교음악           10
1  종교음악베스트합창클래식            1

---------------------------------------------------------

index 19: 국악

       tags  mapping_cnt
0        국악           40
1      국악가요            2
2   국악기가들어간            1
3      국악밴드            1
4     국악연주가            1
5       국악인            1
6      국악탑백            1
7      국악퓨전            1
8   크로스오버국악            2
9      퓨전국악           16
10     퓨젼국악            1

---------------------------------------------------------

index 20: 아이돌

             tags  mapping_cnt
0          1세대아이돌            3
1       2000년대아이돌            1
2      2017년여자아이돌            1
3          2세대아이돌            2
4           국민아이돌            1
5            남아이돌            1
6           남자아이돌          110
7         남자아이돌명곡            5
8          남자아이돌의            5
9     내가생각하는아이돌명곡            1
10          대형아이돌            1
11          데뷔아이돌            1
12        숨은아이돌명곡            2
13     신나는_아이돌_노래            1
14      신나는_아이돌음악            1
15         신나는아이돌            1
16       신나는아이돌댄스            1
17         신인_아이돌            1
18         실력파아이돌            2
19          심야아이돌            2
20            아이돌         1322
21         아이돌1세기            1
22         아이돌OST            1
23         아이돌_명곡            3
24       아이돌_여름노래            1
25        아이돌겨울노래            1
26       아이돌과인디밴드            1
27          아이돌그룹           35
28          아이돌노래           25
29  아이돌노래는_거의_없어요            1
30         아이돌노래돌            1
31        아이돌노래모음            2
32          아이돌댄스            6
33        아이돌댄스노래            2
34          아이돌래퍼            1
35         아이돌메이커           16
36          아이돌명곡           31
37        아이돌명곡모음            1
38         아이돌발라드           16
39          아이돌밴드            1
40          아이돌솔로            3
41         아이돌솔로곡            1
42         아이돌수록곡           28
43       아이돌숨겨진띵곡           14
44       아이돌숨은갬성곡            1
45        아이돌숨은명곡           27
46       아이돌숨은명곡들           14
47      아이돌숨은명곡들돌            2
48        아이돌여름노래            2
49          아이돌원조            1
50          아이돌위주            1
51          아이돌유닛            1
52          아이돌음악           11
53        아이돌의발라드            1
54       아이돌의숨은명곡           83
55      아이돌의숨은명곡돌            4
56        아이돌이넘많타            1
57        아이돌이부른곡            1
58         아이돌일본곡            1
59         아이돌추천곡            1
60          아이돌캐롤            2
61       아이돌크리스마스            1
62          아이돌탄생            1
63        아이돌탐구생활           32
64          아이돌팬송            5
65        아이돌표발라드            1
66          아이돌학교            2
67         아이돌흥하자            1
68  언제나빛나는우주최강아이돌            1
69          여름아이돌            1
70          여성아이돌            1
71           여아이돌            3
72          여자아이돌          117
73       여자아이돌수록곡            2
74          옛날아이돌            1
75          완소아이돌            1
76          원조아이돌            3
77       인기아이돌댄스곡            2
78          일본아이돌            3
79          주간아이돌            2
80          중국아이돌            1
81           탈아이돌            3
82           틴아이돌            1

---------------------------------------------------------

index 21: EDM

               tags  mapping_cnt
0               EDM         1528
1          EDMFloor          161
2           EDM_POP            1
3         EDM_Remix            1
4            EDM_보컬            6
5             EDM노래            3
6          EDM라빈스31            1
7             EDM모음           17
8            EDM모음집            1
9             EDM신곡            1
10             EDM씬            1
11          EDM아티스트            1
12   EDM은_JMC엔터테인먼트            1
13            EDM추천            4
14            EDM파티            1
15          EDM페스티벌            4
16        IndianEDM            1
17          REDMARE            1
18        Vocal_EDM            1
19  WELOVEVOCAELEDM            1
20   WeLoveVocalEDM           10
21      가볍고_경쾌한_EDM            1
22          가사있는EDM            2
23            감성EDM           15
24            겨울EDM            2
25            국내EDM            3
26        나만알고싶은EDM            1
27            댄스EDM            1
28          드라이브EDM            1
29        듣기좋은EDM신곡            1
30            띵곡EDM            1
31           럭셔리EDM            1
32            보컬EDM            7
33          보컬있는EDM            7
34            상큼EDM            2
35           세련된EDM            1
36           시원한EDM            1
37           신나는EDM            4
38          신비로운EDM            2
39            일렉EDM            1
40           주말엔EDM            2
41            최신EDM            2
42          취향저격EDM            1
43        취향저격보컬EDM            1
44      취향저격보컬있는EDM           14
45           클럽EDM곡            2
46          트렌디한EDM            1
47         트렌디한_EDM            1
48           흥나는EDM            2
49            힐링EDM            1

---------------------------------------------------------

index 22: 뮤직테라피

    tags  mapping_cnt
0  뮤직테라피           12

---------------------------------------------------------

index 23: 뮤지컬

       tags  mapping_cnt
0     국외뮤지컬            3
1       뮤지컬           84
2    뮤지컬OST           12
3   뮤지컬_OST            1
4     뮤지컬넘버           14
5     뮤지컬노래            7
6     뮤지컬들의            1
7     뮤지컬배우            1
8     뮤지컬영화            8
9     뮤지컬음악            3
10   뮤지컬풍노래            1
11    초기뮤지컬            1
12  하이스쿨뮤지컬            1
13    해외뮤지컬            2

---------------------------------------------------------

index 24: 크리스마스

            tags  mapping_cnt
0   더매직오브크리스마스타임            1
1       라스트크리스마스            1
2       로맨틱크리스마스            1
3        메리크리스마스           50
4      미리듣는크리스마스            2
5      미리메리크리스마스            9
6        솔로크리스마스            1
7       아이돌크리스마스            1
8        여름크리스마스            1
9     올해도메리크리스마스            1
10     외로운_크리스마스            1
11     재즈보컬크리스마스            1
12      재즈와크리스마스            1
13       재즈크리스마스            1
14         크리스마스          948
15     크리스마스2019            1
16     크리스마스_전야제            1
17       크리스마스가요            5
18       크리스마스감성            1
19  크리스마스겨울추천클래식            1
20        크리스마스곡            1
21       크리스마스노래           41
22     크리스마스노래모음            2
23        크리스마스는            2
24       크리스마스니까            2
25       크리스마스때는            1
26       크리스마스러버            1
27        크리스마스를            1
28       크리스마스매장            1
29     크리스마스매장음악            1
30       크리스마스모음            3
31      크리스마스분위기            5
32       크리스마스선물            1
33        크리스마스송            6
34        크리스마스에            1
35  크리스마스에는눈이올까요            2
36    크리스마스에듣기좋은            1
37       크리스마스연금            1
38       크리스마스영화            1
39     크리스마스영화음악            2
40       크리스마스음악           11
41       크리스마스이브           16
42       크리스마스재즈            6
43       크리스마스찬양            1
44       크리스마스캐럴            7
45       크리스마스캐롤           54
46      크리스마스클래식            1
47       크리스마스테마            1
48       크리스마스파티           14
49        크리스마스팝            2
50       크리스마스팝송            7
51      클래식크리스마스            1
52       혼자크리스마스            1
53      화이트크리스마스           17
54   화이트크리스마스OST            2

---------------------------------------------------------

index 25: 힙합

           tags  mapping_cnt
0      10월마지막힙합            1
1         10월힙합            1
2       1세대한국힙합            3
3         1세대힙합            1
4      2000년대힙합            3
..          ...          ...
260    힙합플레이리스트            5
261      힙합플레이야            2
262  힙합플레이야2018            1
263        힙합홍수            1
264        힙합힙합            1

[265 rows x 2 columns]

---------------------------------------------------------

index 26: Soul

             tags  mapping_cnt
0   BlueEyed_Soul            1
1    ChipmunkSoul            1
2        DeLaSoul            1
3       EarlySoul           15
4      FutureSoul            1
5      HiphopSoul            7
6      KingOfSoul            1
7     MemphisSoul            1
8   MusiqSoulcild            1
9         SoulMin            1
10      SoulTrain            1
11       Soul_Pop            2
12        Soulful           13
13   Soulquarians            1
14   SouthernSoul            1
15    VoiceOfSoul            1
16         최신Soul            1

---------------------------------------------------------

index 27: 메탈

          tags  mapping_cnt
0     2010년대메탈            1
1         LA메탈            2
2         고딕메탈            1
3         국내메탈            1
4        그루브메탈            1
5          누메탈            3
6          뉴메탈           13
7         데스메탈           11
8          락메탈           55
9          랩메탈            8
10        록_메탈            4
11         록메탈          120
12          메탈          327
13        메탈러버            2
14         메탈록            1
15        메탈리카            8
16       메탈발라드            3
17        메탈밴드            3
18        메탈에서            1
19        메탈음악            1
20    메탈이듣고싶을때            1
21        메탈코어            6
22        메탈키즈            1
23     멜로딕데스메탈            1
24    멜로딕스피드메탈            1
25        블랙메탈            6
26       스래시메탈            8
27       스피드메탈            1
28       신나는메탈            1
29       심포닉메탈            3
30        쌍팔메탈            1
31        아침메탈            1
32        영국메탈            1
33      익스트림메탈            2
34     추억의데스메탈            1
35        파워메탈            3
36    프로그레시브메탈            1
37       하드록메탈           21
38  한국헤비메탈의_전설            1
39        헤비메탈           76
40        훵크메탈            1

---------------------------------------------------------

index 28: 블루스

          tags  mapping_cnt
0        고전블루스            2
1        국내블루스            1
2        델타블루스            1
3        룬디블루스            1
4       리듬앤블루스           18
5       백인블루스록            1
6          블루스          109
7        블루스기타            2
8      블루스도짱이야            1
9         블루스락            2
10        블루스록           18
11       블루스명곡            2
12   블루스에서팝록으로            1
13       블루스음악            2
14       블루스인기            1
15      시카고블루스            2
16       신촌블루스            2
17     일렉트릭블루스            2
18    컨템포러리블루스            1
19      컨트리블루스            1
20     포크블루스차트            1
21  폴버터필드블루스밴드            1
22      피아노블루스            1
23       한국블루스            3

---------------------------------------------------------

index 29: 태교

               tags  mapping_cnt
0              발달태교            1
1   우리아이를위한태교자장가클래식            1
2      우리아이를위한태교클래식            3
3      우리아이자장가태교클래식            1
4      우리아이태교자장가클래식            2
5     우리아이태교추천인기클래식            1
6         우리아이태교클래식            3
7   인기휴식힐링스트레스태교클래식            1
8              첼로태교            1
9                태교          277
10            태교_음악            4
11       태교에좋은클래식음악            2
12   태교와우리아이추천힐링클래식            1
13            태교와육아            2
14      태교우리아이추천클래식            1
15             태교음악           75
16        태교추천인기클래식            2
17     태교추천인기피아노클래식            1
18            태교클래식           12
19            태교피아노            1
20             태교할때            1

---------------------------------------------------------

index 30: 컨트리

           tags  mapping_cnt
0       21세기컨트리            1
1   그래미최우수컨트리노래            1
2       멕시코_컨트리            1
3           컨트리           96
4          컨트리락            4
5          컨트리록            6
6         컨트리명곡            1
7         컨트리뮤직            1
8        컨트리블루스            1
9          컨트리송            1
10        컨트리음악            2
11        컨트리재즈            1
12         컨트리팝           12

---------------------------------------------------------

index 31: dance

             tags  mapping_cnt
0       Eurodance            3
1           dance          228
2      indiedance            1
3  shutupanddance            1

---------------------------------------------------------

index 32: 알앤비

         tags  mapping_cnt
0   1990년대알앤비            2
1   2000년대알앤비            1
2    2017년알앤비            1
3     90년대알앤비            1
4       감성알앤비            7
5       고전알앤비            1
6       국내알앤비           55
7       국외알앤비            3
8    드라이브용알앤비            1
9       몽환알앤비            1
10    숨겨진알앤비송           19
11        알앤비         3186
12  알앤비Top100            1
13    알앤비_뽀에버            1
14       알앤비곡            1
15      알앤비맛집            1
16      알앤비명곡            4
17     알앤비발라드            6
18      알앤비보컬            1
19      알앤비소울           52
20     알앤비스테디            1
21      알앤비음악            2
22      알앤비인기            1
23      알앤비차트            1
24      알앤비추천            2
25      알앤비탑백            2
26       알앤비팝           10
27     알앤비핫트랙            1
28     알앤비황금기            1
29      알앤비힙합           29
30   얼터너티브알앤비            3
31      얼터알앤비            3
32      여성알앤비            2
33      외국알앤비            9
34      초기알앤비            1
35      최신알앤비            2
36   컨템포러리알앤비            4
37       팝알앤비            2
38      퓨처알앤비            2
39      퓨쳐알앤비            3
40      피비알앤비            7
41      한국알앤비            2
42      해외알앤비           13
43    해외알앤비소울           93
44   해외알앤비스테디            1
45       힙알앤비            1
46     힙한_알앤비            1
47      힙합알앤비           13

---------------------------------------------------------

index 33: rock

               tags  mapping_cnt
0          Hardrock            5
1   alternativerock            2
2           artrock            2
3       britishrock            2
4      brockhampton            1
5       classicrock            1
6             drock            1
7          glamrock            2
8             krock            3
9        modernrock            1
10        oneokrock            2
11      paintitrock            1
12        punk_rock            1
13      rock_n_roll            3
14      rockandroll            4
15         rockband            3
16    rockisnotdead            1
17     rocktheworld            1
18        rock이그리울때            1
19           rock추천            1
20        rootsrock            2
21      seattlerock            1

---------------------------------------------------------

index 34: 인디

             tags  mapping_cnt
0        2010년대인디            2
1    2월Yasisi인디뮤직            1
2             k인디            1
3        가을과인디의만남            1
4            가을인디            1
..            ...          ...
124        케이인디차트           17
125          한국인디            8
126          해외인디            9
127        해외인디음악            1
128       흔하지않은인디            1

[129 rows x 2 columns]

---------------------------------------------------------

index 35: 성인

          tags  mapping_cnt
0          감성인            1
1         감성인디           39
2           성인            8
3         성인가요           85
4   성인가요Top100            1
5      성인가요스테디            1
6        성인발라드            1
7          성인식            3
8         성인인증            1
9        성인자장가            1
10      슬픈성인가요            1
11        여성인디            2

---------------------------------------------------------

index 36: 팝

         tags  mapping_cnt
0     1970년대팝            2
1     1980년대팝            4
2      1997팝송            1
3     2000년대팝            2
4    2000년대팝송            1
..        ...          ...
404       힐링팝            2
405      힐링팝송            2
406        힙팝            2
407      힙한팝송            1
408      힙합팝송            1

[409 rows x 2 columns]

---------------------------------------------------------

index 37: 일렉트로닉

        tags  mapping_cnt
0      일렉트로닉          350
1   일렉트로닉POP           10
2    일렉트로닉댄스           18
3     일렉트로닉락            1
4    일렉트로닉뮤직            1
5     일렉트로닉스            1
6     일렉트로닉카            1
7     일렉트로닉트            1
8     일렉트로닉팝           70
9   일렉트로닉하우스            2
10   최신일렉트로닉            1
11   팝_일렉트로닉            1

---------------------------------------------------------

index 38: 키즈

           tags  mapping_cnt
0       굿키즈온더블록            1
1       뉴키즈온더블록            1
2           딕키즈            1
3         먼데이키즈            6
4          메탈키즈            1
5          멜론키즈            4
6          스윙키즈            4
7       스윙키즈ost            1
8        스트레이키즈            3
9   스트레이키즈_전곡듣기            1
10           키즈           12
11         키즈동요           57
12         키즈동화           43
13          키즈송            1
14         키즈카페            9
15         키즈캐슬            1
16        키즈클래식           76
17          키즈팝            2
18         힙합키즈            1

---------------------------------------------------------

index 39: 종교

           tags  mapping_cnt
0            종교            1
1          종교음악           10
2  종교음악베스트합창클래식            1

---------------------------------------------------------

index 40: idol

Empty DataFrame
Columns: [tags, mapping_cnt]
Index: []

---------------------------------------------------------

index 41: 소울

             tags  mapping_cnt
0        DJ소울스케이프            2
1           RnB소울           24
2         갓파더오브소울            1
3            고전소울            1
4            남성소울            1
5           네오_소울            1
6            네오소울           36
7            노던소울            2
8            데프소울            1
9            드라소울            1
10          레전드소울            1
11         맵오브더소울            1
12          멤피스소울            2
13          모타운소울            1
14          버블검소울            1
15       브라운아이드소울           12
16         브리티시소울            1
17        블루아이드소울            1
18         블루지_소울            1
19          사운드소울           23
20       사이키델릭_소울            1
21           서던소울            2
22       서울소울페스티벌            1
23             소울         1871
24           소울가득            1
25           소울감성            1
26           소울노트            1
27     소울담은플레이리스트            1
28           소울대부            1
29           소울듀오            1
30           소울디바            1
31          소울라이츠            1
32          소울메이트            2
33          소울발라드            1
34           소울보컬            1
35        소울보컬리스트            1
36           소울스타            1
37         소울아티스트            1
38           소울음악            3
39            소울이            1
40           소울있는            1
41           소울재즈            2
42          소울컴퍼니            8
43         소울쿼리안스            1
44           소울트리            6
45            소울팝            8
46           소울펑크            1
47           소울펑키            1
48          소울페이퍼            1
49            소울풀           16
50         소울풀하우스            5
51           소울풀한            6
52         소울풀한주말            1
53           소울힙합            2
54          시카고소울            1
55  신시사이저와_소울의_만남            1
56          알앤비소울           52
57          알엔비소울            3
58           어반소울            1
59           어번소울            1
60           얼리소울            1
61           영국소울            1
62     우월한_소울_유전자            1
63            잼소울            1
64            지소울            2
65           최신소울            1
66          칩멍크소울            3
67        컨템포러리소울            1
68          킹오브소울            1
69         태그흑인소울            1
70           트랩소울            1
71           펑크소울            1
72           펑키소울            3
73           퓨처소울            2
74        필라델피아소울            2
75           필리소울            8
76      필리소울_리바이벌            1
77          한국적소울            1
78        해외알앤비소울           93
79           흑인소울           15
80           힙합소울           10

---------------------------------------------------------

index 42: 일본

            tags  mapping_cnt
0        7080일본곡            1
1   당신이알아야할일본가수들            1
2          방탄일본어            1
3         아이돌일본곡            1
4             일본          104
5          일본_노래            1
6          일본_애니            1
7           일본가요            3
8           일본감성            6
9            일본곡            2
10         일본곡포함            1
11          일본노래           49
12        일본노래추천            2
13          일본데뷔            1
14         일본드라마            2
15           일본락            3
16        일본만화영화            1
17     일본만화영화OST            1
18          일본매장            1
19         일본발라드            4
20          일본발표            1
21          일본밴드            9
22         일본아이돌            3
23        일본아티스트            1
24          일본애니           11
25       일본애니메이션            5
26    일본애니메이션ost            2
27          일본앨범            4
28           일본어            2
29         일본어공부            1
30         일본어학원            1
31          일본여행            2
32          일본영화            3
33          일본음악           73
34          일본인디            2
35        일본인디밴드            1
36          일본재즈            2
37         일본타이틀            1
38         일본활동곡            1
39         일본히트곡            1
40          일본힙합            1
41        트와이스일본            1

---------------------------------------------------------

---
---
# <span style="color:red">------------7/16ㄱ</span>
---

# 3. 플레이리스트 이름과 장르/태그 비교

## 1) train의 플레이리스트 타이틀 중 장르 이름이 들어간 플레이리스트 찾기

In [26]:
for i in range(0,43):
    print("index %d: " %i,end='')
    print(genre_list['genre'][i]+'\n')
    test=train[train['plylst_title'].str.contains(genre_list['genre'][i])] 
    test=test.reset_index()
    del test['index']
    print(test['plylst_title'])
    print("\n---------------------------------------------------------\n")

index 0: 발라드

0                 발라드로 감성을 발라드림(슬픔주의)
1                       걸그룹 발라드 명곡 모음
2       비오는날 감성 자극 듣기 좋은 어쿠스틱/피아노 발라드
3       "이별 후에 들으면 더 슬픈 감성 발라드 인디 노래"
4       고음병걸린 당신을위한 명품발라드100선　　#여자가수편
                    ...
3547             한 번 쯤 스쳐지나간 멜로디의 발라드
3548                 출근할때 듣는 시원한 롹발라드
3549              좋은발라드 다 모아놓고 한번에 듣기
3550                        ★슬픈감성발라드★
3551                         취향저격 발라드
Name: plylst_title, Length: 3552, dtype: object

---------------------------------------------------------

index 1: 댄스

0                  졸음운전방지※댄스댄스한 플레이리스트♥
1                운동 중에 들으면 힘나는 빠른 댄스곡!!
2       정신차려보면 이미 댄스 무아지경! 2000년대초 댄스음악
3                        po내적댄스wer 팝송모음
4             댄스 팝 틀어놓고 신나게 춤추며 스트레스 풀자
                     ...
1262            무더운 여름을 날려주는 걸그룹 댄스곡^_^
1263                  90년대 인기곡(댄스곡 모음집)
1264                호텔 라운지 느낌 일렉트로 댄스뮤직
1265                    댄스그룹이 부른 감미로운 곡
1266                        힙합과 댄스가 만나면
Name: plylst_title, Length: 1267, dtype: object

---------------------------------------------------------

index 2: 랩

0                         일렉트로니카에서 파생된 랩 음악들
1                              마약 같은 씨잼의 싱잉랩
2                        랩에 0도 모른사람 재즈랑 들어보자
3                         픽시 라이더를 위한 강렬한 랩힙합
4                             ●유명랩퍼 힙합선곡 모음●
                       ...
661    정통 힙합? 어떤건지 모르겠고 그냥 내가 듣기  좋아하는 랩?힙합?
662                        요즘내가듣는랩-! 여심저격!!!
663                          :) 랩퍼들의 조용한 속삭임
664              국힙 1세대 래퍼들의 타이트한 랩 스킬 트랙 모음
665                 힙합 랩 내가 제일 잘나가 한번 들어볼까요?
Name: plylst_title, Length: 666, dtype: object

---------------------------------------------------------

index 3: R&B

0                              포근한 이불속 R&B 468
1                                 국내 감성 R&B 모음
2                                <귀 녹이는 남자R&B>
3                     R&B의 새로운 물결: 얼터너티브 R&B 1
4                        나만 알고 싶은 POP, R&B 리스트
                         ...
1175                      방에서 뒹굴며 답답할 때 R&B 어때
1176                 분위기 깡패인 해외 R&B/Hip-Hop 모음
1177                             여자 R&B (1)[L]
1178    새로운 R&B 힙합 레이블 Real Bros Sound 의 음악들~!
1179                                분위기 있는 R&B
Name: plylst_title, Length: 1180, dtype: object

---------------------------------------------------------

index 4: 인디음악

0                귀가 말랑해지는 인디음악
1           부담없이 듣기 좋은 인디음악.^^
2      달달도 터지고 외로움도 터질것같은 인디음악
3          인디음악을 소화하는 가장 쉬운 방법
4                  잔잔한 인디음악 모음
                ...
608           “ 내가 좋아하는 인디음악 “
609                   아끼는 인디음악
610         오늘같은 날씨와 어울리는 인디음악
611        은은하게 사랑받고 있는 인디음악들.
612            퇴근길 듣는 조용한 인디음악
Name: plylst_title, Length: 613, dtype: object

---------------------------------------------------------

index 5: 록

0                     [록/메탈] Written by 이일우
1                                 올림픽 스밍 목록
2                                 자주듣는 노래목록
3                                  수록곡들의 반란
4                         들을수록 기분좋은 달콤한 멜로디
                       ...
1394                            디제이 본인 재생목록
1395            감각적인 비트, 들을수록 빠져드는 음색의 팝모음.
1396                          디즈니,에니메이션 수록곡
1397    숨은 명곡들이 많은 트와일라잇 시리즈의 수록곡들  MY LIST
1398                들을수록 걸크러쉬 물씬 느껴지는 음악리스트
Name: plylst_title, Length: 1399, dtype: object

---------------------------------------------------------

index 6: 성인가요

0                      성인가요 Top100
1             1960~64년 성인가요 히트곡 모음
2              자꾸만 생각나는 성인가요 명곡 모음
3         인기 성인가요/트로트 베스트(2010-01)
4             신세대가 부르기 좋은 성인가요&노래방
5         고속도로에서 몸이들썩여지는 트로트 성인가요.
6        부모님이 좋아하시는 60 ~ 80년대 성인가요
7                  명곡만 쏙! 성인가요 발라드
8                      1950년대 성인가요
9               낭만으로 가득 찬 성인가요 발라드
10          1960년대 후반부 성인가요 히트곡(2)
11                        성인가요 스테디
12                   추억의 성인가요 1972
13                   추억의 성인가요 1974
14       듣고만 있어도 몸이 들썩이는 성인가요 트로트.
15    추억의 성인가요 베스트  미스터 트롯도 왔구나 왔어
16                   추억의 성인가요 1973
17                   추억의 성인가요 1975
18        인기 성인가요/트로트 베스트(2013-01)
19    젊은층도 듣기좋은 트로트/성인가요 (리메이크 포함)
20            서정적이고 감성적인 성인가요, 발라드
21                   추억의 성인가요 1970
22          어머니/아버지가 좋아하실 성인가요 모음집
23        인기 성인가요/트로트 베스트(2012-12)
24              1930~1949 추억의 성인가요
Name: plylst_title, dtype: object

---------------------------------------------------------

index 7: 포크

0        이 달의 인디·포크 (2018년 06월)
1      오직 기타와 목소리만으로 이루어진 감성 포크
2               포크 싱어 송라이터 리바이벌
3       포크를 잘부르는 인디밴드들의 감성을 모아서
4         마음이 울적한 날, 친근한 포크와 함께
                 ...
247                 영국의 포크를 찾아서
248           느낌 좋은 국내 포크 모음 :)
249               감성 포크 전성시대 47
250           주목할 만한 90년대 포크 명곡
251          인디의 산실, 서브팝의 포크 음악
Name: plylst_title, Length: 252, dtype: object

---------------------------------------------------------

index 8: POP

0                  믿고듣는 하우스 일렉트로니카 POP #2
1                      여름에 어울리는 시원상쾌한 POP
2                산책할 때 들으면 적당히 흥나는 POP_02
3                     드라마 속 분위기에 녹아드는 POP
4                                 멜로디 POP
                      ...
1883                             Soft POP
1884                        J-POP의 명곡들...
1885                   아직도 이 POP을 모르는거야 ?
1886    퇴근 버스에서 편히 들으면서 하루를 마무리하기에 좋은 POP
1887                  FAVORITE POPSONG!!!
Name: plylst_title, Length: 1888, dtype: object

---------------------------------------------------------

index 9: 일렉트로니카

0                      믿고듣는 하우스 일렉트로니카 POP #2
1                  [주간] 일렉트로니카 라디오 5월 넷째주 발매곡
2                          일렉트로니카에서 파생된 랩 음악들
3                        가슴을 전율시키는 일렉트로니카의 세계
4                                      일렉트로니카
                        ...
255               나만의 세계로 이끌어줄 감각적인 일렉트로니카 뮤직
256                  이어폰 끼고 들어보세요(덥스텝,일렉트로니카)
257    한번쯤 들어보면 좋은 재즈힙합,시부야케이,ost,뉴에이지,일렉트로니카
258                 기분전환하고싶을때 들으면 좋은 일렉트로니카 팝
259                 [일렉트로니카] Explore: Dubstep
Name: plylst_title, Length: 260, dtype: object

---------------------------------------------------------

index 10: OST

0                    추억의 명화를 만나는 시간 (영화 OST 모음)
1                            치명적이고도 치정적 사랑의 OST
2                            배경음악에 쓰이는 웅장한OST 3
3          어린시절 잠결에 흘려 보았던 토요명화가 생각나는 영화 OST 보컬
4                             드라마는 끝나도 OST는 남는다
                         ...
1281                   너도 들으러올래? 정말 듣기좋은 OST모음⭐
1282                              추억의 애니메이션 OST
1283                               드라마 OST 플레이어
1284    커플의 러브엑츄얼리 vs 솔로의 나홀로집에 크리스마스 대표 영화 OST
1285                   들으면 설레는 드라마 및 영화 삽입곡&OST
Name: plylst_title, Length: 1286, dtype: object

---------------------------------------------------------

index 11: 클래식

0             거슈윈에서 스타워즈까지, 미국 대표 클래식
1                         퇴근길 클래식 이야기
2          오늘은 왠지 꿀꿀- 나를 웃게하는 클래식 음악들
3       가을의 문턱! 잊고있던 나의 감성을 깨워주는 클래식!
4                       발레 음악 클래식 베스트
                    ...
1881          (클래식)클래식 음악의 전성시대 : 낭만파
1882                      내가 사랑하는 클래식
1883           감상에 젖게하는 아름다운 피아노 클래식.
1884             청량한 파도같은 클래식 피아노 추천곡
1885               내 마음에 착~하고 안기는 클래식
Name: plylst_title, Length: 1886, dtype: object

---------------------------------------------------------

index 12: 재즈

0                퇴근길, 하루를 마무리하는 재즈
1         기분 좋은 하루의 시작, 산뜻한 재즈와 함께
2       재즈 최신곡 모음집 (2015년 08월 03일)
3                             감성재즈
4       재즈 최신곡 모음집 (2015년 09월 22일)
                   ...
2529              크리스마스에는 재즈 & 클래식
2530    재즈 최신곡 모음집 (2015년 08월 17일)
2531                요즘 가장 핫한 재즈모음집
2532        감각적인 멜로디 <재즈와 팝재즈의 세계>
2533              흥겨운 빅밴드의 재즈 사운드!
Name: plylst_title, Length: 2534, dtype: object

---------------------------------------------------------

index 13: 뉴에이지

0                      ★아무때나 듣기좋은 뉴에이지★
1                 가을밤의 풀소리와 함께 듣는 뉴에이지.
2               상쾌한 아침을 여는 싱그러운 뉴에이지 음악
3                                 뉴에이지♡
4       머리를 맑게 해주는 부드러운 뉴에이지 (피아노연주곡모음)
                     ...
1980                  여름밤 너와함께 듣는 뉴에이지.
1981               파란 하늘처럼 맑고 아름다운 뉴에이지
1982             제주도의 바람처럼 따스한 뉴에이지 피아노
1983                 봄을 기다리며 듣는 감성 뉴에이지
1984                  맑은 하늘을 닮은 뉴에이지 음악
Name: plylst_title, Length: 1985, dtype: object

---------------------------------------------------------

index 14: J-POP

0                     J-POP prism♪
1                   듣기 좋은 J-POP 모음
2      J-POP의 매력을 모르는 사람에게 들려주고싶다!
3              쟈니스 없는 J-POP 베스트 12
4          J-POP더위에 지칠땐 댄스와 일렉팝!!!
                  ...
143             '봄'을 노래한 J-POP 디바들
144                  ★★완전좋은J-POP★★
145                   영원한 J-POP 우상
146     00년대 즐겨듣던 J-POP (시부야케이 위주)
147                  J-POP의 명곡들...
Name: plylst_title, Length: 148, dtype: object

---------------------------------------------------------

index 15: 월드뮤직

0                   진한 커피향과 짙은 감성의 월드뮤직
1                  점심 식사시간용 월드뮤직. 주로 라틴
2                     흠.. 월드뮤직이 어렵다구요?!
3                         팝과 록에 담긴 월드뮤직
4                ♠이국적인 여유로운 일상,재즈&월드뮤직♠
5                 비오는날 감성적인 월드뮤직과 함께...
6                 해변 생각나는 이국적인 사운드 월드뮤직
7                 여행을 떠나고싶은 감성! 월드뮤직 모음
8                        ♣내 입맛돋구는 월드뮤직♣
9           언더커버뮤직 51회: 월드뮤직 어디까지 들어봤니?
10                  명곡 팝,월드뮤직,힙합 매장음악모음
11           재즈, 클래식, 월드뮤직 소수와 공유하는 음악들
12                            월드뮤직[올드팝]
13                  매력적인 월드뮤직을 찾아가는 여행~
14                  호미호미카페 월드뮤직1(여성 모음)
15      ARC 음반사가 소개하는 문화와 역사가 뭍어나는 월드뮤직
16      라틴부터 아프리카까지, 월드뮤직 명가 '월드서킷' 리스트
17                내적 자유 분방 감각있는 댄스 월드뮤직
18                      월드뮤직으로 떠나는 남미여행
19      월드뮤직 듣고 세계여행떠나는 기분 느껴보시는건 어떨까요?
20          [월드뮤직] Explore: Latin Dance
21                         월드뮤직(라틴음악위주)
22    월드뮤직의 대모 Cesaria Evora (세자리아 에보라)
23                  우리가 사랑한 유로팝댄스와 월드뮤직
24            넘모 넘모 감성 터졌던 월드뮤직의 두번째 모음
25             오마라 포르투온도와 원드림 월드뮤직페스티벌!
26    [월드뮤직] Explore: Reggae Pop Vol. 1
27                5월의 바람과 햇살에 어울리는 월드뮤직
28              따뜻한 남국을 떠올리며, 재즈 & 월드뮤직
29               호미호미카페 음악선물1 뉴에이지,월드뮤직
30              의외로 감성터지기도 하는 잔잔한 월드뮤직.
31    [월드뮤직] Explore: Reggae Pop Vol. 2
32                         저녁 까페에서 월드뮤직
33                떠나고 싶은 날 듣는 이국적인 월드뮤직
34                월드뮤직! 당신도 쉽게 접할 수 있다!
Name: plylst_title, dtype: object

---------------------------------------------------------

index 16: CCM

0                     마커스워십  CCM 은혜받으세요
1                              내 귀에 CCM
2                  give_thanks_feat.CCM
3      61회 그래미 어워즈 '컨츄리&가스펠/CCM' 부문 후보곡
4                   100번들어도좋은(feat.CCM)
                     ...
306                월요병을 극복하게해줄 은혜로운 CCM
307                        흥이 나는 국내 CCM
308          노래가 아닌 찬양으로, 기도하며 결단하는 CCM
309                    밝고 힘찬 성령 충만한 CCM
310                   신나게 찬양하고 싶을때! CCM
Name: plylst_title, Length: 311, dtype: object

---------------------------------------------------------

index 17: 어린이

0                      동심으로의 여행 : 어린이를 위한 클래식!
1                        어린이날 특집: 아이들과 함께 한 힙합
2                      행복한 크리스마스:)어린이 캐롤 동요 모음
3                           어린이를 위한 감성 뉴에이지 음악
4               아가의 통잠을 위한 오르골 자장가(어린이집 낮잠 노래)
5       자장가 숙면을 위한 태교 감성 클래식 피아노 명곡 어린이 동요 베스트
6                                어린이 동요 만화 주제가
7                '70 '80 순수했던 시절의 어린이 크리스마스 캐롤
8                                  어린이용 귀여운곡들~
9                    엄마들은 편하고 아이들이좋아하는 어린이동요!!
10                     어린이집에서 신나게 들을수 있는 동요모음!
11                            모두들 안녕! 즐거운 어린이집
12                                   어린이미사 성가곡
13                            책 읽으며 듣는 어린이 클래식
14                신난다! 우리 아이들이 좋아하는 어린이 영어 캐럴♪
15                       어린이날 특집, 아이들과 함께 한 힙합
16                           어린이 CCM 아이들에게 축복을
17                         맑고 고운 소리 세계 어린이 합창단
18          어린이의 정서안정과 두뇌발달을 돕는 클래식(키즈,어린이,육아)
19            신나는 인기 동요 베스트 모음 (어린이집, 유치원 필수곡)
20             책 읽으며 듣는 피아노 연주곡 모음 (태교음악,어린이집)
21               자장가 동요 클래식 모음집 리스트! 어린이집 필수템!
22                         어린이를 위한 맑은 감성의 뉴에이지
23                              5월은 푸르구나 어린이음악
24     천사같은 우리 어린이집 아기들의 행복한 낮잠을 위해 들려주고 싶은 노래
25                                     어린이 클래식
26                                  어린이를 위한 가요
27                  어린이집 우리아가들 꿀잠자게하는 자장가 뉴에이지
28               태교음악 모음(태교 클래식,어린이 클래식,낮잠,통잠)
29                          어린이집에서 부르는 1-2월 동요
30                         쉽게 따라 부르는 어린이 예배 찬양
31        어린이 클래식 dj플레이리스트입니다! 어린이정서에 도움많이됩니다~
32                               어린이 성탄절 캐롤 ^^
33                                     어린이날 동요
34                              어린이를 위한 클래식모음집
35                 우리아이가 제일 좋아하는 명품 어린이 감성발달동요
36                             어린이날에 떠나는 클래식여행
37                     어린이 두뇌개발을 위한 클래식 명곡 모음집
38               어린이집 보낸 맘들 모이세요^^잔잔하게 여유 한 곡~
39                          온 가족이 즐겁게! 어린이 뮤지컬
40                        어린이 합창단의 매력이 빛나는 연주들
41                              국내 어린이 합창단 동요!
42                     *어린이날 상큼 발랄한 피아노 음악 모음*
43                             어른이를 위한 어린이날 선곡
44    어린이날 과 어린이들의 달 5월의 신나고 재미나고 감동적인 동요 100선
45                           어린이집 낮잠 노래 (태교음악)
46                                 어린이 파아노 연주곡
47           ■ 어린이집 우리 아이들을 위한 자장가 동요 어린이클래식 ■
Name: plylst_title, dtype: object

---------------------------------------------------------

index 18: 종교음악

0    신앙심을 더 깊게 만든 경건한 종교음악
1     [종교음악] 국내 찬불가 Vol. 1
2         나를 돌아보게 하는 종교음악들
Name: plylst_title, dtype: object

---------------------------------------------------------

index 19: 국악

0                       잠자면서 듣기 좋은 퓨전국악
1                         새해! 퓨전국악과 함께!
2                    우리 소리가 좋아요! (국악동요)
3                             국악 TOP100
4                                국악의 매력
5                            카페다니엘_퓨전국악
6                        낭창낭창, 은은한 퓨전국악
7                   색다른 느낌 국악 크로스오버 최신곡
8                     ◈퓨전국악 그 소리에 심취하다◈
9                             국악 주로 가야금
10                      [국악] 국악의 무한매력❤️
11    빛나는 한국음악 | 퓨전 국악으로 만나는 매력적인 한국음악.
12                 현대와 옛의 만남, 느낌있는 퓨전국악
13                    ★전통찻집에 어울리는 퓨전국악★
14                        국악 (연주곡은 안 됨)
15         ▲ 아련한 달빛여인 [여배우 BGM/퓨전국악 추천]
16                             퓨전국악뉴에이지
17                   고급지고 세련된 크로스오버 국악♬
18            국악에 새로운 상상력을 더하다. 국악x현대음악
19                 듣기 편하고 심금을 울리는 퓨전 국악
20                    국악선율속에 스며든 가을의 정취
21        대중음악부터 국악까지, 천재 뮤지션 정재일의 음악세계
22     '여백'이라 쓰고 '현장감'이라 읽는다. 국악 듣기의 묘미
23                          우리 국악 우리 소리
24          한국의 소리를 찾아서 국악-POP or 크로스오버
25                   편하게 듣는 국악 & 퓨전 국악!
26                             국악 크로스오버
27                       국악 연주자 소리꾼 장사익
28                     우리의 멋~ 국악 동요 모음집
29                  사랑 거즛 말이 [국악 크로스오버]
30             국악 민요 판소리 퓨전 가요 크로스오버 추천
31            아름다운 우리 소리, 꼭 들어봐야 할 퓨전국악
32                           국악과 재즈의 만남
33                    콜라보 발라드 트로트 국악...
34                한국 정서를 담은 국악 사극 느낌 노래
35                 국악풍 우리의 가락을 품은 사극 노래
36           국악의 부활을 꿈꾼다! 판 스틸러: 국악의 역습
37          황금돼지해 2019년은 국악 추천곡으로 신년맞이~
38               전공자가 추천하는 퓨전국악/ 국악입덕하기
39                   우리의 소리를 찾아서 국악 한마당
40                      누구나 듣기 좋은 국악연주곡
41                      국악 연주곡 마음이 편해져요
42                             퓨전국악뉴에이지
43                     장르의 경계를 허무는 퓨전국악
44                           크로스오버 국악음악
45                       편하게 듣기 좋은 퓨전국악
46               누구나 좋아할수 있는 산뜻한 국악과함께~
47         동양의 미를 머금은 노래들 feat.국악 크로스오버
48                         국악,판소리가듣고싶을때
49            마음을 편하게 해주는도 인기 국악 모음 베스트
50                      태교에 좋은 퓨전 국악 연주
51                잠비나이(국악으로 록을 할수 있을까?)
52             한국적인 국악가요, 퓨전국악, 민요풍의 노래
53                                 국악이다
Name: plylst_title, dtype: object

---------------------------------------------------------

index 20: 아이돌

0              ➕아이돌 파헤치기7️⃣ All No.1 GD➕
1                       아이돌 컴백전쟁 퀸덤 원곡모음
2                          아이돌 명곡들을 모아보자
3                     빵빵 떠야하는 아이돌 그룹의 명곡
4                들어도 들어도 좋은 분위기갑 아이돌 명곡들
                      ...
1430                      2018 핫한 아이돌 노래
1431                     아이돌의 감성돋는 히든트랙.
1432             가을이 들어가는 아이돌 노래들 듣고 시펑?
1433    도입부만 들어도 따라 부를 수 있는 아이돌 노래 흥 폭발!
1434            시간이 지나 잊혀지기는 아쉬운 아이돌 명곡들
Name: plylst_title, Length: 1435, dtype: object

---------------------------------------------------------

index 21: EDM

0             EDM 서바이벌 프로그램 '헤드라이너'가 남긴 3가지 논쟁
1                                 듣기좋은 EDM 추천곡
2                               듣고 있으면 신나는 EDM
3                     U.M.F에 온 것 같은 느낌을 주는 EDM
4                                 리듬으로 마라톤 EDM
                        ...
921                          ★club★고르고고른 EDM 5
922             더운 여름 듣기 좋은 트로피칼 분위기의 팝송 & EDM
923                 3년간 엄선한 EDM 클럽하우스 뮤직 top75
924    #기분업! 에너지필~ 사운드굿! 해외 EDM/일렉 선곡#2019년9월#
925             빠른 리스너를 위한 따끈따끈한 최신 인기 EDM 모음!
Name: plylst_title, Length: 926, dtype: object

---------------------------------------------------------

index 22: 뮤직테라피

0            뮤직테라피 스테디
1    요가 명상과 함께하는 뮤직테라피
2     마음을 안정시켜주는 뮤직테라피
3    따듯한 봄날에 즐기는 뮤직테라피
Name: plylst_title, dtype: object

---------------------------------------------------------

index 23: 뮤지컬

0                내가 좋아하는 뮤지컬 영화 노래들~
1      디스코, 힙합이 함께하는 뮤지컬 드라마, 더 겟 다운
2              뮤지컬의 재해석! 또 다른 느낌의 명곡
3           뮤덕이 추천하는 뮤지컬 넘버._. (한국어)
4               디즈니 음악과 뮤지컬영화 음악이 함께
                   ...
129                     매력적인 뮤지컬 넘버들
130                           뮤지컬 뮤직
131               듣기 좋은 뮤지컬 노래 추천 모음
132                   기억해야 할 뮤지컬 넘버들
133     뮤지컬영화.공연.애니 취향존중 곡 선정 (계속업뎃)
Name: plylst_title, Length: 134, dtype: object

---------------------------------------------------------

index 24: 크리스마스

0                         크리스마스 분위기에 흠뻑 취하고 싶을때
1                              크리스마스를 책임질 캐롤 모음
2                                  느낌있는 크리스마스 쏭
3                                        크리스마스9
4                                   미리 메리 크리스마스
                         ...
1379                          나만 알고 싶은 크리스마스 재즈
1380                           크리스마스에는 재즈 & 클래식
1381                                   크리스마스441
1382    커플의 러브엑츄얼리 vs 솔로의 나홀로집에 크리스마스 대표 영화 OST
1383                       크리스마스&겨울에 생각나는 J-pop
Name: plylst_title, Length: 1384, dtype: object

---------------------------------------------------------

index 25: 힙합

0                  트렌디하고 그루브한 힙합/알앤비 MUSIC
1                            서른살 여자가 듣는 힙합
2                       언제들어도 효과 만점인 매력 힙합
3                      스쿨 오브 힙합, 초급 1교시 77
4       2010년대 이후, 국내 힙합신에 새롭게 급부상한 뉴페이스들!
                       ...
3826              나른한 주말 힙합음악과 함께 +아리아나 홀릭
3827           이런 노래가 있었어? 나만 알기 아쉬운 국내 힙합
3828                             섹시 분위기 힙합
3829                           힙합과 댄스가 만나면
3830                Let's Groove 느낌있는 감성힙합
Name: plylst_title, Length: 3831, dtype: object

---------------------------------------------------------

index 26: Soul

0                        첫 소절듣고 바로 꽂히는 Soul RnB
1                      흑인보컬들의 리얼 Black R&B Soul
2                            추천해 주고 싶은 RnB Soul
3                 Greatest Hits Funky Pop ,Soul
4                   크리스마스 데이트를 위한 달달한 Soul/Funk
                         ...
292                         Sweet Soul Music #4
293      진한 멜로디 속 뭉클함, 독보적인 색을 지닌 Pop, R&B/Soul
294    [스테이션 H] DJ소울스케이프가 뽑은 가을을 위한 1980년대 Soul
295                스타표 개별적인 슬픈 노래들(U.Soul의 추천곡)
296                                  R&B : Soul
Name: plylst_title, Length: 297, dtype: object

---------------------------------------------------------

index 27: 메탈

0                       [록/메탈] Written by 이일우
1                      무게가 다르다! 해외 헤비메탈 모음 41
2                              심포닉메탈 넘져아 ㅎㅎㅎㅎ
3         최고의 기타리스트들과 그 밴드들이 선보인 하드록/헤비메탈 명곡선
4      서슬퍼런 분노의 포효! 뉴메탈 이끈 로스 로빈슨의 1990년대 작품들
                        ...
238           멜로디컬한 기타 리프, 깔끔한 훅 날리는 멜로딕 데스메탈
239                        *쿨한 감각의 복고풍 메탈베스트*
240                             데스 헤비 메탈 드라이브
241                       메탈리카 2017 내한공연 셋리스트
242                    혼을 쏙 빼는 빠른 멜로디, 스피드 메탈
Name: plylst_title, Length: 243, dtype: object

---------------------------------------------------------

index 28: 블루스

0      일렉트릭 기타로 블루스를 최초로 연주한 전설적인 선구자 T-Bone Walker
1                                  센치한 밤, 끈적한 블루스 록
2                     [블루스] Introduction: B.B. King
3                                    R&B는 리듬 앤 블루스!
4                                  블루스, 미국 대중음악의 근간
                           ...
125                                         퇴근길 블루스
126                                   브리티시 블루스의 전성기
127                            영원한 블루스의 제왕 B.B King
128                             블루스락, 일렉연주곡, 국내외 명곡
129                               블루스 들으면서 주말을 보내봐용
Name: plylst_title, Length: 130, dtype: object

---------------------------------------------------------

index 29: 태교

0             태교음악 사랑하는우리아이를위해 자장가음악
1                   ❤태교에 좋다는 노래들입니다❤
2           양질의 숙면을 위한 자장가, 태교 음악 모음
3                   남편과 함께 하는 태교 클래식
4         임산부의 태교에 좋은 아름다운 하프 연주곡 모음
                   ...
141                어린이집 낮잠 노래 (태교음악)
142              엄마의 태교와 태아에 좋은 음악모음
143     임산부의 태교에 너무 좋은 사랑스런 오르골 연주곡들
144                    {태교} 휴식을 필요해요
145    태교음악으로 많이 찾아 듣는 뉴에이지 &클래식 연주곡
Name: plylst_title, Length: 146, dtype: object

---------------------------------------------------------

index 30: 컨트리

0     골든 리스트! 편안하고 분위기있는 시간들:)2 (팝, 어쿠스틱, 컨트리)
1                               풀내음 가득한 컨트리 뮤직
2                    부드러움을 흡수한 미국의 컨트리: 1970년대
3                감성적인 노래 혼자 듣기 좋은 노래 컨트리 팝 틴팝!
4                  언제 들어도 좋아! 마음 편하게 즐기는 컨트리 팝
5                               컨트리의 뿌리, 블루그래스
6                         꼭 들어야 할 세련된 21세기 컨트리
7                              기분 전환 컨트리음악 552
8                               이별을 노래한 컨트리/포크
9          [로키산]광활한 자연을 닮은 경쾌한 사운드, 트랜디한 컨트리 팝
10                     드라이브, 운전할 때 듣기 좋은 컨트리 팝
11                         강력추천. 믿고 듣는 컨트리 음악.
12                          한국에서 인기없는? 컨트리음악-1
13                         가장 로맨틱한 21세기 컨트리/포크
14                          기분전환 80~90년대 컨트리 팝
15                    내방을 그랜드캐니언으로 만들어주는 컨트리뮤직
16                                       컨트리트리
17        컨트리 거장의 마지막 예술혼! 조니 캐시와 아메리칸 레코딩 시리즈
18                                시골길에는 컨트리지~!
19                           아름다운 90년대 컨트리 러브송
20                       미국의 자부심 컨트리: 아웃-로 컨트리
21                   초원이 생각나는,  이색적이고 감성적인 컨트리
22                         컨트리 팝과 함께 봄 나들이 가자!
23               컨트리의 고장 Nashville을 느끼고 싶다면!!!
24                         미국의 자부심 컨트리: 2000년대
25         컨트리계 반짝이는 샛별 : 여성 듀오 'Maddie & Tae'
26                    캘리포니아 시골이 연상되는 포크.컨트리POP
27                        고속도로 달리며 듣기 좋은 컨트리송!
28                         기분이 좋아지는 2000년대 컨트리
29                 주말의 나른함을 피하지말고 컨트리 음악으로 즐기자
30                            감미로운 목소리의 포크/컨트리
31                                     캘리 컨트리송
32                             90년대 컨트리 숨은 히트곡
33                                   컨트리..포크..
34                         환상의 하모니로 완성된 컨트리 듀엣
35                          올드펍에서 들으면 좋은 컨트리 록
36          [컨트리] Introduction: Zac Brown Band
37                        세련됨 갖춘 2010년대 컨트리/포크
38                         따사로운 봄햇살 아래 듣는 컨트리팝
39                         마음을 편안하게 해주는 컨트리 음악
40                           사색에 잠기며 듣는 포크/컨트리
41                                   컨트리 딩기링기딩
42                 멕시코의 컨트리 음악, 란체라를 대표하는 뮤지션들
43                             차분한 컨트리 음악의 세계로
44                     낯설지만 알고보면 좋은 음악, 컨트리 뮤직
45                          미국의 자부심 컨트리: 컨트리 록
46            포크/블루스/컨트리 음악으로  한주를 힘차게 시작해볼까요?
47                             컨트리 여신 테일러 스위프트
48                                    컨트리(통기타)
49                                 컨트리 뮤직의 희소식
50                     색다른 느낌! 포크/블루스/컨트리 리메이크
51              아메리칸 어쿠스틱&컨트리 POP (nostalgic)
52                             기분 전환 컨트리음악 552
53                          잔잔하고 상쾌한 미국 컨트리 음악
54                          사랑한다면 낭만의 컨트리 음악처럼
55                          그래미 최우수 컨트리 노래 수상작
56                        편안한 사운드, 컨트리와 포크의 경계
57                대중성 흡수한 1990년대 컨트리 팝 발라드 전성기
58                         나들이 음악으로 제격인 컨트리 팝송
59                         미국의 자부심 컨트리: 1990년대
60     COUNTRY HITS 100 / 한번 듣고나면 친근한 음악 컨트리뮤직
61                        미국의 자부심 컨트리: 21세기 밴드
62                           연인과 함께 듣는 컨트리 러브송
63                            웰컴픽_포크블루스컨트리_잔잔한
64                           가을에 잘 어울리는 감성 컨트리
65                              여름밤에 듣기좋은 컨트리송
66                       오랫만에 찾게되는 컨트리뮤직 & 올드팝
67                           기타소리로 기분 좋게하는 컨트리
68                                       컨트리 송
69                              남성 컨트리 그래미 수상작
70              컨트리 그루비 팝 (country,groovy pop)
71                         ♥ 빌보드 핫 컨트리 노래 모음 ♥
72                    연인과 함께 듣는 달달한 포크/컨트리 러브송
73                          공기 좋고 물 맑은 컨트리 로~드
74      @컨트리 장르를 섞으면 망한다? NO! 이제는 대세라규! (상시추가)
75                                컨트리로 듣는 팝과 록
76          [컨트리] Explore: Alternative Country
77                    커피 마시면서 즐기는 블루스 &컨트리송 :)
78                          한국에서 인기없는? 컨트리음악-2
79              [컨트리] Explore: 90s Country Pop
80                             기분 전환 컨트리음악 552
81                            웰컴픽_포크블루스컨트리_경쾌한
82                           웰컴픽_포크블루스컨트리_어쿠스틱
83                     모든 순간이 담긴 따스한 컨트리 Music
84                                  티버드 컨트리뮤직1
85                        컨트리뮤직 & 올드팝과 함께하는 여행
86                              여성 컨트리 그래미 수상작
Name: plylst_title, dtype: object

---------------------------------------------------------

index 31: dance

0             분위기up!! 신나는 k-dance 모음 d(^_^o)
1                                가요 dance HG
2                       파쇼의 Shall we dance?!
3                    한번 들으면 계속 듣게 되는 [dance]
4                               pop dance HG
5                          신나는 dance Music★★
6                 무더위에는 핫한 danceable 밴드뮤직!!!
7                      #얼반댄스 #urbandancecamp
8                    Crazy funky dance beats
9         Try not to dance challenge!춤 참아봐ㅎㅎ
10    Songs you can dance to 춤 추기 좋은 댄스 곡 모음
11                           shall we dance3
12                          #funky dance mix
13                           Shall we dance2
14              씨클라우드: 트램폴린 & Cloudancer 콘서트
15                                     dance
16              2016년최강clupdance!come back!!
17                                90's dance
18         춤신춤왕#느낌있는힙합#rhythm#dance#playlist
19                       Dance dance dance¿¡
20                           Shall we dance1
21       Sundance Film Festival! 역대 화제작 OST!
22            내가 좋아하는 노래 vol.6 summer dance.
23               더위를 한방에 날려줄 팝댄스 (pop dance)
24          겨울이다:) 겨울에 듣기 좋은 노래 (dance ver.)
25               let's dance~! >국산< 나이트음악의계보
26                  [테마]I just wanna dance~!
27                   let your soul dance !!!
Name: plylst_title, dtype: object

---------------------------------------------------------

index 32: 알앤비

0                       트렌디하고 그루브한 힙합/알앤비 MUSIC
1                             욕 나올정도로 좋은 해외 알앤비
2                        가을 밤과 어울리는 감성보컬 알앤비 모음
3                               커피와 찰떡궁합 알앤비 힙합
4                                   아름다운 알앤비&힙합
                         ...
687                       세련된 그루브! 어반 알앤비 & 힙합!
688             (수시 업뎃) 홍대 빈티지샵 재질의 트렌디한 국힙/알앤비
689                        멜로디가좋고 듣기좋은 알앤비 힙합!!
690                       비오는 밤, 그루브 넘치는 알앤비 팝~
691    1-알앤비 I 감성 터지는 늦은 밤, 혼자만의 생각에 잠기기 좋은 20곡
Name: plylst_title, Length: 692, dtype: object

---------------------------------------------------------

index 33: rock

0                              괜찬은 rock! 예~
1                                 haya rock
2                J rock 뉴비들을 위한 입문하기 좋은 노래들
3                           락힙합 rock hiphop
4                                dear. rock
5          Thanks God It’s rock Festival !!
6               드라이브할때 듣는 파워풀한 베이스의 해외 rock
7                        나의 Modern rock....
8                             My rock metal
9                                 rock&soft
10                         흔하지 않은 사운드의 rock
11              가을취향 저격 K-Modern rock/Indie
12               감각적인, 중독성 400%의 pop n rock
13               지구를 뿌셔뿌셔! 스트레스 받을때 듣는 rock
14                       밤산책을 위한 pop & rock
15                                pop rock1
16                            Favorite rock
17                Modern rock / Alternative
18                                haya rock
19               unknown korean rock ballad
20                                 old rock
21                             Rockrockrock
22                      신나는 락 메탈 rock metal
23                   드라이브 락 drive with rock
24                               rock world
25       70년대 주름잡았던 hard rock & heavy metal
26                              조용한 rock 음악
27                       쿵쿵 흥돋는 rock/hiphop
28                  이런음악 들어봤니? J-rock에 빠져봐!
29                                 야밤에 rock
30                       @japan rock@ 비주얼 락
31                   Rock하니까 청춘! 젊은 rock 명곡
32                                Punk rock
33                    귀와 몸이 반응하는 트렌디 국내rock
34                    소장하고픈 POP1(soul,rock)
35    Rock 주옥같은 곡들 (all different but rock)
36                           독특한 느낌의 j-rock
37                  부담없이 듣기좋은 k-modern rock
38                 ♬ rock'n'roll!!!!!!!!! ♬
39             신해철 rock opera prototype 1 .
40                      Cherish_Modern rock
41                            멜로디가 경쾌한 rock
42                                 『완소rock』
43                구관이 명관이다 hard rock, metal
44                   My favorite rock music
45                            사심 가득 외국 rock
46                               knock rock
47                        여름 장마를 이겨내는 rock!
48                                 krock 선곡
49                           popballad-rock
50                어두운 방 홀로 (새벽 감성) rock.ver
51        pitchfork-trending right now-rock
52     energetic rock music with raw sounds
53     스펙트럼 넓은 팝90선[rock,alternative,old 등]
54                       ╊ DJ Rock K-rock ╉
55                                  최고의rock
56                        모던 rock, acoustic
57                   영국/밴드/솔로/rock/pop/folk
58                                90's rock
59                                  희노애rock
60    Drive ⌗02 Groove / electronica / rock
61                     rock ballad 락발라드의 정석
62                                     rock
63                   매력적인 여성보컬//rock ballad
64                            주제없이 rock&pop
65     홀로 듣는 rock, punk, metal, alternative
66                                 내가  rock
67                      신나는 rock'n'roll 추천!
68            jazzy rockey hippy oldy poppy
Name: plylst_title, dtype: object

---------------------------------------------------------

index 34: 인디

0                지친 하루 끝, 힐링이 필요한 당신에게 추천하는 인디곡
1                        이 달의 인디·포크 (2018년 06월)
2               WEEKLY CHOICE | 지금! 주목해야 할 인디뮤직
3                 "이별 후에 들으면 더 슬픈 감성 발라드 인디 노래"
4                                 귀가 말랑해지는 인디음악
                         ...
2299    인디 음악 좋아해? 일렉트로닉 좋아해? 이것이 인디 일렉트로닉의 정수!
2300                            퇴근길 듣는 조용한 인디음악
2301                  당신의 우울함을 보듬는 2000년대 인디 음악
2302                  활기찬 하루를 위해! 상큼 터지는 인디 뮤직~
2303                               느낌있는 어쿠스틱 인디
Name: plylst_title, Length: 2304, dtype: object

---------------------------------------------------------

index 35: 성인

0                 성인가요 Top100
1      이것이 핱시 감성인가 (Pop ver.)
2        1960~64년 성인가요 히트곡 모음
3         자꾸만 생각나는 성인가요 명곡 모음
4        고요한 가을밤을 물들이는 감성인디모음
                ...
98       외로운 새벽, 별이 되어줄 감성인디들
99               정말좋은 취저 감성인디
100        1930~1949 추억의 성인가요
101            내 취향 가득 감성인디:D
102         가사가 참 좋은 감성인디 20선
Name: plylst_title, Length: 103, dtype: object

---------------------------------------------------------

index 36: 팝

0           DJ. Lime_유럽여행에 어울리는 팝뮤직 Vol.2
1       주말을 기다리며, 마음을 정화하는 노래 (가요부터 팝송까지)
2                   기분이 우울할 땐 힙하고 신나는 팝송!
3                            밤에 듣는 감성적인 팝
4                    빌보드&인기팝송 듣기만 해도 즐거운!
                      ...
5260                            가을 드라이빙 팝
5261               감각적인 멜로디 <재즈와 팝재즈의 세계>
5262    2017년 하마터면 놓칠 뻔 한 감각적인 팝 사운드 대방출!
5263                    취향저격 나만의 팝송 GET!!
5264                               기타선율 팝
Name: plylst_title, Length: 5265, dtype: object

---------------------------------------------------------

index 37: 일렉트로닉

0                             일렉트로닉 한번들어봐 너무좋아
1      코첼라 페스티벌이 강력한 일렉트로닉 음악 페스티벌이 될 수 있는 이유!
2                                     클럽 일렉트로닉
3                  2018년이 기대되는 일렉트로닉 댄스 아티스트들!
4                           1월의 최신 일렉트로닉 음악 소식
                        ...
353                     그루브한 리듬, 느낌있는 일렉트로닉 음악
354                                      일렉트로닉
355                  절대 놓쳐서는 안될 힙하고 트렌디한 일렉트로닉
356          일렉트로닉 뉴에이지 두 거장, 반젤리스 vs. 장-미셸 자르
357    인디 음악 좋아해? 일렉트로닉 좋아해? 이것이 인디 일렉트로닉의 정수!
Name: plylst_title, Length: 358, dtype: object

---------------------------------------------------------

index 38: 키즈

0                         팝씬을 여행하는 쿨키즈를 위한 안내서
1        엄빠랑 아이랑 모조리 취향 저격! 온 가족이 듣는 보사노바 키즈팝♪
2                           [가요]먼데이키즈, 그리고 김민수
3                               그때 그시절 - 먼데이키즈
4                                 엄빠도 즐거운 키즈송♪
5                             함중아와 양키즈,함중아 히트곡
6              굿키즈 온 더 블록(On My Block) S01 OST
7                      벨로주: 몽키즈 단독 콘서트 Thank U
8                                먼데이키즈의 부활을 위해
9                       아이와 함께 듣는 키즈존 뮤직 (영유아)
10             클럽 롸일락: 더 베거스, 더 루져스, 버닝몽키즈 콘서트
11                      미디엄템포 왕조시절 노래 #2 먼데이키즈
12                             먼데이키즈~고인의명복을!!!
13                 『가수바라기 No.61』 먼데이키즈의 베스트 20
14                                 먼데이키즈 노래 추천
15                               ●먼데이키즈BEST앨범●
16                            위키즈 영어 A-K까지 배우자
17          어린이의 정서안정과 두뇌발달을 돕는 클래식(키즈,어린이,육아)
18                                       먼데이키즈
19                             키즈캐슬과 함께 몸에 대해!
20                               영화 "스윙키즈" OST
21                        더 넛츠, 먼데이 키즈 그들에 대하여
22                           스트레이키즈 추천곡!! (8곡)
23                               배드키즈 8월 7일 컴백
24                                    스윙키즈 ost
25                         아이들을 위한 동화같은 키즈 클래식
26                                  먼데이키즈.포스트맨
27                                   먼데이키즈 추천곡
28                       요즘 같은날 듣기좋은 먼데이키즈 노래들
29                           오늘의 추천 가수 - 먼데이키즈
30                           같이 불러야 더 신나는 위키즈!
31                          Yo! 아이의 흥! 신나는 키즈팝
32    ✿키즈 마을✿ 캐릭터 친구들 다 모여라!! (엄마, 아빠 밥 좀먹자!!)
33      스트레이키즈 전곡 듣기 (솔로 및 피처링 포함, 상시 업데이트 예정)
34             상상초월 금지곡 리스트, 1980년대 팝 키즈들의 완소곡
Name: plylst_title, dtype: object

---------------------------------------------------------

index 39: 종교

0           신앙심을 더 깊게 만든 경건한 종교음악
1       (종교)가톨릭음악이 필요하신분들 여기있습니다~
2            [종교음악] 국내 찬불가 Vol. 1
3    나의 종교는 사랑이며 당신은 나의 유일한 교리입니다
4                나를 돌아보게 하는 종교음악들
5      (종교) 불교음악이 필요하신분들 여기로 오세요~
Name: plylst_title, dtype: object

---------------------------------------------------------

index 40: idol

0                     K-POP idol 유닛 총정리
1                    #idol #female #노동요
2    영원한 젊은 여름을 위한; idol’s summer music
3                 내가 좋아하는 노래 Vol.5 idol
4                      #idol #male #노동요
5      (엄선작)handsome하고 cute한 idol muzic
Name: plylst_title, dtype: object

---------------------------------------------------------

index 41: 소울

0          소울 태동기, 대중적으로 다가온 소울 대표 뮤지션
1                        2019년상반기 나의소울
2                      소울과 어쿠스틱이 합쳐지면?
3           ❤(해외)R&B/소울 들으시면서 분위기upup❤
4             나만 알고싶은 독특한 소울을 가진 여성싱어들
                    ...
479    'I SOUL U' 서울 소울 페스티벌 2017 파헤치기
480            소울/얼터너티브 힙합 크루 '소울쿼리안스'
481                  소울가득, 매력적인 음색 (여)
482                 혼술하며 듣는 분위기넘치는 소울팝
483                        흑인소울을 듣고싶다면
Name: plylst_title, Length: 484, dtype: object

---------------------------------------------------------

index 42: 일본

0                               보아일본곡
1                     일본 노래 모음 2000년대
2                     트와이스 일본 타이틀곡 모음
3        지금 이순간 일본여행의 추억과 사랑이 떠오를때...
4                    주목 받는 힙한 일본 인디음악
                    ...
187    인싸들의 잇템 씨티팝! 일본에만 있니? 한국에도 많어!
188                내가 봤던 인생애니 ost(일본)
189            그들만의 개성이 느껴지는 일본의 ROCK
190             폴 매카트니 일본 공연 set list
191               일본어라고 놓치면 후회할 띵곡 모음
Name: plylst_title, Length: 192, dtype: object

---------------------------------------------------------

오히려 플레이리스트 이름으로 한게 예상보다 좋은 결과가 나온 것 같다.

- 키즈 라는 단어는 빼야할듯? (먼데이키즈, 스트레이키즈 가 섞여있음)

---

## 2) train의 플레이리스트 타이틀 중 태그와 일치하는 이름이 있는 플레이리스트 찾기

In [27]:
for i in range(0,50):#2만개인데 10분째 다 안나옴..
    print("index %d: " %i,end='')
    print(tag_cnt['tags'][i]+'\n')
    test=train[train['plylst_title'].str.contains(tag_cnt['tags'][i])] 
    test=test.reset_index()
    del test['index']
    print(test['plylst_title'])
    print("\n---------------------------------------------------------\n")

index 0:

0                                   여행같은 음악
1                                   요즘 너 말야
2                     편하게, 잔잔하게 들을 수 있는 곡.-
3                     크리스마스 분위기에 흠뻑 취하고 싶을때
4                                  추억의 노래 ㅋ
                        ...
115066                        METAL E'SM #2
115067       빠른 리스너를 위한 따끈따끈한 최신 인기 EDM 모음!
115068                #1. 눈물이 앞을 가리는 나의_이야기
115069    퇴근 버스에서 편히 들으면서 하루를 마무리하기에 좋은 POP
115070                  FAVORITE POPSONG!!!
Name: plylst_title, Length: 115071, dtype: object

---------------------------------------------------------

index 1: 00

0                           100번 들어도 기분좋은 가요 !
1                고음병걸린 당신을위한 명품발라드100선　　#여자가수편
2                          4월 12일자 빌보드 Hot 100
3              정신차려보면 이미 댄스 무아지경! 2000년대초 댄스음악
4                            몽환러버의 ‘감성 2:00AM’
                         ...
1903             '00:00~~06:00' 가사를 마음에 담는 시간.
1904                         오늘의 추천곡 10선 - 005
1905                                00년대 좋았던노래
1906                 당신의 우울함을 보듬는 2000년대 인디 음악
1907    Billboard TheHot100 Top20 161105(미국차트)
Name: plylst_title, Length: 1908, dtype: object

---------------------------------------------------------

index 2: 007

0                                         0007
1                  추억속으로 2탄 (2007 ~ 2009년) 중딩때
2                   2002~2007년 공중파 음악방송 역대 1위곡
3                             오래되지 않은 추억담 007#
4                             20070201-오늘같은분위기
5                               2007연인 공감 노래^^
6                                 2007 드라마 삽입곡
7                다시 듣고 싶어져서 듣는 노래(2006-2007)..
8     Official SinglesChart Top20 161007(영국차트)
9                        추억의 2007-2016년 걸그룹 노래
10                         2007 빌보드 차트 1위곡 모음집
11                                2007년 겨울4...
12                             2007. 12. 2. 식상
13                                 2007년 겨울...
14                         알양의 100713 어쩌다만난노래들
15                               2007년 겨울2....
16              그때 그시절 - 보아 Part2. (2005~2007)
17     어디선가 많~이 들어본 상큼 발랄곡! (2007-14년 걸그룹 노래들)
18      Billboard TheHot100 Top20 171007(미국차트)
19                          [시대별차트] 2007년 국내차트
20        2007년 이후 추억의 '아이돌 그룹' 노래 모음! 추억여행하자!
21    이기찬의 미인. 아이비&양파의 대성공.     2007년의 K-Pop50
22                                   2007흥분댄스♬
23                  94년생의 학창시절과 함께한(2007~2012)
24      아무로 나미에 [PLAY TOUR 2007-2008] Set List
25                     2007년도 이후 신나는  k-pop댄스곡
26                대한민국 걸그룹 Top 100 (2007~2015)
27                        2007~2010 장기자랑 단골 노래
28                               백투더 신나는 2007년
29                        007 제임스 본드 테마 음악 스페셜
30               2007 - 2013 한국인이 사랑한 듣기좋은 POP
31                                2007년 겨울3...
32                          [시대별차트] 2007년 해외차트
33          역대 뮤직뱅크 K-Chart 1위곡 모음 (2007-2013)
34             민트페이퍼 10주년, 2007~2016 100곡의 노래들
35                             【꽁꽁】2007 .댄스관람♪
36          'XXL Freshmen'에 선정된 래퍼들(2007~2012)
37                             2007 hot music~
38                                 ★Music 2007
39                       당대 최고 가수들이 부른 007 주제곡
40                               보내기아쉬운...2007
41                                     make007
42                   최고의 가수가 부르는 명곡! '007 주제가'
43       클래식한 스파이 액션의 대표주자, 007 시리즈를 빛낸 역대 주제곡
44                        2007 빌보드 연말 결산 싱글 차트
45                          추억의 노래 (1990-2007)
Name: plylst_title, dtype: object

---------------------------------------------------------

index 3: 007시리즈

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 4: 00s

0                         I LOVE 2000s POP
1                 그때 우리가 열광한 2000s 아이돌 발라드
2        Guitar Riffs of the 2000s Part. 1
3                 Best Rock Songs of 2000s
4                             00s Pop Song
5    Best of The 2000s Billboard Hot Songs
6                       시간여행@시대별차트 00s 151
Name: plylst_title, dtype: object

---------------------------------------------------------

index 5: 00년

0      정신차려보면 이미 댄스 무아지경! 2000년대초 댄스음악
1        한번쯤은 들어본 1960~2000년대의 추천곡 모음집
2                2000년대 익숙한 popsongs !
3                      일본 노래 모음 2000년대
4       2000년대, 빌보드를 뒤흔든 여제의 귀환을 바라며..
                    ...
421          몽글몽글 2000년대 팝과 함께 저녁 드라이브
422             추억속에 담긴 2000년대 팝 명곡 모음
423         00년대 즐겨듣던 J-POP (시부야케이 위주)
424                         00년대 좋았던노래
425          당신의 우울함을 보듬는 2000년대 인디 음악
Name: plylst_title, Length: 426, dtype: object

---------------------------------------------------------

index 6: 00년대

0      정신차려보면 이미 댄스 무아지경! 2000년대초 댄스음악
1        한번쯤은 들어본 1960~2000년대의 추천곡 모음집
2                2000년대 익숙한 popsongs !
3                      일본 노래 모음 2000년대
4       2000년대, 빌보드를 뒤흔든 여제의 귀환을 바라며..
                    ...
351          몽글몽글 2000년대 팝과 함께 저녁 드라이브
352             추억속에 담긴 2000년대 팝 명곡 모음
353         00년대 즐겨듣던 J-POP (시부야케이 위주)
354                         00년대 좋았던노래
355          당신의 우울함을 보듬는 2000년대 인디 음악
Name: plylst_title, Length: 356, dtype: object

---------------------------------------------------------

index 7: 00년대노래

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 8: 00년대발라드

0    90년대2000년대발라드
Name: plylst_title, dtype: object

---------------------------------------------------------

index 9: 00년도노래

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 10: 00년생

0              추억90',2000년생각나는장르불문가요.
1                 00년생 래퍼들 참여 좋은노래 모음
2                      00년생이 듣는 버즈 노래
3    00년생부터 91년생까지의 래퍼, 알앤비 싱어들을 모아봤다
4                         00년생의 음악리스트
Name: plylst_title, dtype: object

---------------------------------------------------------

index 11: 01

0                                2017 Pop Trend
1                 DANCING IN THE MOON-LIGHT .01
2                        이 달의 인디·포크 (2018년 06월)
3                         2011 수능시험화이팅!!! (보컬곡)
4                             2013년 11월에 듣던 노래들
                         ...
3916                         2014Best of CLUB M
3917               2016년 가요계 결산 올해의 앨범 & 올해의 싱글
3918          2017년 하마터면 놓칠 뻔 한 감각적인 팝 사운드 대방출!
3919       사상 최대 규모의 Tomorrowland 2017이 기대되는 이유
3920    #기분업! 에너지필~ 사운드굿! 해외 EDM/일렉 선곡#2019년9월#
Name: plylst_title, Length: 3921, dtype: object

---------------------------------------------------------

index 12: 0129

0    0129
Name: plylst_title, dtype: object

---------------------------------------------------------

index 13: 015B

0        90년대 가요계 최고 인기 그룹 '015B 패밀리'
1                  015B 리더 정석원의 음악 세계
2    작곡가 3탄 : 정석원과 015B, 그리고 그 밖의 명곡들
3              감성에 단비를 뿌린 최고의 밴드 015B
4              [永國] 015B Best of Best
Name: plylst_title, dtype: object

---------------------------------------------------------

index 14: 02

0           ♬사무실 플레이리스트_2020년 2월 5째주
1                  [청각의 미각화] 02. 신 맛
2      2020 Billboard Hot 100 2월 1주차
3           산책할 때 들으면 적당히 흥나는 POP_02
4        클래식 최신곡 모음집 (2015년 10월 02일)
                   ...
570                  2020 달콤한 사랑 고백송
571          ♥오늘의음악 121026♥-로맨틱또는강렬함
572          요즘 많이 듣는 곡 (2020.01.16)
573                    2020 4월 신곡 모음
574                         2020년 1월
Name: plylst_title, Length: 575, dtype: object

---------------------------------------------------------

index 15: 03

0                        2003 빌보드 차트 1위곡 모음집
1                 재즈 최신곡 모음집 (2015년 08월 03일)
2               뉴에이지 최신곡 모음집 (2015년 03월 13일)
3        MBC FM4U 라디오 20.03.12 (목) : WANNABE
4      MBC FM4U 라디오 15.02.03 (화) : You Won`t
                       ...
259              클래식 최신곡 모음집 (2015년 03월 20일)
260                      2030 세대가 남몰래 듣는 트로트
261                                 miru0903
262                  요즘 많이 듣는 곡 (2019.03.28)
263                                  라디오 603
Name: plylst_title, Length: 264, dtype: object

---------------------------------------------------------

index 16: 03월

0         뉴에이지 최신곡 모음집 (2015년 03월 13일)
1          클래식 최신곡 모음집 (2015년 03월 17일)
2           재즈 최신곡 모음집 (2015년 03월 10일)
3           뉴에이지 최신 추천곡 (13년 03월 18일자)
4           재즈 최신곡 모음집 (2015년 03월 18일)
5     [⁂月刊] 일렉트로니카 TOP30 - 17년 03월 발매곡
6           재즈 최신곡 모음집 (2015년 03월 11일)
7                   사과의 쥬크박스 2016년 03월
8           재즈 최신곡 모음집 (2015년 03월 05일)
9          클래식 최신곡 모음집 (2015년 03월 04일)
10         클래식 최신곡 모음집 (2015년 03월 16일)
11          재즈 최신곡 모음집 (2015년 03월 09일)
12         클래식 최신곡 모음집 (2015년 03월 06일)
13         클래식 최신곡 모음집 (2015년 03월 10일)
14        뉴에이지 최신곡 모음집 (2015년 03월 09일)
15             #해외 EDM/일렉 선곡#2020년03월#
16          재즈 최신곡 모음집 (2015년 03월 06일)
17        뉴에이지 최신곡 모음집 (2015년 03월 20일)
18        뉴에이지 최신곡 모음집 (2015년 03월 04일)
19        뉴에이지 최신곡 모음집 (2015년 03월 16일)
20        뉴에이지 최신곡 모음집 (2015년 03월 10일)
21        뉴에이지 최신곡 모음집 (2015년 03월 12일)
22          재즈 최신곡 모음집 (2015년 03월 13일)
23              이 달의 인디·포크 (2018년 03월)
24         클래식 최신곡 모음집 (2015년 03월 18일)
25        뉴에이지 최신곡 모음집 (2015년 03월 06일)
26          재즈 최신곡 모음집 (2015년 03월 12일)
27          재즈 최신곡 모음집 (2015년 03월 20일)
28          뉴에이지 최신 추천곡 (13년 03월 08일자)
29          뉴에이지 최신 추천곡 (13년 03월 05일자)
30        뉴에이지 최신곡 모음집 (2015년 03월 19일)
31         클래식 최신곡 모음집 (2015년 03월 12일)
32         클래식 최신곡 모음집 (2015년 03월 20일)
Name: plylst_title, dtype: object

---------------------------------------------------------

index 17: 04

0                                    라디오 1045
1                                    크리스마스204
2                         UK차트 16.08.04 top20
3         인싸들이 흥얼거리는 요즘 국힙들 (2020.04.14 최종업뎃)
4                  재즈 최신곡 모음집 (2015년 04월 17일)
                        ...
304                    20170416 콜드플레이 내한 셋리스트
305                              걸그룹2004~2006
306                     이른봄, 2017.04.21 14:29
307    Billboard TheHot100 Top20 170415(미국차트)
308                        2015.04.07 오늘들은 노래
Name: plylst_title, Length: 309, dtype: object

---------------------------------------------------------

index 18: 0416

0                                  140416
1    ARIA SinglesChart Top20 170416(호주차트)
2                       0416. 세월호를 추모하며..
3                        아직, 있다. 20140416
4                           Remember 0416
5                          Remember140416
6                  20170416 콜드플레이 내한 셋리스트
Name: plylst_title, dtype: object

---------------------------------------------------------

index 19: 0421

0                                        0421
1    Official SinglesChart Top20 170421(영국차트)
Name: plylst_title, dtype: object

---------------------------------------------------------

index 20: 04_29

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 21: 05

0                                푸른밤의 플레이리스트 05
1                                10:05 너와 나의 시간
2      아무로 나미에 [Space of Hip-Pop 2005] Set List
3          ARIA SinglesChart Top20 160508(호주차트)
4                       요즘 많이 듣는 곡 (2019.05.09)
                         ...
241                    알양의 100517 whatever plus
242                  2세대 아이돌들의 대표곡들-2005년~2010년
243                   추천 ♬ 끄덕이는 노래, 끄덕이는 박자【05】
244                           오늘의 추천곡 10선 - 005
245      Billboard TheHot100 Top20 161105(미국차트)
Name: plylst_title, Length: 246, dtype: object

---------------------------------------------------------

index 22: 0515

0    ARIA SinglesChart Top20 160515(호주차트)
1              170515 [프롬의 낭만잡화점] 20화 선곡표
Name: plylst_title, dtype: object

---------------------------------------------------------

index 23: 06

0             이 달의 인디·포크 (2018년 06월)
1                            프레시업 06
2                         2017.11.06
3        클래식 최신곡 모음집 (2015년 06월 11일)
4        클래식 최신곡 모음집 (2015년 06월 02일)
                   ...
239           드라이브 댄싱 곡 (2017.06.02)
240                     걸그룹2004~2006
241          그 시절 새내기의 봄 (06학번~19학번)
242                   Good bye 2 '06
243    '00:00~~06:00' 가사를 마음에 담는 시간.
Name: plylst_title, Length: 244, dtype: object

---------------------------------------------------------

index 24: 07

0                               1인가구로 산다는 것 507
1                    재즈 최신곡 모음집 (2015년 07월 13일)
2      Official SinglesChart Top20 160729(영국차트)
3           MBC FM4U 라디오 14.11.07 (금) : 그 날의 음악
4                                      라디오 1074
                         ...
252                               카수의 음악이 좋다 07
253                  재즈 최신곡 모음집 (2015년 07월 09일)
254                                        1107
255                제11회 서울재즈페스티벌 #2107서재페 첫날라인업
256                          2015.04.07 오늘들은 노래
Name: plylst_title, Length: 257, dtype: object

---------------------------------------------------------

index 25: 0802

0                 0802
1    알양의 080226 일요일오디오
Name: plylst_title, dtype: object

---------------------------------------------------------

index 26: 08월

0       재즈 최신곡 모음집 (2015년 08월 03일)
1       재즈 최신곡 모음집 (2015년 08월 24일)
2      클래식 최신곡 모음집 (2015년 08월 31일)
3      클래식 최신곡 모음집 (2015년 08월 19일)
4      클래식 최신곡 모음집 (2015년 08월 05일)
5      클래식 최신곡 모음집 (2015년 08월 28일)
6     뉴에이지 최신곡 모음집 (2015년 08월 24일)
7     뉴에이지 최신곡 모음집 (2015년 08월 28일)
8     뉴에이지 최신곡 모음집 (2015년 08월 19일)
9       재즈 최신곡 모음집 (2015년 08월 20일)
10                   [금영2010년 08월]
11      재즈 최신곡 모음집 (2015년 08월 14일)
12      재즈 최신곡 모음집 (2015년 08월 19일)
13      재즈 최신곡 모음집 (2015년 08월 12일)
14     뉴에이지 최신곡 모음집 (2015년 08월 17일
15    뉴에이지 최신곡 모음집 (2015년 08월 26일)
16      재즈 최신곡 모음집 (2015년 08월 28일)
17      재즈 최신곡 모음집 (2015년 08월 10일)
18        ★ 'BJ한나♡' 08월 넷째 주 신청곡 ★
19     클래식 최신곡 모음집 (2015년 08월 24일)
20     클래식 최신곡 모음집 (2015년 08월 17일)
21     클래식 최신곡 모음집 (2015년 08월 06일)
22     클래식 최신곡 모음집 (2015년 08월 20일)
23      재즈 최신곡 모음집 (2015년 08월 11일)
24     클래식 최신곡 모음집 (2015년 08월 07일)
25     클래식 최신곡 모음집 (2015년 08월 18일)
26    뉴에이지 최신곡 모음집 (2015년 08월 05일)
27      재즈 최신곡 모음집 (2015년 08월 25일)
28     클래식 최신곡 모음집 (2015년 08월 14일)
29      재즈 최신곡 모음집 (2015년 08월 31일)
30    뉴에이지 최신곡 모음집 (2015년 08월 06일)
31    뉴에이지 최신곡 모음집 (2015년 08월 31일)
32       뉴에이지 최신 추천곡 -13년 08월 05일자
33      재즈 최신곡 모음집 (2015년 08월 07일)
34    뉴에이지 최신곡 모음집 (2015년 08월 18일)
35    뉴에이지 최신곡 모음집 (2015년 08월 20일)
36    뉴에이지 최신곡 모음집 (2015년 08월 25일)
37     클래식 최신곡 모음집 (2015년 08월 03일)
38      재즈 최신곡 모음집 (2015년 08월 27일)
39     클래식 최신곡 모음집 (2015년 08월 04일)
40    뉴에이지 최신곡 모음집 (2015년 08월 10일)
41    뉴에이지 최신곡 모음집 (2015년 08월 14일)
42     클래식 최신곡 모음집 (2015년 08월 27일)
43    뉴에이지 최신곡 모음집 (2015년 08월 12일)
44    뉴에이지 최신곡 모음집 (2015년 08월 03일)
45      재즈 최신곡 모음집 (2015년 08월 18일)
46     클래식 최신곡 모음집 (2015년 08월 25일)
47    뉴에이지 최신곡 모음집 (2015년 08월 11일)
48        #4. 2019년 08월 특별한 나의_이야기
49      재즈 최신곡 모음집 (2015년 08월 17일)
Name: plylst_title, dtype: object

---------------------------------------------------------

index 27: 0930

0      Billboard TheHot100 Top20 170930(미국차트)
1    Official SinglesChart Top20 160930(영국차트)
Name: plylst_title, dtype: object

---------------------------------------------------------

index 28: 09월

0       재즈 최신곡 모음집 (2015년 09월 22일)
1      클래식 최신곡 모음집 (2015년 09월 16일)
2     뉴에이지 최신곡 모음집 (2015년 09월 18일)
3     뉴에이지 최신곡 모음집 (2015년 09월 08일)
4       재즈 최신곡 모음집 (2015년 09월 10일)
5      클래식 최신곡 모음집 (2014년 09월 26일)
6       재즈 최신곡 모음집 (2015년 09월 16일)
7     뉴에이지 최신곡 모음집 (2014년 09월 26일)
8     뉴에이지 최신곡 모음집 (2014년 09월 24일)
9         ★ 'BJ한나♡' 09월 첫째 주 신청곡 ★
10       뉴에이지 최신 추천곡 -13년 09월 11일자
11      재즈 최신곡 모음집 (2015년 09월 24일)
12     클래식 최신곡 모음집 (2014년 09월 29일)
13     클래식 최신곡 모음집 (2014년 09월 25일)
14    뉴에이지 최신곡 모음집 (2014년 09월 29일)
15        #6. 2019년 09월 특별한 나의_이야기
16    뉴에이지 최신곡 모음집 (2015년 09월 02일)
17     클래식 최신곡 모음집 (2014년 09월 30일)
18      재즈 최신곡 모음집 (2015년 09월 02일)
19     클래식 최신곡 모음집 (2015년 09월 18일)
20      재즈 최신곡 모음집 (2015년 09월 08일)
21    뉴에이지 최신곡 모음집 (2015년 09월 10일)
22      재즈 최신곡 모음집 (2015년 09월 23일)
23      재즈 최신곡 모음집 (2015년 09월 30일)
24     클래식 최신곡 모음집 (2014년 09월 24일)
25       뉴에이지 최신 추천곡 -13년 09월 23일자
26      ★' BJ한나 '♡ 09월 셋째 주 신청곡 모음
27     클래식 최신곡 모음집 (2015년 09월 03일)
28    뉴에이지 최신곡 모음집 (2014년 09월 30일)
29     클래식 최신곡 모음집 (2015년 09월 10일)
30    뉴에이지 최신곡 모음집 (2015년 09월 15일)
31       뉴에이지 최신 추천곡 -13년 09월 30일자
32    뉴에이지 최신곡 모음집 (2015년 09월 25일)
33     클래식 최신곡 모음집 (2015년 09월 25일)
34      재즈 최신곡 모음집 (2015년 09월 15일)
35    뉴에이지 최신곡 모음집 (2015년 09월 03일)
36        2019년 09월 노래방 애창곡 TOP200
37      재즈 최신곡 모음집 (2015년 09월 03일)
38    뉴에이지 최신곡 모음집 (2014년 09월 25일)
39      재즈 최신곡 모음집 (2015년 09월 25일)
40     클래식 최신곡 모음집 (2015년 09월 22일)
41     클래식 최신곡 모음집 (2015년 09월 23일)
42    뉴에이지 최신곡 모음집 (2015년 09월 22일)
Name: plylst_title, dtype: object

---------------------------------------------------------

index 29: 0channel

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 30: 0개국어

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 31: 0살

0                        20살 맞이
1    20살 그시절 그때로..(8090 발라드 모음)
2                    20살이좋아하는노래
3             30살이 고르는 20세기 명곡들
4        20살 성인이 되는 너와 나를 위한 노래
5          30살이 말하는 유년의 Pops...
6            가을 타는 20살 소년의 비밀공간
Name: plylst_title, dtype: object

---------------------------------------------------------

index 32: 0시

0              TOP100시즌 4 2014
1        7080시대가있다면 9020시대도있지!
2                       0시의 재즈
3    ■5시~10시 가로수길 카페뮤직 Vol. 3■
4               8090시대 추억속의 노래
5      밤 10시부터 자정까지 듣는 잔잔한 POP
6              TOP100시즌 3 2013
Name: plylst_title, dtype: object

---------------------------------------------------------

index 33: 1

0                                 2017 Pop Trend
1                  DANCING IN THE MOON-LIGHT .01
2                노래로 의지를 불태우자! "1일1다짐" st용 프로필뮤직
3                      Electronica/lounge Part1.
4                         이 달의 인디·포크 (2018년 06월)
                          ...
10623                                      선아님아1
10624                                      12월1일
10625    #기분업! 에너지필~ 사운드굿! 해외 EDM/일렉 선곡#2019년9월#
10626                      meltedmoon's tastes 1
10627                      #1. 눈물이 앞을 가리는 나의_이야기
Name: plylst_title, Length: 10628, dtype: object

---------------------------------------------------------

index 34: 10

0                           100번 들어도 기분좋은 가요 !
1                고음병걸린 당신을위한 명품발라드100선　　#여자가수편
2                          4월 12일자 빌보드 Hot 100
3                         10월 마지막 주 퇴근 플레이리스트!
4           2010년대 이후, 국내 힙합신에 새롭게 급부상한 뉴페이스들!
                         ...
2193           영국 오피셜 차트 Top 40 (2019년 5월 10일)
2194                                커피101-보사노바
2195                         오늘의 추천곡 10선 - 005
2196       MBC FM4U 라디오 14.10.30 (목) : 그 날의 음악
2197    Billboard TheHot100 Top20 161105(미국차트)
Name: plylst_title, Length: 2198, dtype: object

---------------------------------------------------------

index 35: 100

0                            100번 들어도 기분좋은 가요 !
1                 고음병걸린 당신을위한 명품발라드100선　　#여자가수편
2                           4월 12일자 빌보드 Hot 100
3                   빌보드가 선정한 가장 큰 히트곡: 최고의 100곡
4        빌보드 Hot 100 중 50 Single (2019년 10월 5일)
                         ...
831                                 국내 발라드 100곡
832                        카페 음악 인디팝 감성 충전 100%
833    ❤따스한 봄날이 가기전에 1000곡 다 들을때까지 산책하기~ 도저언~!❤
834      Billboard TheHot100 Top20 170415(미국차트)
835      Billboard TheHot100 Top20 161105(미국차트)
Name: plylst_title, Length: 836, dtype: object

---------------------------------------------------------

index 36: 100000

0    추1000000
Name: plylst_title, dtype: object

---------------------------------------------------------

index 37: 1000곡

0                      기억 저편 해마 까지 털어 모은 1000곡
1                              1000곡이담긴 플레이리스트
2           [외힙] 찐 흑인음악 1000곡 채우기 Vol.1_상시업데이트
3         (2탄) 나 혼자 듣자고 모은 팝송! 1000곡! 모으는 중...
4                                      도전1000곡
5              90년대 태어난 사람들은 다 아는 신나는 노래 1000곡
6                       잔잔하게 듣기 좋은 재즈 1000곡 모음
7                             무작위 선곡한 노래 1000곡
8                  (1탄) 나 혼자 듣자고 모은 팝송! 1000곡!
9     ※집중력최고※ 카페에 앉아 조용한 볼륨, 인디1000곡 들으며 작업하자!
10                                    1000곡 텟트
11    ❤따스한 봄날이 가기전에 1000곡 다 들을때까지 산책하기~ 도저언~!❤
Name: plylst_title, dtype: object

---------------------------------------------------------

index 38: 1000만관객동원

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 39: 1000칼로리

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 40: 100곡

0                빌보드가 선정한 가장 큰 히트곡: 최고의 100곡
1                   명품 남녀 듀엣곡 엄선!! - 100곡 모음
2                             마음에 드는 노래 100곡
3                     내가 들었던 백가지 곡식 아닌 100곡.
4      Pick! 믿고 듣는 찬양 100곡 (매일매일 하나님과 동행하세요)
                       ...
117                      더 유명해졌으면 하는 팝송 100곡
118                           my 선곡 락-메탈100곡
119                    나만의 발라드 리스트 100곡 입니다.
120             #20 몇번을 들어도 좋기만 한 노래모음(100곡)
121                              국내 발라드 100곡
Name: plylst_title, Length: 122, dtype: object

---------------------------------------------------------

index 41: 100번

0                           100번 들어도 기분좋은 가요 !
1                          100번들어도좋은(feat.CCM)
2                     시와 찬미 9 1~100번 찬양 ccm 모음
3                            내가 100번 이상 들은 노래들
4                      100번 넘게 들어도 좋은 100곡 (2)
5                  100번 그이상 재생한 attractive곡 모음
6                     100번 넘게 들을 수 있은 중독성 쩌는 팝
7                   100번들어도 질리지 않는 best POPs!!
8                            멜로디때매 100번듣게되는 노래
9       소란 (SORAN) 고영배의 '정말 꽂혀서 100번 넘게 들은 노래'
10    자꾸만 듣고싶어 100번 이상 재생한 attractive곡모음 Part2
11                         100번 넘게 들어도 좋은 100곡
12                         100번을 들어도 좋은 감성발라드.
13                           100번 들어도 안질리는 인생곡
14                          100번 들어도 기분좋은 가요 !
15    Best Playlist - 중독성 쩔어서 100번도 더 듣게되는 곡들❤
16                              100번 이상 들은 노래들
Name: plylst_title, dtype: object

---------------------------------------------------------

index 42: 100선

0                고음병걸린 당신을위한 명품발라드100선　　#여자가수편
1                고음병걸린 당신을위한 명품발라드100선　　#남자가수편
2               당신의 귀를 황홀하게 할 감각적인 일렉 음악 100선!
3                             겨울에 듣기좋은 팝송 100선
4                   젠틀이가 추천하는 POP TOP100선별 추천곡
5                               한국일렉 BEST 100선
6              멜론에서 만나는 2017 전반기 전자음악 엑기스 100선
7                   대중음악 SOUND선정-한국 인디 명곡 100선
8                       오랫동안 사랑받는 라이브 명곡 100선!
9                                내맘대로뮤지컬노래100선
10                         Jazz 명반 100선 Part.5
11                 패션/매장에서 틀어보자 패션피플 변신가능 100선
12                    패션/매장에서 틀어보자 모델워킹가능 100선
13                         Jazz 명반 100선 Part.3
14                     폭염 날려버릴듯 파워풀한 여름노래 100선
15                               신개념 국내힙합 100선
16                     당신이 기억해야할 한국 인디 명곡 100선
17                      내 아이를 위한 말랑한 태교음악 100선
18             고르고 골라 또 고른 주옥같은 힙합명곡 100선 (외국)
19                모든 사람들이 알만한 익숙한 노래 모음 100선!!
20                           좋아하는 드라마 OST 100선
21                                  국외힙 100선 二
22                         Jazz 명반 100선 Part.2
23                              2018 인디명곡 100선
24                                    국외힙 100선
25                         Jazz 명반 100선 Part.4
26                           1970년대 POP음악 100선
27                       새로운 시작을 할때 듣는 노래 100선
28                                    한국힙합100선
29                           해외 R&B 100선 Ver.5
30                     ●미국에서 나오는 힙한 트랙리스트 100선
31    어린이날 과 어린이들의 달 5월의 신나고 재미나고 감동적인 동요 100선
Name: plylst_title, dtype: object

---------------------------------------------------------

index 43: 100억짜리피쳐링

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 44: 100위

0       해외 일렉트로닉 뮤직 탑100위중 베스트
1        코인 노래방차트 1~100위(상시업뎃)
2    좋은 음악이지만 차트100위 안에는 없는 음악
3        j. pop 탑100위중 베스트 콜랙션
4            발라드 탑100위중 베스트 모음
Name: plylst_title, dtype: object

---------------------------------------------------------

index 45: 100주년

0           재즈 피아니스트 Nat King Cole: 탄생 100주년
1         재즈의 예언자 Herbie Nichols 100주년 Pt. 2
2     펩톤 wish list (2017.12.17.이화여고100주년기념관)
3    삼일절 100주년을 맞아 한일 관계, 아픈 우리나라 역사를 말하는 노래
4         재즈의 예언자 Herbie Nichols 100주년 Pt. 1
5           '진정한 블루노트 아티스트' Ike Quebec 100주년
Name: plylst_title, dtype: object

---------------------------------------------------------

index 46: 101

0                                   20131101 팝
1         ARIA SinglesChart Top20 161016(호주차트)
2                             90년생을 위한 노래 101선
3                                  프로듀스101 모음!
4                          프로듀스X101 인기 경연곡 모음!
5                           사탕보다 달콤한 음악바구니 101
6                     ♥오늘의음악 121017♥ -  발라드&댄스
7                     프로듀스101 시즌2 포지션 평가곡 다시듣기
8                   프로듀스 101 시즌2 그룹배틀평가곡 다시 듣기
9               요즘 어떻게 지내? 프로듀스101 1편 I.O.I 근황
10                         프로듀스X101 포지션평가 곡 모음
11                                      호란1018
12                  프로듀스101부터 I.O.I까지,관련 곡 모음집
13                      프로듀스101 시즌2 연습생들이 낸 곡들
14                                    라디오 1011
15                                 소녀감성 101퍼센트
16                                  프로듀스 X 101
17     9회말 2아웃, 1픽으로 장만하는 데뷔의 발판! 프로듀스 101 시즌2
18                 귀마저 달달함을 원하는 봄에 딱 어울리는 101곡
19                        25121419300101150045
20                                 20131101 한국
21                         프로듀스101 시즌2 포지션평가 곡
22        ARIA SinglesChart Top20 171015(호주차트)
23                                    라디오 1013
24                                151101 드림 콘티
25                               PRODUCE X 101
26                        프로듀스 101 시즌 2 경연곡 모음
27    Official SinglesChart Top20 161014(영국차트)
28                                       101번째
29                                    크리스마스101
30                          동성로 101 3기 공연곡 모음!
31                          프로듀스101 시즌 2 회상곡❤️
32        스핀 매거진 선정 The 101 Best Songs of 2015
33                      ♥오늘의음악 121013♥ - 한 중 일
34                       ♥오늘의음악 121011♥ - 드라이브
35                              101곡의 감성 까페 음악
36                              커피101 - 올드팝(2)
37                            20131101 좋아하는 노래
38                        프로듀스 101 시즌 2 컨셉평가 곡
39                             더 믹스 나인틴 101 학교
40                       [프로듀스101시즌2] 포지션 평가 곡
41                                    라디오 1012
42                                    라디오 1017
43                               커피101-팝발라드(2)
44                        PRODUCE101시즌2 - 포지션3
45                               프로듀스 101 시즌 2
46                          181101 엑소엘 화력총공리스트
47             추억의 프듀 노래 모음집(프로듀스101~프로듀스X101)
48                            프로듀스101이 탄생시킨 가수
49                                    라디오 1010
50                      프로듀스101 콘셉트평가 경연곡 다시듣기
51                            [유희열의 스케치북] 101회
52                        PRODUCE 101 season 2
53                                    라디오 1101
54                     '프로듀스 101 시즌 2', 그후 일 년
55                                        1010
56                      프로듀스101 시즌1~시즌4까지 몰아듣기
57                             PRODUCE101 시즌2
58                           국민 아이돌 PRODUCE101
59                              101%의 아름다운 고백송
60            '좋아요 1천 미만' '숨겨진 보석' 명곡 101곡 모음!
61                            자몽의플레이리스트_181011
62                    푸른밤 종현입니다(141012~141019)
63      101명의 소년, 소녀들의 꿈을 향한 레이스! 프로듀스 101 띵곡들
64                                     라디오 101
65                                    라디오 1018
66                       프로듀스 101 Concept 평가 곡
67                                     101~200
68                 Produce 101의 소녀들. 안녕, 아이오아이
69                              커피101 - 올드팝(1)
70                    [프로듀스101 최대수혜자] 작곡가 라이언전
71                     비판적으로 생각하며 보자! 프로듀스 101
72                              프로듀스X101 하이라이트
73       초대형 걸그룹 프로듀스101 - PICK ME가 좋다면 일렉트로!!
74       듣는 순간 세상의 주인공은 나! 소름 돋는 일렉팝 101곡 모음~~
75                              커피101 - 발라드(1)
76                프로듀스101 시즌 2에서 한번이라도 나온 음악들❤
77      Billboard TheHot100 Top20 171014(미국차트)
78                              ♥오늘의음악 121012♥
79                            국가대표 보컬리스트 101곡!
80                             프로듀스101시즌2 노래모음
81                                  Radio 1017
82                                 프로듀스101 시즌2
83                                    라디오 1015
84      워너원 데뷔카운트다운 D-10 프로듀스101 노래 한번씩 들어보아요~
85                          사탕보다 달콤한 음악바구니 101
86                                  커피101-보사노바
Name: plylst_title, dtype: object

---------------------------------------------------------

index 47: 10cm

0       라쿤 페스티벌, 10cm/볼빨간사춘기/권진아/소란/용준형 최고야 ♡
1                           나만의 BEST 3 : 10cm
2        내가 좋아하는 뮤지션 #1 - 음악으로 행복한 [10cm 권정열]
3                      DJ 미러볼 1회 : 권정열 (10cm)
4                            DJ 미러볼 19회: 10cm
5                            나만의 BEST 3: 10cm
6                            오늘의 추천 가수 - 10cm
7                    10cm 단독 콘서트 1+2+3+4 셋리스트
8                         #인디 #십란한밤 #10cm #소란
9                     [인디] Introduction: 10cm
10    데이브레이크, 멜로망스, 선우정아, 10cm 역대급! 경주 그린플러그드
11          Rebirth, 그래도 여전히 두 남자의 간격은 '10cm'
12                          나만의 BEST 3 : 10cm
13                 『가수바라기 No.57』 10cm의 베스트 20
14                                 10cm 그 감성들
15                             내가 듣는 10cm 엄선본
16                   10cm 소극장 콘서트 셋리스트 미리듣기 ♥
17                                  10cm INST
Name: plylst_title, dtype: object

---------------------------------------------------------

index 48: 10곡

0                                 안예은 BEST 10곡
1                      1)슬픈 이별, R&B/발라드 노래 10곡
2                             여름밤 듣기 좋은 음악 10곡
3                             지금 듣기 좋은 발라드 10곡
4                                 요즘 많이 듣는 10곡
5     용기,고민,이별의 감정을 이야기처럼 풀어내는 10곡(상세정보 꼭 확인!)
6                    새벽녘 우리의 마음을 어루만져주는 음악 10곡
7                                딱 10곡만 들어주세요.
8             밤에 조용히 들을만한  목소리가 좋은 여성보컬 노래 10곡
9                                 롱디커플을 위한 10곡
10                            STAY라는 제목의 명곡10곡
11       샤워할때 들으면 수도세 폭발해서 엄마한태 등짝맞는 힙한 노래 10곡
12                                클럽 일렉 음악 10곡
13                           내 마음을 읽어주는 노래 10곡
14                    매장용 10곡! 골라듣자 (국내5,해외5곡)
15                           ccm베스트10곡을 모아봤어요.
16                               제일 신나는 국힙 10곡
17               (vol.1~7 총집합) 시끄럽지 않은 일렉 210곡
18                    감성힙합? 힐링타임? 힙합 10곡 들어가요~
19                                외국영화 ost 10곡
20                    즐거운 일요일^^[최신곡,추천곡 모음10곡]
21                              윤하 베스트10곡 순서대로
22                             <힙합10곡>유니크한 스타일
23                           신해철 그가 사랑한 명곡 10곡
24                         늦은 밤 드라이브에 어울리는 10곡
25    이 집 노래 맛집이네! 매일 10곡씩 여러분의 플레이리스트를 채워드립니다
26                         듣자마자 신나버리는 EDM 10곡!
27                      지친 날, 우리를 위로해주는 음악 10곡
28                 가사에 취해 들으면 더 슬퍼지는 발라드 10곡..
29                   (눈물 주의)미치도록 슬픈 일본 발라드 10곡
30                     독서할 때 듣기 좋은 노래 엑기스 10곡!
31                           잠자기 전에 듣는 r&b 10곡
32                      요즘 가장 핫해서 꼭 들어야 하는 10곡
33                        딱 10곡만, 장르불문 임팩트 굿!!
34                     10곡도 채 못듣고 잠이든다는 마법의 노래
35              DJ백곰돌이// 그리움에 빠지는 사랑 추억 여행 10곡
36                 가사 묵상하기 좋은 위로되는 CCM 10곡 엄선!
37                           외힙띵곡!!10곡만 플레이 고고
38                      국내 :: 매장음악 딱 10곡 :: 카페
39                               주관적인 기리보이 10곡
40                          추천노래 10곡 [강력추천] ^^
41                   잔잔하고 몽환적인 분위기를 느끼고싶다면 10곡
42                                딱 10곡이면 충분한듯
43                   자꾸만 귀에 맴도는 마법같은 노래 10곡 !!
44                  가을밤, 우리의 마음을 달래줄 감성 음악 10곡
45                        더도 말고 덜도 말고 딱 이 10곡만
46                       힘들고 지칠때 위로가 되는 노래 10곡
47                                  장윤정 인기곡10곡
48                        혼자있을때 들으면 좋은 노래 10곡!
Name: plylst_title, dtype: object

---------------------------------------------------------

index 49: 10년간의_기록

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

#### 너무 많아서 끊었다!!
- 그리고 가수이름같은 경우 겹치는게 많음 -> 이건 태그로 안하고 가수 이름과 플레이리스트 대조하는게 좋을듯하다
- 태그중에 쓸데없는것도 많음 
    - 7777 이런거...(뭔지모름)
- 의도가 다른것도 있음
    - 101 -> 프로듀스 101, 오늘의 음악 161101, 유희열의 스케치북 101회 이런것도 다 들어감
    
#### 이건 안쓰는게 나을 것 같다.

## 3) train의 플레이리스트 타이틀 중 가수 이름과 일치하는 이름이 있는 플레이리스트 찾기

---

In [28]:
#아티스트 id별 이름 매칭

In [29]:
#담을 곳 선언
artist_list=pd.DataFrame()

#artist id와 name
#song_meta['artist_id_basket']
#song_meta['artist_name_basket']

# 첫 번째것만 담겠다. 왜냐하면 나중에 딕셔너리는 정렬이 안됨ㅠ
artist_list['id']=song_meta['artist_id_basket'].str[0] #list 첫번째 항목만 넣는다
artist_list['name']=song_meta['artist_name_basket'].str[0] #list 첫번째 항목만 넣는다

In [30]:
artist_list

            id             name
0         2727  Various Artists
1        29966   Murray Perahia
2         3361    Peter Gabriel
3       838543           Matoma
4       560160         Jude Law
...        ...              ...
707984  166499        Fela Kuti
707985   11837     Cyndi Lauper
707986     437              윤종신
707987  729868     Nature Piano
707988     895              김경호

[707989 rows x 2 columns]

In [31]:
# artist id중 맨 앞에 있는 이름으로 정렬
artist_list=artist_list.sort_values(by=['id'],axis=0)
artist_list

             id         name
305875        1          나훈아
169859        1          나훈아
321108        1          나훈아
48843         1          나훈아
170749        1          나훈아
...         ...          ...
512947  2865590           라포
334050  2865591           펭수
442813  2866236  Midas Touch
318592  2866406    Moon Arch
160844  2866426     Patricia

[707989 rows x 2 columns]

In [32]:
artist_list=artist_list.drop_duplicates('id', keep="first")

#index reset하겠음(문자 단위 검색 목적이므로)
artist_list=artist_list.reset_index()
del artist_list['index']

artist_list

             id         name
0             1          나훈아
1             2          남화용
2             5          유현상
3             6          김학래
4             7          정태춘
...         ...          ...
103573  2865590           라포
103574  2865591           펭수
103575  2866236  Midas Touch
103576  2866406    Moon Arch
103577  2866426     Patricia

[103578 rows x 2 columns]

- id 3이나 4가 사라진게아니라 sont_meta data 내에는 없다..

In [33]:
for i in range(0,100):#10만개는 너무많은듯.. 일단 일부만 뽑아봄
    print("index %d: " %i,end='')
    print(artist_list['name'][i]+'\n')
    test=train[train['plylst_title'].str.contains(artist_list['name'][i])] 
    test=test.reset_index()
    del test['index']
    print(test['plylst_title'])
    print("\n---------------------------------------------------------\n")

index 0: 나훈아

0          나훈아 히트곡 모음
1    영원한 트로트의 황제! 나훈아
2      트로트 꺽기의 황제 나훈아
Name: plylst_title, dtype: object

---------------------------------------------------------

index 1: 남화용

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 2: 유현상

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 3: 김학래

0    불후의 명곡 전설을 노래하다...YB&김학래&김광석 (편)
Name: plylst_title, dtype: object

---------------------------------------------------------

index 4: 정태춘

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 5: 김태곤

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 6: 이치현

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 7: 임창제

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 8: 이진관

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 9: 함중아

0    함중아와 양키즈,함중아 히트곡
Name: plylst_title, dtype: object

---------------------------------------------------------

index 10: 이주원

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 11: 김종서

0    김종서 [헤비메탈 / 하드코어 Best 10]
1             김종서 [고음 Best 10]
2              김종서 [명곡 Best 5]
3      김종서 [특이함 / 독특함 Best 10]
4         김종서 [김종서 음악 Best 15]
5      김종서 [락발라드 / 어두움 Best 5]
Name: plylst_title, dtype: object

---------------------------------------------------------

index 12: 이정선

0           이정선 기타교실 1
1           이정선 기타교실 7
2    포크의 추억, 이정선과 해바라기
3           이정선 기타교실 3
4           이정선 기타교실 5
5           이정선 기타교실 6
Name: plylst_title, dtype: object

---------------------------------------------------------

index 13: 김원준

0    아이돌의 조상 김원준 파헤치기~!
Name: plylst_title, dtype: object

---------------------------------------------------------

index 14: 설운도

0    송대관 태진아 설운도 현철 히트곡 모음
1           설운도 누이 모음 ~~~~
Name: plylst_title, dtype: object

---------------------------------------------------------

index 15: 조용필

0                                조용필
1             한국 가요계의 가왕, 조용필의 필모그래피
2     불후의 명곡 전설을 노래하다..조용필 구창모(송골매)편
3                           조용필  베스트
4          국민가수! 패티김 50주년 과 조용필 40주년
5                         영원한 가왕 조용필
6                        조용필 조용필쥬뇨어응
7                조용필 슈퍼소닉 2013 세트리스트
8                   살아있는 레전드, 가왕 조용필
9      80년대 남자가왕들 조용필.전영록.이용.최성수.김범룡
10                 조용필 전국투어 콘서트 2013
11                 황제 조용필 여왕 이선희 컬렉션
Name: plylst_title, dtype: object

---------------------------------------------------------

index 16: 김용만

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 17: 이용

0    2019년 멜론 연간 누적 이용자 순위 TOP 100 (가이섬.com)
1              2020년 멜론 일간 최고 이용자수 노래 TOP 30
2                                어린이용 귀여운곡들~
3                           이용신 성우님 언제나 함께해요
4                      봄나들이용 음악~마음만은 이미 봄이쟈나
5              80년대 남자가왕들 조용필.전영록.이용.최성수.김범룡
6                             봄맞이용 상큼한 팝송 모음
7                     레전드 작곡가 - 강렬한 비트 이용민 편
Name: plylst_title, dtype: object

---------------------------------------------------------

index 18: 노영심

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 19: 전영록

0    불후의 명곡 전설을 노래하다...남진 이미자 최진희 전영록(작사, 작곡)
1              가요계 원조 아이돌, 전영록이 작곡한 수 많은 히트곡들
2                                   전영록하면  젊음
3               80년대 남자가왕들 조용필.전영록.이용.최성수.김범룡
Name: plylst_title, dtype: object

---------------------------------------------------------

index 20: 송시현

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 21: 신승훈

0                                         신승훈
1                   『가수바라기 No.89』 신승훈의 베스트 20
2                                      신승훈수호성
3                                더 신승훈 쇼 2013
4                    내가꼽은노래~!(부활,이승철,신승훈,t,등)
5                             신승훈 김건모 그리고 이승환
6                             발라드 황제, 신승훈의 명곡
7    김장훈 YB 김광석 신승훈 부활 이승철 지오디 핑클 라이브 앨범 모음 등
8            천만장 가수 2탄 : 발라드의 황제, 신승훈의 발라드 모음
Name: plylst_title, dtype: object

---------------------------------------------------------

index 22: 이승환

0     30/40 발라드 (6가왕-이승환/김동률/박효신/박정현/이소라/박기영)
1                                     공장장 이승환
2                                  히든싱어3 이승환편
3                           이승환 2020빠데이를 기다리며
4                        이승환의 '차카게 살자' 콘서트 후기
5                             신승훈 김건모 그리고 이승환
6              V-Hall: 이승환의 마니아 전용 돌발콘서트 WET!
7              히든싱어 시즌3 이승환편 미션곡&삽입곡 순서대로 모음!
8             이승환 LAST PPADAY '괴물'(2019.6.15)
9                       공연의 신! 이승환 명곡 TOP 30!
10                   공연특집 : 드림팩토리 공장장 이승환 215
Name: plylst_title, dtype: object

---------------------------------------------------------

index 23: 김승덕

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 24: 김수희

0    성인 가요에 남도 창법을 덧입혀 성공한 김수희
Name: plylst_title, dtype: object

---------------------------------------------------------

index 25: 김수철

0    불후의 명곡 전설을 노래하다(200회 특집 김수철 1/2편 원곡
Name: plylst_title, dtype: object

---------------------------------------------------------

index 26: 강수지

0    [발라드] Introduction: 강수지
Name: plylst_title, dtype: object

---------------------------------------------------------

index 27: 윤수일

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 28: 심수봉

0    1세대 여자 싱어송라이터 심수봉 원곡과 리메이크곡
1         올 겨울 분위기 있는 심수봉 음악과 함께
Name: plylst_title, dtype: object

---------------------------------------------------------

index 29: 신성우

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 30: 최성수

0    80년대 남자가왕들 조용필.전영록.이용.최성수.김범룡
Name: plylst_title, dtype: object

---------------------------------------------------------

index 31: 김상범

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 32: 김상배

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 33: 윤상

0                윤상 작곡,작사.. 이별이야기
1     작곡가 5탄 : 윤상의 명곡과 그가 작곡한 노래들
2         윤상 팬들도 모르는 숨겨진 윤상작곡편곡노래
3                      윤상의 플레이리스트
4     [스테이션H] 윤상의 '내 인생 베스트 트랙 7'
5        마음을 적시는 감성 발라드 윤종신&윤상&토이
6        두 아이콘의 음악 열전: 윤상 vs. 유영석
7                윤상이 작곡했던 타가수 노래들
8         꽃보다 청춘 온실속의 화초 윤상의 명곡모음
9     [작곡가]윤상, OnePiece 《발라드, 댄스》
10     윤상(onepiece)이 작곡한 러블리즈 명곡들
11               치밀하고 정교한 사운드, 윤상
Name: plylst_title, dtype: object

---------------------------------------------------------

index 34: 강산에

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 35: 노사연

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 36: 김범룡

0    80년대 남자가왕들 조용필.전영록.이용.최성수.김범룡
Name: plylst_title, dtype: object

---------------------------------------------------------

index 37: 최백호

0    불후의 명곡 전설을 노래하다...최백호, 김연자
Name: plylst_title, dtype: object

---------------------------------------------------------

index 38: 이문세

0     유명가수 리메이크 명곡 1 - 조덕배 & 이문세
1     오늘아침, 이문세입니다 Pop 2009. 06.
2      표현력의 교과서, 이문세의 컬래버레이션 트랙들
3     오늘아침, 이문세입니다 Pop 2009. 05.
4      공연 : 2015 Theatre 이문세 258
5                    이문세와 그의 대표곡
6                     이문세 콘서트 예습
7                     이문세 히트곡 모음
8     오늘아침, 이문세입니다 Kop 2009. 05.
9     오늘아침, 이문세입니다 Kop 2009. 06.
10                        이문세베스트
11    오늘아침, 이문세입니다 Kop 2009. 07.
12               오늘의 추천 가수 - 이문세
13                  대.한.민.국. 이문세
Name: plylst_title, dtype: object

---------------------------------------------------------

index 39: 손무현

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 40: 한동준

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 41: 이동원

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 42: 송대관

0    송대관 태진아 설운도 현철 히트곡 모음
1            송대관 사랑이무어냐 모음
2             송대관 히트곡모음 1집
Name: plylst_title, dtype: object

---------------------------------------------------------

index 43: 강권순

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 44: 프로젝트 살

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 45: 김덕수

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 46: 김매자

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 47: 김명덕

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 48: 김뻑국

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 49: 김성녀

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 50: 김수연

0    김수연과 임동혁이 선보인 최고의 이중주
Name: plylst_title, dtype: object

---------------------------------------------------------

index 51: 김영동

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 52: 김영임

0    천상의 소리꾼 국민명창 김영임
Name: plylst_title, dtype: object

---------------------------------------------------------

index 53: 김영재

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 54: 김영희

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 55: 최성욱

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 56: 김응서

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 57: 김주남

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 58: 노부영

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 59: 박계향

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 60: 박동진

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 61: 박범훈

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 62: 박순금

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 63: 방성춘

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 64: 백진희

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 65: 변종혁

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 66: 서용석

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 67: 성창순

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 68: 신영희

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 69: 안숙선

0    안숙선 노래
Name: plylst_title, dtype: object

---------------------------------------------------------

index 70: 양정화

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 71: 오복녀

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 72: 오정숙

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 73: 원장현

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 74: 유지숙

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 75: 이건희

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 76: 이금미

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 77: Digital Masta

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 78: 이동규

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 79: 이상원

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 80: 이생강

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 81: 이옥천

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 82: 이은관

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 83: 이도형

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 84: 이춘희

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 85: 이호연

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 86: 임정란

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 87: 전숙희

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 88: 정예진

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 89: 조통달

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 90: 지화자

0    지화자 2019! 주말 파티 EDM 65 by 스피닝 레코드
Name: plylst_title, dtype: object

---------------------------------------------------------

index 91: Leif Garrett

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 92: 황병기

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 93: 유정연

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 94: 유진

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 95: 유호

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 96: 윤설희

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 97: 윤종신

0                               윤종신 좋아요 꾸욱.
1             윤종신이 만든 작사,작곡 참여한 명곡 모음 월간윤종신
2                            윤종신덕후의 윤종신 알리기
3                      음유시인 윤종신의 2000년대 가삿말
4                    윤종신 팬이 좋아하는 작사가 윤종신 노래
5                                 히든싱어 윤종신편
6                                       윤종신
7                                       윤종신
8               2017 윤종신 콘서트 '윤종신 좋니?' 셋리스트
9                                  감성보스 윤종신
10                 『가수바라기 No.3』 윤종신의 베스트 30
11    우리나라 뮤지션 특집.지친 하루를 너의 여행으로 만들어줄 "윤종신"
12                     윤종신의 곡중 best of best
13                        인디아티스트와 함께한 월간윤종신
14                                   월간 윤종신
15                            대단한 뮤지션 윤종신 !
16      윤종신 산문집 '계절은 너에게 배웠어' 수록곡 감성 플레이리스트
17                     윤종신 김연우 김광석 이승철 YB 등
18         월간 윤종신 100회. 끝없이 빛나는 윤종신 BEST 명곡
19      작사가 윤종신 콘서트 Part 2. 특강 2교시 set list
20                  팬들이 뽑은 '작사가 윤종신' 노래 30곡
21         윤종신 산문집 <계절은 너에게 배웠어> 수록곡 플레이리스트
22                 마음을 적시는 감성 발라드 윤종신&윤상&토이
23                           월간 윤종신, 끝없는 기록
24                         올드감성 끝판왕 윤종신 유희열
25                                 월간 윤종신 "
26               [발라드] Lyrics by 윤종신 Vol. 1
27                             나의 윤종신노래 top
28                『가수바라기 No.77』 월간윤종신 베스트20
29                      2018 윤종신 전국투어 셋업리스트
30                          오늘의 추천 가수 - 윤종신
31                       윤종신 팬이 추천하는 윤종신 노래
32                  이별전문가 윤종신의 일상적 이별노래들 ;)
33                            월간윤종신.나의베스트곡.
34          작사가 윤종신 콘서트 PART 2. 특강 set list
35               내가 좋아하는 [윤종신 작사 작곡 노래] 모음집
36                     윤종신 음악에 빠지게되는 플레이리스트
Name: plylst_title, dtype: object

---------------------------------------------------------

index 98: Robbie Williams

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

index 99: 윤형주

Series([], Name: plylst_title, dtype: object)

---------------------------------------------------------

#### 쓸만한듯?

### <span style="color:#00c3ff;">어떻게 쓸 것인가?</span>
    
- train data에 개수 추가? ->의미없을듯
- 플레이리스트 타이틀 중 장르 이름이 들어간 플레이리스트 찾기
    - **장르와 노래 연결**해서 추가 작업 필요
- 플레이리스트 타이틀 중 가수 이름과 일치하는 이름이 있는 플레이리스트 찾기
    - **가수별 노래 list 필요**
- **dataframe으로 만들어야할듯?** 아니면 이 dataframe에서 검색해서 index를 뽑음->그다음 검색하는 방법으로 사용해야할 것 같다.

---

# <span style="color:red">----0718, 19 추가내용ㄱ</span>

# train의 song에서 가장 많은 장르를 뽑는다.

In [34]:
train_gen=train

In [35]:
train_gen

,tags,id,plylst_title,songs,like_cnt,updt_date
0,[락],61281,여행같은 음악,"[525514, 129701, 383374, 562083, 297861, 13954...",71,2013-12-19 18:36:19.000
1,"[추억, 회상]",10532,요즘 너 말야,"[432406, 675945, 497066, 120377, 389529, 24427...",1,2014-12-02 16:19:42.000
2,"[까페, 잔잔한]",76951,"편하게, 잔잔하게 들을 수 있는 곡.-","[83116, 276692, 166267, 186301, 354465, 256598...",17,2017-08-28 07:09:34.000
3,"[연말, 눈오는날, 캐럴, 분위기, 따듯한, 크리스마스캐럴, 겨울노래, 크리스마스,...",147456,크리스마스 분위기에 흠뻑 취하고 싶을때,"[394031, 195524, 540149, 287984, 440773, 10033...",33,2019-12-05 15:15:18.000
4,[댄스],27616,추억의 노래 ㅋ,"[159327, 553610, 5130, 645103, 294435, 100657,...",9,2011-10-25 13:54:56.000
...,...,...,...,...,...,...
115066,"[록메탈, 밴드사운드, 록, 락메탈, 메탈, 락, extreme]",120325,METAL E'SM #2,"[429629, 441511, 612106, 516359, 691768, 38714...",3,2020-04-17 04:31:11.000
115067,[일렉],106976,빠른 리스너를 위한 따끈따끈한 최신 인기 EDM 모음!,"[321330, 216057, 534472, 240306, 331098, 23288...",13,2015-12-24 17:23:19.000
115068,"[담시, 가족, 눈물, 그리움, 주인공, 나의_이야기, 사랑, 친구]",11343,#1. 눈물이 앞을 가리는 나의_이야기,"[50512, 249024, 250608, 371171, 229942, 694943...",4,2019-08-16 20:59:22.000
115069,"[잔잔한, 버스, 퇴근버스, Pop, 풍경, 퇴근길]",131982,퇴근 버스에서 편히 들으면서 하루를 마무리하기에 좋은 POP,"[533534, 608114, 343608, 417140, 609009, 30217...",4,2019-10-25 23:40:42.000
115070,"[노래추천, 팝송추천, 팝송, 팝송모음]",100389,FAVORITE POPSONG!!!,"[26008, 456354, 324105, 89871, 135272, 143548,...",17,2020-04-18 20:35:06.000

In [36]:
# 플레이리스트 아이디(id)와 수록곡(songs) 추출
plylst_song_map = train[['id', 'songs']]

# unnest songs
plylst_song_map_unnest = np.dstack(
    (
        np.repeat(plylst_song_map.id.values, list(map(len, plylst_song_map.songs))), 
        np.concatenate(plylst_song_map.songs.values)
    )
)

# unnested 데이터프레임 생성 : plylst_song_map
plylst_song_map = pd.DataFrame(data = plylst_song_map_unnest[0], columns = plylst_song_map.columns)
plylst_song_map['id'] = plylst_song_map['id'].astype(str)
plylst_song_map['songs'] = plylst_song_map['songs'].astype(str)

# unnest 객체 제거
del plylst_song_map_unnest

In [37]:
# 곡 아이디(id)와 대분류 장르코드 리스트(song_gn_gnr_basket) 추출
song_gnr_map = song_meta.loc[:, ['id', 'song_gn_gnr_basket']]

# unnest song_gn_gnr_basket
song_gnr_map_unnest = np.dstack(
    (
        np.repeat(song_gnr_map.id.values, list(map(len, song_gnr_map.song_gn_gnr_basket))), 
        np.concatenate(song_gnr_map.song_gn_gnr_basket.values)
    )
)


# unnested 데이터프레임 생성 : song_gnr_map
song_gnr_map = pd.DataFrame(data = song_gnr_map_unnest[0], columns = song_gnr_map.columns)
song_gnr_map['id'] = song_gnr_map['id'].astype(str)
song_gnr_map.rename(columns = {'id' : 'song_id', 'song_gn_gnr_basket' : 'gnr_code'}, inplace = True)

# unnest 객체 제거
del song_gnr_map_unnest

#---장르

# 1-1. join 목적으로 곡 아이디 integer to string 변환
plylst_song_map['songs'] = plylst_song_map['songs'].astype(str)

# 1-2. 플레이리스트-곡 테이블 plylst_song_map + 곡-장르 테이블 song_gnr_map join
plylst_song_gnr_map = pd.merge(plylst_song_map, song_gnr_map, how = 'left', left_on = 'songs', right_on = 'song_id')

# 2. 플레이리스트 별 곡 장르 수 count 테이블 생성 : plylst_song_gnr_cnt
plylst_song_gnr_cnt = pd.DataFrame(plylst_song_gnr_map.groupby('id').gnr_code.nunique())

In [38]:
plylst_song_gnr_cnt

        gnr_code
id
1              2
1000          10
100000         6
100001        13
100002         6
...          ...
99991          8
99992          3
99993          3
99997          4
99999          5

[115071 rows x 1 columns]

In [39]:
plylst_song_gnr_cnt=plylst_song_gnr_cnt.reset_index()
plylst_song_gnr_cnt

            id  gnr_code
0            1         2
1         1000        10
2       100000         6
3       100001        13
4       100002         6
...        ...       ...
115066   99991         8
115067   99992         3
115068   99993         3
115069   99997         4
115070   99999         5

[115071 rows x 2 columns]

오름차순으로 바꿔도 똑같음. 뭔가 정렬기준이 이상해진듯  
115071이 train인거는 맞는데.. id가 string인듯??

In [40]:
plylst_song_gnr_cnt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115071 entries, 0 to 115070
Data columns (total 2 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   id        115071 non-null  object
 1   gnr_code  115071 non-null  int64
dtypes: int64(1), object(1)
memory usage: 1.8+ MB

object 형식으로 되어있는 것을 확인할 수 있다.

In [41]:
# id를 int형으로 변환
plylst_song_gnr_cnt['id']=pd.to_numeric(plylst_song_gnr_cnt['id'])
plylst_song_gnr_cnt

            id  gnr_code
0            1         2
1         1000        10
2       100000         6
3       100001        13
4       100002         6
...        ...       ...
115066   99991         8
115067   99992         3
115068   99993         3
115069   99997         4
115070   99999         5

[115071 rows x 2 columns]

In [42]:
plylst_song_gnr_cnt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115071 entries, 0 to 115070
Data columns (total 2 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   id        115071 non-null  int64
 1   gnr_code  115071 non-null  int64
dtypes: int64(2)
memory usage: 1.8 MB

In [43]:
#정렬
# 장르 제일 적은거 0개 (id 128219), 가장 많은거 26개
#plylst_song_gnr_cnt=plylst_song_gnr_cnt.sort_values(by=['gnr_code'],axis=0)
plylst_song_gnr_cnt=plylst_song_gnr_cnt.sort_values(by=['id'],axis=0)
plylst_song_gnr_cnt

           id  gnr_code
0           1         2
48395       2         8
65067       4         8
73290       5        10
81634       6         5
...       ...       ...
44566  153423        11
44567  153425         4
44568  153426         5
44569  153427         5
44570  153428         2

[115071 rows x 2 columns]

In [44]:
plylst_song_gnr_map

             id   songs song_id gnr_code
0         61281  525514  525514   GN1400
1         61281  129701  129701   GN0900
2         61281  129701  129701   GN1000
3         61281  383374  383374   GN1000
4         61281  562083  562083   GN0900
...         ...     ...     ...      ...
6837821  100389   51373   51373   GN1300
6837822  100389  640239  640239   GN1500
6837823  100389   13759   13759   GN0900
6837824  100389   13759   13759   GN1000
6837825  100389  154078  154078   GN1000

[6837826 rows x 4 columns]

In [45]:
gnr_count=pd.DataFrame()
#playlist id를 행으로 추가하기
gnr_count['plylst_id']=plylst_song_gnr_cnt['id']
gnr_count=gnr_count.reset_index()
del gnr_count['index']

In [46]:
gnr_count

        plylst_id
0               1
1               2
2               4
3               5
4               6
...           ...
115066     153423
115067     153425
115068     153426
115069     153427
115070     153428

[115071 rows x 1 columns]

In [47]:
#빈 열 만들기
gnr_count['most_appearing_gnr']=pd.Series()

C:\Users\308_2\.conda\envs\minji\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.

In [48]:
gnr_count

        plylst_id  most_appearing_gnr
0               1                 NaN
1               2                 NaN
2               4                 NaN
3               5                 NaN
4               6                 NaN
...           ...                 ...
115066     153423                 NaN
115067     153425                 NaN
115068     153426                 NaN
115069     153427                 NaN
115070     153428                 NaN

[115071 rows x 2 columns]

In [49]:
plylst_song_gnr_map[plylst_song_gnr_map['id']=='1']

        id   songs song_id gnr_code
4583014  1   47805   47805   GN0300
4583015  1  308020  308020   GN0300
4583016  1  662131  662131   GN0300
4583017  1  418970  418970   GN0500
4583018  1  418970  418970   GN0300
4583019  1  117747  117747   GN0500
4583020  1  117747  117747   GN0300

In [50]:
# test, 임의로 '1'이라는 playlist id와 매치
plylst_song_gnr_map[plylst_song_gnr_map['id']=='1'].describe()

       id   songs song_id gnr_code
count   7       7       7        7
unique  1       5       5        2
top     1  418970  418970   GN0300
freq    7       2       2        5

plylst_song_gnr_map['id']가 object여야한다.  
만약에 plylst_song_gnr_map['id']가 정수형인 경우 평균, 최댓값 등이 구해져버린다.   
　　　 id  
count	7.0  
mean	1.0  
std	0.0  
min	1.0  
25%	1.0  
50%	1.0  
75%	1.0  
max	1.0  
이런식으로 나옴

In [51]:
plylst_song_gnr_map[plylst_song_gnr_map['id']=='1'].describe()['gnr_code']['top']

'GN0300'

In [52]:
testmap=pd.DataFrame()
testmap=gnr_count
testmap.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115071 entries, 0 to 115070
Data columns (total 2 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   plylst_id           115071 non-null  int64
 1   most_appearing_gnr  0 non-null       float64
dtypes: float64(1), int64(1)
memory usage: 1.8 MB

In [53]:
# testmap에서 plylst_id의 type가 int64라서 object로 바꿔주겠음
testmap['plylst_id']=testmap['plylst_id'].astype(str)
testmap['most_appearing_gnr']=testmap['most_appearing_gnr'].astype(str)
testmap.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115071 entries, 0 to 115070
Data columns (total 2 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   plylst_id           115071 non-null  object
 1   most_appearing_gnr  115071 non-null  object
dtypes: object(2)
memory usage: 1.8+ MB

In [54]:
type(testmap['plylst_id'][1])

str

In [55]:
# test, 임의로 '1'이라는 playlist id와 매치
testmap['plylst_id'][1]

'2'

In [56]:
plylst_song_gnr_map[plylst_song_gnr_map['id']==testmap['plylst_id'][1]].describe()['gnr_code']['top']

'GN0500'

In [57]:
plylst_song_gnr_map['id']

0           61281
1           61281
2           61281
3           61281
4           61281
            ...
6837821    100389
6837822    100389
6837823    100389
6837824    100389
6837825    100389
Name: id, Length: 6837826, dtype: object

In [58]:
testmap['plylst_id']

0              1
1              2
2              4
3              5
4              6
           ...
115066    153423
115067    153425
115068    153426
115069    153427
115070    153428
Name: plylst_id, Length: 115071, dtype: object

In [59]:
testmap

       plylst_id most_appearing_gnr
0              1                nan
1              2                nan
2              4                nan
3              5                nan
4              6                nan
...          ...                ...
115066    153423                nan
115067    153425                nan
115068    153426                nan
115069    153427                nan
115070    153428                nan

[115071 rows x 2 columns]

In [60]:
plylst_song_gnr_map[plylst_song_gnr_map['id']==testmap['plylst_id'][0]]

        id   songs song_id gnr_code
4583014  1   47805   47805   GN0300
4583015  1  308020  308020   GN0300
4583016  1  662131  662131   GN0300
4583017  1  418970  418970   GN0500
4583018  1  418970  418970   GN0300
4583019  1  117747  117747   GN0500
4583020  1  117747  117747   GN0300

In [61]:
train_topgnr=pd.DataFrame()
train_topgnr=train

#빈 열 만들기
train_topgnr['most_appearing_gnr']=pd.Series()

train_topgnr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115071 entries, 0 to 115070
Data columns (total 7 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   tags                115071 non-null  object
 1   id                  115071 non-null  int64
 2   plylst_title        115071 non-null  object
 3   songs               115071 non-null  object
 4   like_cnt            115071 non-null  int64
 5   updt_date           115071 non-null  object
 6   most_appearing_gnr  0 non-null       float64
dtypes: float64(1), int64(2), object(4)
memory usage: 6.1+ MB

C:\Users\308_2\.conda\envs\minji\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  """

In [62]:
#id를 object로
train_topgnr['id']=train_topgnr['id'].astype(str)
train_topgnr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115071 entries, 0 to 115070
Data columns (total 7 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   tags                115071 non-null  object
 1   id                  115071 non-null  object
 2   plylst_title        115071 non-null  object
 3   songs               115071 non-null  object
 4   like_cnt            115071 non-null  int64
 5   updt_date           115071 non-null  object
 6   most_appearing_gnr  0 non-null       float64
dtypes: float64(1), int64(1), object(5)
memory usage: 6.1+ MB

In [68]:
import time
start = time.time()

for i in range(0,115071):
    train_topgnr['most_appearing_gnr'][i]=plylst_song_gnr_map[plylst_song_gnr_map['id']==train_topgnr['id'][i]].describe()['gnr_code']['top']
    if(i%100==0):
        print(i)
        print("time :", time.time() - start) 
        print("\n")
        
print("FINISH TIME!! :", time.time() - start)

C:\Users\308_2\.conda\envs\minji\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

0
time : 0.3001976013183594


100
time : 27.987226963043213


200
time : 55.47468423843384


300
time : 83.0281355381012


400
time : 110.24134922027588


500
time : 137.27557682991028


600
time : 163.3952717781067


700
time : 189.41136121749878


800
time : 215.3234522342682


900
time : 241.49001026153564


1000
time : 267.5238838195801


1100
time : 293.5658736228943


1200
time : 319.58270049095154


1300
time : 345.55178785324097


1400
time : 371.85097074508667


1500
time : 398.08627223968506


1600
time : 424.24055576324463


1700
time : 450.2106010913849


1800
time : 476.1919026374817


1900
time : 502.19788694381714


2000
time : 528.3695523738861


2100
time : 554.3413982391357


2200
time : 580.3891687393188


2300
time : 606.4554281234741


2400
time : 632.6229748725891


2500
time : 658.6038556098938


2600
time : 684.5321106910706


2700
time : 710.4982266426086


2800
time : 736.5041697025299


2900
time : 762.5323736667633


3000
time : 788.3984415531158


3100
time : 814.4435393810272


3200
time : 840.3905622959137


3300
time : 866.5660755634308


3400
time : 892.7987387180328


3500
time : 918.8541147708893


3600
time : 944.7257297039032


3700
time : 970.6533949375153


3800
time : 996.54372215271


3900
time : 1022.6452527046204


4000
time : 1048.7447731494904


4100
time : 1074.7683007717133


4200
time : 1100.732177734375


4300
time : 1126.9145593643188


4400
time : 1153.0495111942291


4500
time : 1178.9613573551178


4600
time : 1204.863853931427


4700
time : 1230.781590461731


4800
time : 1256.8100690841675


4900
time : 1282.9410166740417


5000
time : 1308.8645131587982


5100
time : 1334.7751865386963


5200
time : 1360.765682220459


5300
time : 1386.6526792049408


5400
time : 1412.7855372428894


5500
time : 1438.6379964351654


5600
time : 1464.6037595272064


5700
time : 1490.6065728664398


5800
time : 1516.5317914485931


5900
time : 1542.4250473976135


6000
time : 1568.3591787815094


6100
time : 1594.269832611084


6200
time : 1620.2949113845825


6300
time : 1646.2475564479828


6400
time : 1672.3603515625


6500
time : 1698.6440715789795


6600
time : 1724.7417922019958


6700
time : 1750.7091908454895


6800
time : 1776.6026225090027


6900
time : 1802.4664371013641


7000
time : 1828.378522157669


7100
time : 1854.4455590248108


7200
time : 1880.444287776947


7300
time : 1906.4709000587463


7400
time : 1932.559018611908


7500
time : 1958.6513905525208


7600
time : 1984.5801014900208


7700
time : 2010.6343500614166


7800
time : 2036.5793159008026


7900
time : 2062.4344053268433


8000
time : 2088.4031703472137


8100
time : 2114.2812910079956


8200
time : 2140.2175014019012


8300
time : 2166.1957669258118


8400
time : 2192.372447490692


8500
time : 2218.5752789974213


8600
time : 2244.5496394634247


8700
time : 2270.438958644867


8800
time : 2296.459644317627


8900
time : 2322.488541841507


9000
time : 2348.4316279888153


9100
time : 2374.481237888336


9200
time : 2400.4831199645996


9300
time : 2426.5220696926117


9400
time : 2452.6447489261627


9500
time : 2478.7753190994263


9600
time : 2504.6921401023865


9700
time : 2530.5901770591736


9800
time : 2556.622654914856


9900
time : 2582.817261695862


10000
time : 2608.7916312217712


10100
time : 2634.602405309677


10200
time : 2660.5748476982117


10300
time : 2686.7026200294495


10400
time : 2712.690605401993


10500
time : 2738.840693950653


10600
time : 2764.720634460449


10700
time : 2790.6409010887146


10800
time : 2816.6213524341583


10900
time : 2842.6936597824097


11000
time : 2868.6198494434357


11100
time : 2894.5536646842957


11200
time : 2920.844297647476


11300
time : 2946.878428220749


11400
time : 2972.802980661392


11500
time : 2999.0338706970215


11600
time : 3025.0462188720703


11700
time : 3051.079005241394


11800
time : 3077.0678787231445


11900
time : 3103.0684900283813


12000
time : 3129.0064833164215


12100
time : 3155.017553329468


12200
time : 3181.016877412796


12300
time : 3207.1135540008545


12400
time : 3233.1985743045807


12500
time : 3259.4388692379


12600
time : 3285.507671356201


12700
time : 3311.583582639694


12800
time : 3337.5270767211914


12900
time : 3363.4288017749786


13000
time : 3389.4084849357605


13100
time : 3415.5078752040863


13200
time : 3441.463700532913


13300
time : 3467.3812532424927


13400
time : 3493.3441038131714


13500
time : 3519.6706454753876


13600
time : 3545.634537935257


13700
time : 3571.661011695862


13800
time : 3597.722091436386


13900
time : 3623.604574203491


14000
time : 3649.6087992191315


14100
time : 3675.5817742347717


14200
time : 3701.5843789577484


14300
time : 3727.6273782253265


14400
time : 3753.6011645793915


14500
time : 3779.8591136932373


14600
time : 3805.8670148849487


14700
time : 3831.8384685516357


14800
time : 3857.83433675766


14900
time : 3883.803158521652


15000
time : 3909.707893848419


15100
time : 3935.7190828323364


15200
time : 3961.61044549942


15300
time : 3987.620170354843


15400
time : 4013.6005811691284


15500
time : 4039.746380329132


15600
time : 4065.7117087841034


15700
time : 4091.582057952881


15800
time : 4117.5733206272125


15900
time : 4143.570249557495


16000
time : 4169.637979507446


16100
time : 4195.532176494598


16200
time : 4221.466698169708


16300
time : 4247.486770868301


16400
time : 4273.4788653850555


16500
time : 4299.632694721222


16600
time : 4325.770706415176


16700
time : 4352.6410484313965


16800
time : 4378.654532194138


16900
time : 4404.788233280182


17000
time : 4430.875182628632


17100
time : 4456.86647605896


17200
time : 4482.970840215683


17300
time : 4509.045120716095


17400
time : 4535.037211894989


17500
time : 4561.176132917404


17600
time : 4587.294497966766


17700
time : 4613.252484560013


17800
time : 4639.143669366837


17900
time : 4665.186231374741


18000
time : 4691.187584400177


18100
time : 4717.3070549964905


18200
time : 4743.326397180557


18300
time : 4769.249867916107


18400
time : 4795.193026542664


18500
time : 4821.284319400787


18600
time : 4847.322950839996


18700
time : 4873.230211496353


18800
time : 4899.211108207703


18900
time : 4925.142509698868


19000
time : 4951.190339803696


19100
time : 4977.245344400406


19200
time : 5003.1660413742065


19300
time : 5029.1308035850525


19400
time : 5055.082455873489


19500
time : 5081.345081329346


19600
time : 5107.473226547241


19700
time : 5133.323856830597


19800
time : 5159.143152713776


19900
time : 5185.0218386650085


20000
time : 5210.986298084259


20100
time : 5236.95333981514


20200
time : 5262.840889930725


20300
time : 5288.8028728961945


20400
time : 5315.005056381226


20500
time : 5341.205351352692


20600
time : 5367.270405292511


20700
time : 5393.332988500595


20800
time : 5419.3400955200195


20900
time : 5445.399304151535


21000
time : 5471.327494382858


21100
time : 5497.3696484565735


21200
time : 5523.316670656204


21300
time : 5549.1990275383


21400
time : 5575.243528842926


21500
time : 5601.353286981583


21600
time : 5627.532079935074


21700
time : 5653.574856996536


21800
time : 5679.640590190887


21900
time : 5705.691268205643


22000
time : 5731.677519321442


22100
time : 5757.569539070129


22200
time : 5783.4846358299255


22300
time : 5809.457951784134


22400
time : 5835.44696855545


22500
time : 5861.651016950607


22600
time : 5887.944939374924


22700
time : 5913.873055458069


22800
time : 5939.844623088837


22900
time : 5965.771162509918


23000
time : 5991.705088853836


23100
time : 6017.611418247223


23200
time : 6043.552188396454


23300
time : 6069.504718542099


23400
time : 6095.516900539398


23500
time : 6121.587752819061


23600
time : 6147.744089126587


23700
time : 6173.708846330643


23800
time : 6199.814091205597


23900
time : 6225.854274511337


24000
time : 6251.763267755508


24100
time : 6277.76171207428


24200
time : 6303.70925617218


24300
time : 6329.551538228989


24400
time : 6355.417717456818


24500
time : 6381.409867048264


24600
time : 6407.590865373611


24700
time : 6433.662834405899


24800
time : 6459.629519462585


24900
time : 6485.616410017014

25000
time : 6511.582785606384


25100
time : 6537.513469219208


25200
time : 6563.485305786133


25300
time : 6589.419936418533


25400
time : 6615.353005170822


25500
time : 6641.363479375839


25600
time : 6667.537497520447


25700
time : 6693.4232614040375


25800
time : 6719.403518199921


25900
time : 6745.463989496231


26000
time : 6771.519901752472


26100
time : 6797.598807096481


26200
time : 6823.664920568466


26300
time : 6849.686430454254


26400
time : 6875.749516248703


26500
time : 6901.832934856415


26600
time : 6928.05692076683


26700
time : 6954.011932373047


26800
time : 6979.911998271942


26900
time : 7005.9020318984985


27000
time : 7031.844758749008


27100
time : 7057.81102514267


27200
time : 7083.777188301086


27300
time : 7109.854519367218


27400
time : 7135.949620723724


27500
time : 7161.882449626923


27600
time : 7188.066106557846


27700
time : 7213.889626979828


27800
time : 7239.87477350235


27900
time : 7265.816854476929


28000
time : 7291.656762599945


28100
time : 7317.507408857346


28200
time : 7343.390634536743


28300
time : 7369.331611394882


28400
time : 7395.398244380951


28500
time : 7421.4929022789


28600
time : 7447.705413341522


28700
time : 7473.543420314789


28800
time : 7499.535515069962


28900
time : 7525.505251646042


29000
time : 7551.438224554062


29100
time : 7577.342417001724


29200
time : 7603.413330793381


29300
time : 7629.405431985855


29400
time : 7655.359114646912


29500
time : 7681.309846401215


29600
time : 7707.494759321213


29700
time : 7733.586621284485


29800
time : 7759.593214511871


29900
time : 7785.602700948715


30000
time : 7811.639267206192


30100
time : 7837.670001506805


30200
time : 7863.700687408447


30300
time : 7889.694257974625


30400
time : 7915.664286136627


30500
time : 7941.661068201065


30600
time : 7967.749792814255


30700
time : 7993.716043710709


30800
time : 8019.902025938034


30900
time : 8045.914161205292


31000
time : 8071.975951194763


31100
time : 8098.031280517578


31200
time : 8123.9868087768555


31300
time : 8150.590167284012


31400
time : 8176.814708471298


31500
time : 8203.398463010788


31600
time : 8229.668346881866


31700
time : 8255.890797376633


31800
time : 8281.936156272888


31900
time : 8307.878016471863


32000
time : 8333.881670951843


32100
time : 8359.825481891632


32200
time : 8385.71471953392


32300
time : 8411.675988435745


32400
time : 8437.63807964325


32500
time : 8463.866519212723


32600
time : 8490.049328565598


32700
time : 8516.19892835617


32800
time : 8542.256846189499


32900
time : 8568.330372333527


33000
time : 8594.345287322998


33100
time : 8620.34635090828


33200
time : 8646.251743793488


33300
time : 8672.183817863464


33400
time : 8698.280142784119


33500
time : 8724.326593875885


33600
time : 8750.518859624863


33700
time : 8776.733148813248


33800
time : 8802.705834388733


33900
time : 8828.637405872345


34000
time : 8854.603722810745


34100
time : 8880.586520671844


34200
time : 8906.646570920944


34300
time : 8932.658643960953


34400
time : 8958.66860818863


34500
time : 8984.730810165405


34600
time : 9010.82990694046


34700
time : 9037.009391069412


34800
time : 9062.987685918808


34900
time : 9089.019918203354


35000
time : 9115.00766825676


35100
time : 9140.945717096329


35200
time : 9166.962974071503


35300
time : 9193.019663095474


35400
time : 9219.119262456894


35500
time : 9245.078316688538


35600
time : 9271.087793827057


35700
time : 9297.198020458221


35800
time : 9323.146477222443


35900
time : 9349.071341276169


36000
time : 9374.953258752823


36100
time : 9401.032439231873


36200
time : 9427.030402421951


36300
time : 9452.984221696854


36400
time : 9478.935897350311


36500
time : 9504.900987386703


36600
time : 9530.908545732498


36700
time : 9557.149947881699


36800
time : 9583.167410850525


36900
time : 9609.168034791946


37000
time : 9635.16864323616


37100
time : 9661.270325183868


37200
time : 9687.23857140541


37300
time : 9713.205798149109


37400
time : 9739.187804698944


37500
time : 9765.102536678314


37600
time : 9791.199278831482


37700
time : 9817.440876483917


37800
time : 9843.305074691772


37900
time : 9869.321897506714


38000
time : 9895.228229522705


38100
time : 9921.194986581802


38200
time : 9946.992864847183


38300
time : 9972.866776704788


38400
time : 9998.844367265701


38500
time : 10024.800904512405


38600
time : 10050.809396982193


38700
time : 10077.062057971954


38800
time : 10103.018933296204


38900
time : 10129.01613330841


39000
time : 10155.045223236084


39100
time : 10181.07909989357


39200
time : 10207.035001039505


39300
time : 10232.985508203506


39400
time : 10258.958441019058


39500
time : 10285.032472610474


39600
time : 10311.113528728485


39700
time : 10337.29196858406


39800
time : 10363.287011623383


39900
time : 10389.192343950272


40000
time : 10415.76458144188


40100
time : 10441.834547758102


40200
time : 10467.837812662125


40300
time : 10493.79068160057


40400
time : 10519.820212602615


40500
time : 10545.80736374855


40600
time : 10571.776720523834


40700
time : 10597.933514356613


40800
time : 10623.884267568588


40900
time : 10649.938970327377


41000
time : 10676.00761461258


41100
time : 10702.101806163788


41200
time : 10728.183866739273


41300
time : 10754.116337060928


41400
time : 10780.141617059708


41500
time : 10806.16438126564


41600
time : 10832.132178544998


41700
time : 10858.403477668762


41800
time : 10884.318614721298


41900
time : 10910.253325939178


42000
time : 10936.14042878151


42100
time : 10962.066427230835


42200
time : 10988.066598176956


42300
time : 11014.067214488983


42400
time : 11040.0827729702


42500
time : 11066.029804468155


42600
time : 11092.051176548004


42700
time : 11118.17653298378


42800
time : 11144.125346422195


42900
time : 11170.043765544891


43000
time : 11195.989645004272


43100
time : 11221.98967051506


43200
time : 11247.96792292595


43300
time : 11273.848253011703


43400
time : 11299.795517921448


43500
time : 11325.855036258698


43600
time : 11351.872126102448


43700
time : 11378.078872919083


43800
time : 11404.106791973114


43900
time : 11430.094534873962


44000
time : 11456.274591445923


44100
time : 11482.292543888092


44200
time : 11508.265244722366


44300
time : 11534.187520503998


44400
time : 11560.162667751312


44500
time : 11586.14909362793


44600
time : 11612.194708108902


44700
time : 11638.310893535614


44800
time : 11664.34611582756


44900
time : 11690.312540054321


45000
time : 11716.194021940231


45100
time : 11742.136747837067


45200
time : 11768.085822105408


45300
time : 11794.038251161575


45400
time : 11820.253504753113


45500
time : 11846.299930095673


45600
time : 11872.333734035492


45700
time : 11898.336458444595


45800
time : 11924.428719520569


45900
time : 11950.361456871033


46000
time : 11976.26236987114


46100
time : 12002.131762981415


46200
time : 12028.04590678215


46300
time : 12054.025029420853


46400
time : 12079.930262088776


46500
time : 12105.910084486008


46600
time : 12131.865094661713


46700
time : 12158.045542478561


46800
time : 12184.278242588043


46900
time : 12210.215638399124


47000
time : 12236.198758840561


47100
time : 12262.19611787796


47200
time : 12288.171544790268


47300
time : 12314.038946390152


47400
time : 12339.905950069427


47500
time : 12365.914063453674


47600
time : 12391.963618278503


47700
time : 12418.078640699387


47800
time : 12444.255551099777


47900
time : 12470.188253879547


48000
time : 12496.215031862259


48100
time : 12522.319071292877


48200
time : 12548.366085290909


48300
time : 12574.323104143143


48400
time : 12600.305884122849


48500
time : 12626.210874795914


48600
time : 12652.178887605667


48700
time : 12678.125655412674


48800
time : 12704.264533758163


48900
time : 12730.226724863052


49000
time : 12756.28759098053


49100
time : 12782.335620641708


49200
time : 12808.420156240463


49300
time : 12834.535267591476


49400
time : 12860.498367547989


49500
time : 12886.502696990967

49600
time : 12912.495484828949


49700
time : 12938.551846504211


49800
time : 12964.654972314835


49900
time : 12990.551581859589


50000
time : 13016.576808691025


50100
time : 13042.518228054047


50200
time : 13068.420812368393


50300
time : 13094.399705410004


50400
time : 13120.503061532974


50500
time : 13146.405991315842


50600
time : 13172.275433301926


50700
time : 13198.237508058548


50800
time : 13224.392158031464


50900
time : 13250.490077257156


51000
time : 13276.392463445663


51100
time : 13302.324224948883


51200
time : 13328.21367764473


51300
time : 13354.095245361328


51400
time : 13380.037443876266


51500
time : 13406.071496963501


51600
time : 13432.103264808655


51700
time : 13458.199197292328


51800
time : 13484.588724136353


51900
time : 13510.621329307556


52000
time : 13536.62546300888


52100
time : 13562.626073122025


52200
time : 13588.64357829094


52300
time : 13614.65152144432


52400
time : 13640.628007888794


52500
time : 13666.567300081253


52600
time : 13692.530729532242


52700
time : 13718.625942468643


52800
time : 13744.825644731522


52900
time : 13770.752814531326


53000
time : 13796.669957637787


53100
time : 13822.571182966232


53200
time : 13848.627049446106


53300
time : 13874.586437225342


53400
time : 13900.553713798523


53500
time : 13926.476119279861


53600
time : 13952.467656373978


53700
time : 13978.519817829132


53800
time : 14004.705466985703


53900
time : 14030.702736616135


54000
time : 14056.656388044357


54100
time : 14082.79052734375


54200
time : 14108.78974366188


54300
time : 14134.868455648422


54400
time : 14160.778487682343


54500
time : 14186.820086479187


54600
time : 14212.900200366974


54700
time : 14238.911133050919


54800
time : 14265.002646446228


54900
time : 14290.93035531044


55000
time : 14316.968302249908


55100
time : 14342.947494983673


55200
time : 14368.960273742676


55300
time : 14394.898498535156


55400
time : 14420.7230052948


55500
time : 14446.692979574203


55600
time : 14472.620964288712


55700
time : 14498.550971031189


55800
time : 14524.657759666443


55900
time : 14550.669121265411


56000
time : 14576.767017364502


56100
time : 14602.923037528992


56200
time : 14629.025881528854


56300
time : 14655.04936504364


56400
time : 14681.146384954453


56500
time : 14707.136953830719


56600
time : 14733.093346118927


56700
time : 14759.025389671326


56800
time : 14785.129909038544


56900
time : 14811.289474487305


57000
time : 14837.162832260132


57100
time : 14863.109271526337


57200
time : 14889.122297048569


57300
time : 14915.18335390091


57400
time : 14941.334878921509


57500
time : 14967.314481496811


57600
time : 14993.246664762497


57700
time : 15019.180587291718


57800
time : 15045.341263532639


57900
time : 15071.407752275467


58000
time : 15097.268793821335


58100
time : 15123.168496608734


58200
time : 15149.131253957748


58300
time : 15175.263496875763


58400
time : 15201.357707500458


58500
time : 15227.192783355713


58600
time : 15253.18174791336


58700
time : 15279.33257651329


58800
time : 15305.378755807877


58900
time : 15331.463764190674


59000
time : 15357.358205080032


59100
time : 15383.32257604599


59200
time : 15409.30170083046


59300
time : 15435.224509239197


59400
time : 15461.158458948135


59500
time : 15487.172580242157


59600
time : 15513.328784704208


59700
time : 15539.458372354507


59800
time : 15565.66191482544


59900
time : 15591.954201936722


60000
time : 15617.960036993027


60100
time : 15643.969543457031


60200
time : 15669.881110906601


60300
time : 15695.748563051224


60400
time : 15721.6957654953


60500
time : 15747.74168753624


60600
time : 15773.762190818787


60700
time : 15799.790842294693


60800
time : 15825.86014008522


60900
time : 15852.115370988846


61000
time : 15878.202739238739


61100
time : 15904.240666151047


61200
time : 15930.215142726898


61300
time : 15956.136654376984


61400
time : 15982.072667598724


61500
time : 16008.032013893127


61600
time : 16033.98740029335


61700
time : 16059.889157295227


61800
time : 16085.900110721588


61900
time : 16112.229691028595


62000
time : 16138.236105680466


62100
time : 16164.127032995224


62200
time : 16190.008902311325


62300
time : 16215.945295095444


62400
time : 16241.916697263718


62500
time : 16267.812668323517


62600
time : 16293.713023900986


62700
time : 16319.581492185593


62800
time : 16345.527983903885


62900
time : 16371.727927446365


63000
time : 16397.693831920624


63100
time : 16423.520465135574


63200
time : 16449.526201725006


63300
time : 16475.52688074112


63400
time : 16501.652701854706


63500
time : 16527.692618846893


63600
time : 16553.617176771164


63700
time : 16579.537497758865


63800
time : 16605.593688964844


63900
time : 16631.75323486328


64000
time : 16657.654927253723


64100
time : 16683.42949771881


64200
time : 16709.524698019028


64300
time : 16735.6072807312


64400
time : 16761.646921396255


64500
time : 16787.588139295578


64600
time : 16813.58562874794


64700
time : 16839.679044485092


64800
time : 16865.684664726257


64900
time : 16891.996683835983


65000
time : 16918.003703594208


65100
time : 16943.8793156147


65200
time : 16969.929321050644


65300
time : 16996.04812836647


65400
time : 17022.181477546692


65500
time : 17048.28726863861


65600
time : 17074.403570652008


65700
time : 17100.52336859703


65800
time : 17126.71603655815


65900
time : 17153.147292375565


66000
time : 17179.32068991661


66100
time : 17205.420110702515


66200
time : 17231.413979768753


66300
time : 17257.551878213882


66400
time : 17283.67205119133


66500
time : 17309.726253271103


66600
time : 17335.764458417892


66700
time : 17361.733714580536


66800
time : 17387.701072454453


66900
time : 17413.869173288345


67000
time : 17439.89328098297


67100
time : 17465.882939100266


67200
time : 17491.82005929947


67300
time : 17517.81753063202


67400
time : 17543.724452018738


67500
time : 17569.73800301552


67600
time : 17595.676597833633


67700
time : 17621.763568639755


67800
time : 17647.820912599564


67900
time : 17674.007645130157


68000
time : 17700.120606660843


68100
time : 17726.138018369675


68200
time : 17752.107053279877


68300
time : 17778.092299699783


68400
time : 17804.041195631027


68500
time : 17830.089307308197


68600
time : 17856.04512000084


68700
time : 17881.91867494583


68800
time : 17907.89246916771


68900
time : 17934.167212724686


69000
time : 17960.367173433304


69100
time : 17986.45477771759


69200
time : 18012.507423877716


69300
time : 18038.64146757126


69400
time : 18064.647839784622


69500
time : 18090.507902622223


69600
time : 18116.56053161621


69700
time : 18142.534068584442


69800
time : 18168.6584379673


69900
time : 18194.8060400486


70000
time : 18220.909115552902


70100
time : 18246.937010526657


70200
time : 18272.981783390045


70300
time : 18299.127444267273


70400
time : 18325.02689886093


70500
time : 18350.971942186356


70600
time : 18376.92387342453


70700
time : 18402.88411974907


70800
time : 18428.96564054489


70900
time : 18455.022497415543


71000
time : 18481.198041439056


71100
time : 18507.128918409348


71200
time : 18533.213335990906


71300
time : 18559.20830845833


71400
time : 18585.193209171295


71500
time : 18611.115700483322


71600
time : 18637.090543985367


71700
time : 18663.13779401779


71800
time : 18689.09772825241


71900
time : 18715.223778247833


72000
time : 18741.418555021286


72100
time : 18767.5143969059


72200
time : 18793.74691772461


72300
time : 18819.950130462646


72400
time : 18846.010179281235


72500
time : 18871.986805915833


72600
time : 18898.01392889023


72700
time : 18924.000026226044


72800
time : 18950.000569581985


72900
time : 18975.93826675415


73000
time : 19002.16813969612


73100
time : 19028.153423547745


73200
time : 19054.231158018112


73300
time : 19080.224928617477


73400
time : 19106.312596797943


73500
time : 19132.380236148834


73600
time : 19158.435632944107


73700
time : 19184.250833034515


73800
time : 19210.08369731903

73900
time : 19236.09059023857


74000
time : 19262.398803949356


74100
time : 19288.343601465225


74200
time : 19314.452502012253


74300
time : 19340.49091243744


74400
time : 19366.497056007385


74500
time : 19392.494176387787


74600
time : 19418.588562726974


74700
time : 19444.625545024872


74800
time : 19470.55108189583


74900
time : 19496.57565522194


75000
time : 19522.753247737885


75100
time : 19548.701749563217


75200
time : 19574.6196269989


75300
time : 19600.56655240059


75400
time : 19626.47149538994


75500
time : 19652.418969154358


75600
time : 19678.44869661331


75700
time : 19704.5440762043


75800
time : 19730.645025491714


75900
time : 19756.667005300522


76000
time : 19782.919788122177


76100
time : 19808.968411445618


76200
time : 19834.954357862473


76300
time : 19860.94639968872


76400
time : 19886.92219567299


76500
time : 19912.863590478897


76600
time : 19938.825532913208


76700
time : 19964.90173316002


76800
time : 19990.861191034317


76900
time : 20016.964875221252


77000
time : 20043.146206855774


77100
time : 20069.03381037712


77200
time : 20095.16798377037


77300
time : 20121.211069345474


77400
time : 20147.258531808853


77500
time : 20173.2946665287


77600
time : 20199.393319368362


77700
time : 20225.49042057991


77800
time : 20251.511979818344


77900
time : 20277.56041765213


78000
time : 20303.845379829407


78100
time : 20329.90915608406


78200
time : 20355.9966776371


78300
time : 20382.014436483383


78400
time : 20408.01661348343


78500
time : 20434.033832788467


78600
time : 20460.050174236298


78700
time : 20486.130924463272


78800
time : 20512.03105187416


78900
time : 20537.928325414658


79000
time : 20564.148588895798


79100
time : 20590.186398983


79200
time : 20616.282863616943


79300
time : 20642.274013996124


79400
time : 20668.226694583893


79500
time : 20694.24241900444


79600
time : 20720.17742586136


79700
time : 20746.050066947937


79800
time : 20771.960566043854


79900
time : 20798.092318058014


80000
time : 20824.33661699295


80100
time : 20850.3773355484


80200
time : 20876.43053984642


80300
time : 20902.522857666016


80400
time : 20928.608754634857


80500
time : 20954.692868232727


80600
time : 20980.571043014526


80700
time : 21006.50228524208


80800
time : 21032.578196048737


80900
time : 21058.577847719193


81000
time : 21084.691419363022


81100
time : 21110.749673843384


81200
time : 21136.640763282776


81300
time : 21162.646872997284


81400
time : 21188.651258468628


81500
time : 21214.777893304825


81600
time : 21240.694974899292


81700
time : 21266.626874923706


81800
time : 21292.631657600403


81900
time : 21318.668845415115


82000
time : 21344.796427726746


82100
time : 21370.93092894554


82200
time : 21396.994364738464


82300
time : 21422.897706985474


82400
time : 21448.941652536392


82500
time : 21474.973544836044


82600
time : 21501.16264152527


82700
time : 21527.26803088188


82800
time : 21553.22950553894


82900
time : 21579.15107011795


83000
time : 21605.28594660759


83100
time : 21631.45113015175


83200
time : 21657.50326538086


83300
time : 21683.481484889984


83400
time : 21709.465431928635


83500
time : 21735.3389878273


83600
time : 21761.274423360825


83700
time : 21787.37543821335


83800
time : 21813.43232870102


83900
time : 21839.53095650673


84000
time : 21865.658366680145


84100
time : 21891.94257593155


84200
time : 21917.967131137848


84300
time : 21943.92112135887


84400
time : 21969.842312574387


84500
time : 21995.807412147522


84600
time : 22021.947555541992


84700
time : 22047.859152555466


84800
time : 22073.812403440475


84900
time : 22099.728721141815


85000
time : 22125.77773165703


85100
time : 22151.902648687363


85200
time : 22177.95919919014


85300
time : 22203.959216833115


85400
time : 22229.81923675537


85500
time : 22255.88539505005


85600
time : 22281.800518751144


85700
time : 22307.71629881859


85800
time : 22333.682440280914


85900
time : 22359.579526901245


86000
time : 22385.640384435654


86100
time : 22411.974408864975


86200
time : 22438.03118443489


86300
time : 22464.047537326813


86400
time : 22490.173545837402


86500
time : 22516.182039022446


86600
time : 22542.077907562256


86700
time : 22568.118564128876


86800
time : 22594.149352550507


86900
time : 22620.111436367035


87000
time : 22646.211993694305


87100
time : 22672.46881699562


87200
time : 22698.550523281097


87300
time : 22724.575382471085


87400
time : 22750.462534427643


87500
time : 22776.536067008972


87600
time : 22802.367879152298


87700
time : 22828.32681798935


87800
time : 22854.290293455124


87900
time : 22880.325099229813


88000
time : 22906.402401447296


88100
time : 22932.549943447113


88200
time : 22958.51350259781


88300
time : 22984.47558093071


88400
time : 23010.585158109665


88500
time : 23036.641949653625


88600
time : 23062.6300907135


88700
time : 23088.656526327133


88800
time : 23114.66368842125


88900
time : 23140.725616455078


89000
time : 23166.640832662582


89100
time : 23192.929909467697


89200
time : 23218.97352051735


89300
time : 23244.873908996582


89400
time : 23270.836980104446


89500
time : 23296.912525177002


89600
time : 23323.13658452034


89700
time : 23349.22930932045


89800
time : 23375.15712738037


89900
time : 23401.121241092682


90000
time : 23427.198969125748


90100
time : 23453.442883968353


90200
time : 23479.42197060585


90300
time : 23505.39142680168


90400
time : 23531.374147176743


90500
time : 23557.428206920624


90600
time : 23583.36595582962


90700
time : 23609.405252933502


90800
time : 23635.350236415863


90900
time : 23661.375217199326


91000
time : 23687.387326717377


91100
time : 23713.581545591354


91200
time : 23739.60922718048


91300
time : 23765.571839809418


91400
time : 23791.51843571663


91500
time : 23817.64464211464


91600
time : 23843.599207878113


91700
time : 23869.660182237625


91800
time : 23895.586881160736


91900
time : 23921.69112968445


92000
time : 23947.777615070343


92100
time : 23973.983598470688


92200
time : 23999.93827366829


92300
time : 24025.919014453888


92400
time : 24051.894620895386


92500
time : 24077.871298789978


92600
time : 24103.822959184647


92700
time : 24129.745369911194


92800
time : 24155.784475564957


92900
time : 24181.72386097908


93000
time : 24207.832610845566


93100
time : 24233.85804581642


93200
time : 24259.87345981598


93300
time : 24285.979682445526


93400
time : 24311.99387049675


93500
time : 24338.02308368683


93600
time : 24364.029462337494


93700
time : 24390.019949913025


93800
time : 24415.94875216484


93900
time : 24441.881769180298


94000
time : 24467.925077199936


94100
time : 24494.1819293499


94200
time : 24520.299114227295


94300
time : 24546.31328201294


94400
time : 24572.18892788887


94500
time : 24598.21245408058


94600
time : 24624.058975696564


94700
time : 24650.000618219376


94800
time : 24675.935007095337


94900
time : 24701.887779951096


95000
time : 24727.837379932404


95100
time : 24753.99207997322


95200
time : 24780.117092609406


95300
time : 24806.94733095169


95400
time : 24834.50074982643


95500
time : 24862.03419303894


95600
time : 24889.508321762085


95700
time : 24916.942039966583


95800
time : 24944.36176919937


95900
time : 24971.732107162476


96000
time : 24999.26446199417


96100
time : 25026.851970672607


96200
time : 25054.486085176468


96300
time : 25081.94836497307


96400
time : 25109.47892642021


96500
time : 25136.840364217758


96600
time : 25164.204426050186


96700
time : 25191.617361068726


96800
time : 25218.909875631332


96900
time : 25246.080039978027


97000
time : 25273.315206050873


97100
time : 25301.02209544182


97200
time : 25328.580028533936


97300
time : 25355.972213983536


97400
time : 25383.58328151703


97500
time : 25410.963505744934


97600
time : 25438.422124624252


97700
time : 25465.81332397461


97800
time : 25493.26149535179


97900
time : 25520.770796775818


98000
time : 25548.39632678032


98100
time : 25576.46452641487


98200
time : 25604.153860569

98300
time : 25631.660868167877


98400
time : 25659.03279685974


98500
time : 25685.631297826767


98600
time : 25711.71838569641


98700
time : 25737.809194803238


98800
time : 25763.886259555817


98900
time : 25789.922317028046


99000
time : 25815.846841573715


99100
time : 25841.92089819908


99200
time : 25868.086919784546


99300
time : 25894.049552679062


99400
time : 25919.997198343277


99500
time : 25945.83819413185


99600
time : 25971.90566635132


99700
time : 25998.02289557457


99800
time : 26024.139189243317


99900
time : 26050.16264486313


100000
time : 26076.27669620514


100100
time : 26102.452878952026


100200
time : 26128.767018079758


100300
time : 26154.78479528427


100400
time : 26180.79897212982


100500
time : 26206.92809700966


100600
time : 26232.918914794922


100700
time : 26258.808399438858


100800
time : 26284.726055383682


100900
time : 26310.67395210266


101000
time : 26336.723295927048


101100
time : 26362.737698554993


101200
time : 26388.942289114


101300
time : 26414.88928604126


101400
time : 26440.877454519272


101500
time : 26466.92013859749


101600
time : 26493.017637968063


101700
time : 26519.150037050247


101800
time : 26545.143946170807


101900
time : 26571.18331551552


102000
time : 26597.1615691185


102100
time : 26623.300866365433


102200
time : 26649.59203529358


102300
time : 26675.438550710678


102400
time : 26701.46490430832


102500
time : 26727.493673801422


102600
time : 26753.544563770294


102700
time : 26779.578521728516


102800
time : 26805.674484968185


102900
time : 26831.603689193726


103000
time : 26857.665613651276


103100
time : 26883.761080741882


103200
time : 26910.111775636673


103300
time : 26936.315321922302


103400
time : 26962.304683685303


103500
time : 26988.33496236801


103600
time : 27014.352699518204


103700
time : 27040.46254134178


103800
time : 27066.47054362297


103900
time : 27092.456618070602


104000
time : 27118.506610393524


104100
time : 27144.458530426025


104200
time : 27170.790684700012


104300
time : 27196.83930182457


104400
time : 27222.873156309128


104500
time : 27248.875756263733


104600
time : 27274.704619407654


104700
time : 27300.728972673416


104800
time : 27326.665037870407


104900
time : 27352.73962688446


105000
time : 27378.82193183899


105100
time : 27404.968752384186


105200
time : 27431.19766664505


105300
time : 27457.262206554413


105400
time : 27483.33015012741


105500
time : 27509.364125728607


105600
time : 27535.452026367188


105700
time : 27561.511535406113


105800
time : 27587.51739168167


105900
time : 27613.45406150818


106000
time : 27639.42985010147


106100
time : 27665.481345891953


106200
time : 27691.750568151474


106300
time : 27717.753227949142


106400
time : 27743.799242019653


106500
time : 27769.78685426712


106600
time : 27795.757340192795


106700
time : 27821.915915489197


106800
time : 27847.89197897911


106900
time : 27873.859078407288


107000
time : 27899.865891456604


107100
time : 27925.953127622604


107200
time : 27952.161853313446


107300
time : 27978.365092277527


107400
time : 28004.278516054153


107500
time : 28030.295859098434


107600
time : 28056.466276407242


107700
time : 28082.493053913116


107800
time : 28108.574164628983


107900
time : 28134.62269091606


108000
time : 28160.51983475685


108100
time : 28186.501708507538


108200
time : 28212.559589624405


108300
time : 28238.610641002655


108400
time : 28264.492064237595


108500
time : 28290.390637397766


108600
time : 28316.368272542953


108700
time : 28342.43035721779


108800
time : 28368.473457336426


108900
time : 28394.437821626663


109000
time : 28420.514164447784


109100
time : 28446.550220489502


109200
time : 28472.632192611694


109300
time : 28498.86436843872


109400
time : 28524.777164697647


109500
time : 28550.6620926857


109600
time : 28576.594056606293


109700
time : 28602.605434417725


109800
time : 28628.576523065567


109900
time : 28654.558363437653


110000
time : 28680.59019088745


110100
time : 28706.549546957016


110200
time : 28732.66831946373


110300
time : 28758.75551891327


110400
time : 28784.530581235886


110500
time : 28810.485827684402


110600
time : 28836.47817850113


110700
time : 28862.5593624115


110800
time : 28888.594967365265


110900
time : 28914.627913951874


111000
time : 28940.58370614052


111100
time : 28966.64136338234


111200
time : 28992.667381048203


111300
time : 29018.966653108597


111400
time : 29044.99856543541


111500
time : 29071.0392742157


111600
time : 29097.141634702682


111700
time : 29123.104533433914


111800
time : 29149.070179224014


111900
time : 29175.053758859634


112000
time : 29201.05512547493


112100
time : 29227.022607326508


112200
time : 29253.115958213806


112300
time : 29279.232184648514


112400
time : 29305.257610321045


112500
time : 29331.305485725403


112600
time : 29357.38710618019


112700
time : 29383.470021486282


112800
time : 29409.551688432693


112900
time : 29435.512895345688


113000
time : 29461.562118291855


113100
time : 29487.467237472534


113200
time : 29513.42930150032


113300
time : 29539.728850126266


113400
time : 29565.812343120575


113500
time : 29591.861253261566


113600
time : 29618.09832930565


113700
time : 29644.254123926163


113800
time : 29670.188311815262


113900
time : 29696.32825613022


114000
time : 29722.348690986633


114100
time : 29748.354582309723


114200
time : 29774.367629766464


114300
time : 29800.678362607956


114400
time : 29826.55950164795


114500
time : 29852.505917310715


114600
time : 29878.455419063568


114700
time : 29904.393573999405


114800
time : 29930.52260375023


114900
time : 29956.599853992462


115000
time : 29982.69838643074


FINISH TIME!! : 30000.85083770752

In [69]:
train_topgnr

,tags,id,plylst_title,songs,like_cnt,updt_date,most_appearing_gnr
0,[락],61281,여행같은 음악,"[525514, 129701, 383374, 562083, 297861, 13954...",71,2013-12-19 18:36:19.000,GN0900
1,"[추억, 회상]",10532,요즘 너 말야,"[432406, 675945, 497066, 120377, 389529, 24427...",1,2014-12-02 16:19:42.000,GN0100
2,"[까페, 잔잔한]",76951,"편하게, 잔잔하게 들을 수 있는 곡.-","[83116, 276692, 166267, 186301, 354465, 256598...",17,2017-08-28 07:09:34.000,GN0400
3,"[연말, 눈오는날, 캐럴, 분위기, 따듯한, 크리스마스캐럴, 겨울노래, 크리스마스,...",147456,크리스마스 분위기에 흠뻑 취하고 싶을때,"[394031, 195524, 540149, 287984, 440773, 10033...",33,2019-12-05 15:15:18.000,GN0100
4,[댄스],27616,추억의 노래 ㅋ,"[159327, 553610, 5130, 645103, 294435, 100657,...",9,2011-10-25 13:54:56.000,GN0200
...,...,...,...,...,...,...,...
115066,"[록메탈, 밴드사운드, 록, 락메탈, 메탈, 락, extreme]",120325,METAL E'SM #2,"[429629, 441511, 612106, 516359, 691768, 38714...",3,2020-04-17 04:31:11.000,GN1000
115067,[일렉],106976,빠른 리스너를 위한 따끈따끈한 최신 인기 EDM 모음!,"[321330, 216057, 534472, 240306, 331098, 23288...",13,2015-12-24 17:23:19.000,GN1100
115068,"[담시, 가족, 눈물, 그리움, 주인공, 나의_이야기, 사랑, 친구]",11343,#1. 눈물이 앞을 가리는 나의_이야기,"[50512, 249024, 250608, 371171, 229942, 694943...",4,2019-08-16 20:59:22.000,GN0100
115069,"[잔잔한, 버스, 퇴근버스, Pop, 풍경, 퇴근길]",131982,퇴근 버스에서 편히 들으면서 하루를 마무리하기에 좋은 POP,"[533534, 608114, 343608, 417140, 609009, 30217...",4,2019-10-25 23:40:42.000,GN1000
115070,"[노래추천, 팝송추천, 팝송, 팝송모음]",100389,FAVORITE POPSONG!!!,"[26008, 456354, 324105, 89871, 135272, 143548,...",17,2020-04-18 20:35:06.000,GN1000

In [70]:
#dataframe으로 저장
train_topgnr.to_json('./train_topgnr.json', orient='table')

In [48]:
new_data = pd.read_json('./train_topgnr.json', orient='table')
new_data

,tags,id,plylst_title,songs,like_cnt,updt_date,most_appearing_gnr
0,[락],61281,여행같은 음악,"[525514, 129701, 383374, 562083, 297861, 13954...",71,2013-12-19 18:36:19.000,GN0900
1,"[추억, 회상]",10532,요즘 너 말야,"[432406, 675945, 497066, 120377, 389529, 24427...",1,2014-12-02 16:19:42.000,GN0100
2,"[까페, 잔잔한]",76951,"편하게, 잔잔하게 들을 수 있는 곡.-","[83116, 276692, 166267, 186301, 354465, 256598...",17,2017-08-28 07:09:34.000,GN0400
3,"[연말, 눈오는날, 캐럴, 분위기, 따듯한, 크리스마스캐럴, 겨울노래, 크리스마스,...",147456,크리스마스 분위기에 흠뻑 취하고 싶을때,"[394031, 195524, 540149, 287984, 440773, 10033...",33,2019-12-05 15:15:18.000,GN0100
4,[댄스],27616,추억의 노래 ㅋ,"[159327, 553610, 5130, 645103, 294435, 100657,...",9,2011-10-25 13:54:56.000,GN0200
...,...,...,...,...,...,...,...
115066,"[록메탈, 밴드사운드, 록, 락메탈, 메탈, 락, extreme]",120325,METAL E'SM #2,"[429629, 441511, 612106, 516359, 691768, 38714...",3,2020-04-17 04:31:11.000,GN1000
115067,[일렉],106976,빠른 리스너를 위한 따끈따끈한 최신 인기 EDM 모음!,"[321330, 216057, 534472, 240306, 331098, 23288...",13,2015-12-24 17:23:19.000,GN1100
115068,"[담시, 가족, 눈물, 그리움, 주인공, 나의_이야기, 사랑, 친구]",11343,#1. 눈물이 앞을 가리는 나의_이야기,"[50512, 249024, 250608, 371171, 229942, 694943...",4,2019-08-16 20:59:22.000,GN0100
115069,"[잔잔한, 버스, 퇴근버스, Pop, 풍경, 퇴근길]",131982,퇴근 버스에서 편히 들으면서 하루를 마무리하기에 좋은 POP,"[533534, 608114, 343608, 417140, 609009, 30217...",4,2019-10-25 23:40:42.000,GN1000
115070,"[노래추천, 팝송추천, 팝송, 팝송모음]",100389,FAVORITE POPSONG!!!,"[26008, 456354, 324105, 89871, 135272, 143548,...",17,2020-04-18 20:35:06.000,GN1000

In [46]:
# song id별 장르 목록
song_gnr_map

       song_id gnr_code
0            0   GN0900
1            1   GN1600
2            2   GN0900
3            3   GN1100
4            4   GN1800
...        ...      ...
802854  707984   GN2000
802855  707985   GN0900
802856  707986   GN0100
802857  707987   GN1800
802858  707988   GN0600

[802859 rows x 2 columns]

In [47]:
#플레이리스트별 노래 목록
plylst_song_map

             id   songs
0         61281  525514
1         61281  129701
2         61281  383374
3         61281  562083
4         61281  297861
...         ...     ...
5285866  100389  111365
5285867  100389   51373
5285868  100389  640239
5285869  100389   13759
5285870  100389  154078

[5285871 rows x 2 columns]

# 학습 방향..?
- ml, dl 사용을 위하여 train data를 어떻게 학습시킬건가